[containers]
netns="host"
userns="host"
ipcns="host"
utsns="private"
cgroupns="host"
cgroups="disabled"
log_driver = "k8s-file"
[engine]
cgroup_manager = "cgroupfs"
events_logger="file"
# The default shm lock can race across multiple jobs during init. Use the file
# backed lock so we can split it per invocation, like we do with everything
# else podman.
lock_type = "file"
runtime="crun"
