{
 "title": "iDKG",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "label": "IC", "query": { "query": "label_values(ic)" } },
   {
    "name": "ic_subnet",
    "label": "IC Subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\"}, instance)"
    }
   },
   {
    "name": "instance_host",
    "label": "Instance Host",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\"}, instance)"
    }
   },
   {
    "name": "dc",
    "label": "DC",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\"}, instance)"
    }
   },
   {
    "name": "idkg_method_name",
    "label": "iDKG method name",
    "query": {
     "query": "label_values(crypto_duration_seconds_sum{domain=\"idkg_protocol\",scope=\"full\"}, method_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Successful iDKG operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$idkg_method_name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "repeat": "idkg_method_name",
   "yaxes": [
    { "format": "short", "label": "operations per minute" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n        sum by (le) (increase(crypto_duration_seconds_bucket{domain=\"idkg_protocol\",method_name=~\"$idkg_method_name\",result=\"ok\",scope=\"full\",instance=~\"\\\\[?$dc:.*\",instance=~\"($instance_host):[0-9]+\"}[$__interval])/($__interval_ms/1000/60)),\n          \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\")",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Failed iDKG operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "$idkg_method_name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "operations per minute" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n        sum by (le, result) (increase(crypto_duration_seconds_bucket{domain=\"idkg_protocol\",method_name=~\"$idkg_method_name\",result!=\"ok\",scope=\"full\",instance=~\"\\\\[?$dc:.*\",instance=~\"($instance_host):[0-9]+\"}[$__interval])/($__interval_ms/1000/60)),\n          \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\")",
     "legendFormat": "{{le}} {{result}}"
    }
   ]
  },
  {
   "title": "load_transcript failures",
   "type": "graph",
   "description": "Specific load_transcript failures for the iDKG protocol which can serve as indicators that a subnet key may be getting lost",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "total failures" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n      crypto_idkg_load_transcript_error{ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",ic_subnet=~\".+\",instance=~\"\\\\[?$dc:.*\",instance=~\"($instance_host):[0-9]+\"} > 0,\n      \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\")",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "load_transcript failures above threshold by subnet",
   "type": "graph",
   "description": "Specific load_transcript failures for the iDKG protocol on more than threshold number of nodes per subnet",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "nodes with failures" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n      count by (job, ic, ic_subnet) (rate(crypto_idkg_load_transcript_error{job=\"replica\",ic=\"$ic\",ic_subnet=~\".+\"}[1h]) > 0)\n            >\n              floor((job_ic_icsubnet:up:count{job=\"replica\",ic=\"$ic\",ic_subnet=~\".+\"} - 1) / 3),\n      \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\")",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  }
 ]
}