{
 "title": "Trim",
 "description": "fstrim runs on the guest OS.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "label": "IC", "query": { "query": "label_values(ic)" } },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{ic=\"$ic\",job=\"node_exporter\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   },
   {
    "name": "hostos_version",
    "label": "Host OS Version",
    "query": {
     "query": "label_values(hostos_version{ic=\"$ic\",job=\"host_node_exporter\"}, version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "fstrim_runs_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(ic_node) (fstrim_runs_total{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}) * on (ic_node) group_left sum by (ic_node) (hostos_version{version=~\"$hostos_version\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fstrim_runs_total increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(ic_node) (increase(fstrim_runs_total{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[90d]) * on (ic_node) group_left sum by (ic_node) (hostos_version{version=~\"$hostos_version\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fstrim_last_run_duration_milliseconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(ic_node) (fstrim_last_run_duration_milliseconds{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}) * on (ic_node) group_left sum by (ic_node) (hostos_version{version=~\"$hostos_version\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fstrim last run failures",
   "type": "graph",
   "description": "Success: 1, failure: 0",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(ic_node) (fstrim_last_run_success{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} == 0) * on (ic_node) group_left sum by (ic_node) (hostos_version{version=~\"$hostos_version\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nodes assigned to subnets that have not run fstrim for over two weeks",
   "type": "graph",
   "description": "Finds nodes that i) have not run fstrim at all in the past 14d, and ii) have been up and assigned to a subnet for at least 90% of the time during the past 14d.\nIf nodes show up here, check their status on this dashboard: https://dashboard.internal.dfinity.network/network/mainnet/topology\nIf they are assigned to a subnet and healthy, there may be a problem. Note that nodes that have only recently been assigned to a subnet, but have not yet run fstrim, will also appear here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n    (\n        increases_over_time(\n            fstrim_runs_total{ic=\"mercury\", ic_subnet=~\".+\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", job=\"node_exporter\"}[14d]\n        ) == bool 0\n    ) * (\n        avg_over_time(\n            (\n                up{ic=\"mercury\", ic_subnet=~\".+\", ic_subnet=~\"$ic_subnet\",instance=~\"$instance\", job=\"node_exporter\"} or on() vector(0)\n            )[14d]\n        ) > bool 0.9\n    )\n) > 0",
     "legendFormat": "{{ic_node}}"
    }
   ]
  }
 ]
}