= Guest OS

'GuestOS' refers to the operating system running inside a QEMU virtual machine on the HostOS. A GuestOS image consists of the base Ubuntu system, along with the replica and orchestrator binaries. The IC software runs inside the GuestOS virtual machine.

The GuestOS virtual machine ensures a consistent runtime environment across various hardware platforms for the GuestOS and its services (orchestrator, replica, etc.). Moreover, it provides a method for upgrading the GuestOS and all its services in a unified manner.

== How to build and run GuestOS
=== Building GuestOS

To build a GuestOS image, refer to the link:../README.adoc[IC-OS README]

=== Running GuestOS locally

This requires QEMU with qemu-system and qemu-kvm installed on the machine.

Bazel can be used to boot a local VM with a GuestOS like this:

    bazel run //ic-os/guestos/envs/dev:launch-local-vm

In a VM or container without KVM support, use:

    bazel run //ic-os/guestos/envs/dev:launch-local-vm-no-kvm

The GuestOS image (`disk.img`) can booted directly in QEMU using the following command:

    qemu-system-x86_64 \
    -nographic -m 4G \
    -bios /usr/share/OVMF/OVMF_CODE.fd \
    -drive file=disk.img,format=raw,if=virtio

* Note: Press `Ctrl-A` followed by `x` to exit the QEMU console.

Alternatively, Bazel can be used to perform a testnet deployment. For documentation on this process, see ic/testnet/tools/README.md.

==== Launch a GuestOS VM on farm

Instead of running GuestOS locally in qemu, you can launch a GuestOS virtual machine on Farm:

    bazel run --config=systest //ic-os/guestos/envs/dev:launch-remote-vm

The program will spin up a new GuestOS VM on Farm, and the machine can then be accessed via SSH.

For more details about the program, refer to the `rs/ic_os/launch-single-vm` directory.

== Developing the Ubuntu system

The Ubuntu configuration and system logic is contained in the components/ subdirectory.
See instructions link:components/README.adoc#[here] on how to make changes to the OS.

For further reading, see the docs in the
link:docs/README.adoc#[docs/ subdirectory]
