= Guest OS

'GuestOS' refers to the operating system running inside a QEMU virtual machine on the HostOS. A GuestOS image consists of the base Ubuntu system, along with the replica and orchestrator binaries. The IC software runs inside the GuestOS virtual machine.

The GuestOS virtual machine ensures a consistent runtime environment across various hardware platforms for the GuestOS and its services (orchestrator, replica, etc.). Moreover, it provides a method for upgrading the GuestOS and all its services in a unified manner.

== How to build and run GuestOS
=== Building GuestOS

To build a GuestOS image, refer to the link:../README.adoc[IC-OS README]

=== Running GuestOS locally

This requires QEMU with qemu-system and qemu-kvm installed on the machine.

The GuestOS image (`disk.img`) can booted directly in QEMU using the following command:

    qemu-system-x86_64 \
    -machine type=q35,accel=kvm \
    -enable-kvm \
    -nographic \
    -m 4G \
    -bios /usr/share/ovmf/OVMF.fd \
    -device vhost-vsock-pci,guest-cid=\\$$CID \
    -drive file=disk.img,format=raw,if=virtio \
    -netdev user,id=user.0,hostfwd=tcp::2222-:22 \
    -device virtio-net,netdev=user.0

* Note: Press `Ctrl-A` followed by `x` to exit the QEMU console.

== Developing the Ubuntu system

The Ubuntu configuration and system logic is contained in the components/ subdirectory.
See instructions link:components/README.adoc#[here] on how to make changes to the OS.

For further reading, see the docs in the
link:docs/README.adoc#[docs/ subdirectory]

== Performance Benchmarking

Performance benchmarks are run in GuestOS, on hardware, every day during the nightly
link:../../.github/workflows-source/schedule-daily.yml[`Bazel Test Bare Metal`] job.

This job runs commands from link:../dev-tools/bare_metal_deployment/benchmark_runner.sh[`benchmark_runner.sh`],
and expects that results are placed into the `results` folder on the node. All results are then
dumped into the logs of the CI job.

Currently, node metrics are not collected, but we hope to point the monitoring infrastructure at
this node to track performance changes over time.

These benchmarks can be run manually, following the benchmarking instructions
link:../dev-tools/bare_metal_deployment/README.md[here], but it is easiest to trigger the nightly
job via https://github.com/dfinity/ic/actions.
