{
 "title": "ckBTC Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "token", "label": "Token", "query": "ckbtc,cktestbtc" },
   {
    "name": "num_new_utxos",
    "query": "0 : 0, 1 : 1, ([2-9][0-9]*) : 2+"
   },
   {
    "name": "num_utxo_pages",
    "query": "1 : 1, 2 : 2, ([3-9][0-9]*) : 3+"
   },
   { "name": "get_utxos_call_source", "label": "Get UTXOs Call Source", "query": "minter, client" }
  ]
 },
 "panels": [
  {
   "title": "Canister Cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TC" } },
   "targets": [
    {
     "expr": "ckbtc_minter_cycle_balance{token = \"$token\"}/1e12",
     "legendFormat": "minter"
    },
    {
     "expr": "ledger_cycle_balance{token = \"$token\"}/1e12",
     "legendFormat": "ledger"
    },
    {
     "expr": "index_cycle_balance{token = \"$token\"}/1e12",
     "legendFormat": "index"
    },
    {
     "expr": "archive_cycle_balance{token = \"$token\"}/1e12",
     "legendFormat": "archive"
    }
   ]
  },
  {
   "title": "Retrieve Requests By Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ckbtc_minter_retrieve_btc_request_count{token = \"$token\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Stable Memory (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ckbtc_minter_stable_memory_bytes{token=\"$token\"} or stable_memory_bytes{token=\"$token\", job=~\".*-minter\"}",
     "legendFormat": "minter"
    },
    {
     "expr": "ledger_stable_memory_bytes{token=\"$token\"} or stable_memory_bytes{token=\"${token}\", job=~\".*-ledger\"}",
     "legendFormat": "ledger"
    },
    {
     "expr": "index_stable_memory_bytes{token=\"$token\"} or stable_memory_bytes{token=\"${token}\", job=~\".*-index\"}",
     "legendFormat": "index"
    },
    {
     "expr": "archive_stable_memory_bytes{token=\"$token\"} or stable_memory_bytes{token=\"${token}\", job=~\".*-archive\"}",
     "legendFormat": "archive"
    },
    {
     "expr": "stable_memory_bytes{token=\"$token\", job=~\".*-kyt\"}",
     "legendFormat": "KYT"
    }
   ]
  },
  {
   "title": "Heap Memory (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ckbtc_minter_heap_memory_bytes{token=\"$token\"} or heap_memory_bytes{token=\"$token\", job=~\".*-minter\"}",
     "legendFormat": "minter"
    },
    {
     "expr": "ledger_total_memory_bytes{token=\"$token\"} or heap_memory_bytes{token=\"${token}\", job=~\".*-ledger\"}",
     "legendFormat": "ledger"
    },
    {
     "expr": "index_total_memory_bytes{token=\"$token\"} or heap_memory_bytes{token=\"${token}\", job=~\".*-index\"}",
     "legendFormat": "index"
    },
    {
     "expr": "archive_total_memory_bytes{token=\"$token\"} or heap_memory_bytes{token=\"${token}\", job=~\".*-archive\"}",
     "legendFormat": "archive"
    }
   ]
  },
  {
   "title": "Cycle Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "BC/h" } },
   "targets": [
    {
     "expr": "-delta(ckbtc_minter_cycle_balance{token = \"$token\"}[1h])/1e9",
     "legendFormat": "minter"
    },
    {
     "expr": "-delta(ledger_cycle_balance{token = \"$token\"}[1h])/1e9",
     "legendFormat": "ledger"
    },
    {
     "expr": "-delta(index_cycle_balance{token = \"$token\"}[1h])/1e9",
     "legendFormat": "index"
    },
    {
     "expr": "-delta(archive_cycle_balance{token = \"$token\"}[1h])/1e9",
     "legendFormat": "archive"
    }
   ]
  },
  {
   "title": "Available UTXO Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "utxos" } },
   "targets": [
    {
     "expr": "ckbtc_minter_utxos_available{token = \"$token\"}"
    }
   ]
  },
  {
   "title": "Minter BTC Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "ckbtc_minter_btc_balance{token = \"$token\"}/1e8",
     "legendFormat": "btc owned"
    },
    {
     "expr": "ledger_total_supply{token = \"$token\"}/1e8",
     "legendFormat": "ckbtc circulated"
    },
    {
     "expr": "ckbtc_minter_btc_balance{token = \"$token\"}/1e8 - on(token) ledger_total_supply{token = \"$token\"}/1e8",
     "legendFormat": "surplus"
    }
   ]
  },
  {
   "title": "Ledger Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "transactions" } },
   "targets": [
    {
     "expr": "ledger_archived_transactions{token = \"$token\"} + ledger_transactions{token = \"$token\"}",
     "legendFormat": "ledger transactions"
    },
    {
     "expr": "index_number_of_blocks{token = \"$token\"}",
     "legendFormat": "indexed transactions"
    }
   ]
  },
  {
   "title": "Median fee per vbyte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "ckbtc_minter_median_fee_per_vbyte{token=\"$token\"}/1e11",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent In-flow/Out-flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "ckbtc_minter_concurrent_update_balance_count{token = \"$token\"}",
     "legendFormat": "update_balance count"
    },
    {
     "expr": "ckbtc_minter_concurrent_retrieve_btc_count{token = \"$token\"}",
     "legendFormat": "retrieve_btc count"
    }
   ]
  },
  {
   "title": "Update Balance Method Latency - ${num_new_utxos:label} New UTXOs",
   "type": "histogram",
   "description": "Histogram showing the latency of the ckBTC update_balance method in milliseconds when there were ${num_new_utxos:label} new UTXOs.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "repeat": "num_new_utxos",
   "fieldConfig": { "defaults": { "unit": "si:Requests" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n    sum by(le) (\n        increase(ckbtc_minter_update_calls_latency_bucket{num_new_utxos=~\"${num_new_utxos:value}\"}[$__range])\n    ), \n\"le\", \"${1}ms\", \"le\", \"([0-9]+)\"), \n\"le\", \"∞\", \"le\", \".*Inf\")",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Get UTXOs Method Latency - ${num_utxo_pages:label} UTXO Pages",
   "type": "histogram",
   "description": "Histogram showing the latency of the ckBTC get_utxos method in milliseconds when there were ${num_utxo_pages:label} pages of UTXOs.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "repeat": "num_utxo_pages",
   "fieldConfig": { "defaults": { "unit": "si:Requests" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n    sum by(le) (\n        increase(ckbtc_minter_get_utxos_latency_bucket{num_pages=~\"${num_utxo_pages:value}\",call_source=\"$get_utxos_call_source\"}[$__range])\n    ), \n\"le\", \"${1}ms\", \"le\", \"([0-9]+)\"), \n\"le\", \"∞\", \"le\", \".*Inf\")",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Number of UTXOs in Get UTXOs Response - Call Source: ${get_utxos_call_source:label}",
   "type": "histogram",
   "description": "Histogram showing the number of UTXOs returned in the response of the ckBTC get_utxos method when the call source was the ${get_utxos_call_source:label}.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "si:Requests" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(sum by(le) (increase(ckbtc_minter_get_utxos_result_size_bucket{call_source=\"$get_utxos_call_source\"}[$__range])), \"le\", \"${1} UTXOs\", \"le\", \"([0-9]+)\"), \"le\", \"∞\", \"le\", \".*Inf\")",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}