# Block device read_ahead configuration
#

block/dm-1/queue/read_ahead_kb = 128
block/dm-2/queue/read_ahead_kb = 128
block/dm-3/queue/read_ahead_kb = 128
block/dm-4/queue/read_ahead_kb = 128
block/dm-5/queue/read_ahead_kb = 128
block/dm-6/queue/read_ahead_kb = 128
block/vda/queue/read_ahead_kb = 128
