#!/usr/bin/env bash
#
# Generate the bootstrap state for a 4-node, single-subnet local IC network.
# Writes to ./bootstrap/.
#
# Topology (single Application subnet, which doubles as NNS):
#   Subnet 0: 4 nodes
#     node-0  fd00:1::10
#     node-1  fd00:1::11
#     node-2  fd00:1::12
#     node-3  fd00:1::13
#   Ports per node (each container has its own netns, so identical is fine):
#     xnet/P2P: 4100
#     HTTP API: 8080
#     metrics:  9090
#
# Environment:
#   REPLICA_VERSION   defaults to 0.9.0
#   PRESERVE=1        don't wipe ./bootstrap/ before generating
#
# This prep is "deploy-ready":
#   - provisional_whitelist = ["*"]   any principal may create canisters
#                                     via provisional_create_canister_with_cycles
#                                     (this is what dfx uses for local deploys)
#   - use_specified_ids_allocation_range gives the subnet the canister-ID range
#     that dfx and the IC spec expect (so e.g. the default canister IDs match
#     production / mainnet conventions).
#
# This config is fine for both:
#   - a bare application subnet (just deploy canisters; current default)
#   - a future NNS-installed subnet (Phase 4 will add nns-init.sh as an
#     additive step that installs governance/registry/etc. as canisters here)
set -euo pipefail

LOCAL_NET_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$LOCAL_NET_DIR"

SUBNET_IDX=0
REPLICA_VERSION="${REPLICA_VERSION:-0.9.0}"
NODE_IPS=(
    "fd00:1::10"
    "fd00:1::11"
    "fd00:1::12"
    "fd00:1::13"
)
XNET_PORT=4100
HTTP_PORT=8080
METRICS_PORT=9090

BOOTSTRAP="$LOCAL_NET_DIR/bootstrap"
if [ -d "$BOOTSTRAP" ] && [ "${PRESERVE:-0}" != "1" ]; then
    echo "==> Removing existing $BOOTSTRAP (set PRESERVE=1 to skip)"
    rm -rf "$BOOTSTRAP"
fi
mkdir -p "$BOOTSTRAP"

# Verify the runtime image exists.
if ! docker image inspect ic-replica:dev >/dev/null 2>&1; then
    echo "ERROR: ic-replica:dev image not found. Run ./build.sh first." >&2
    exit 1
fi

NODE_ARGS=()
for i in 0 1 2 3; do
    ip="${NODE_IPS[$i]}"
    NODE_ARGS+=(--node "idx:$i,subnet_idx:$SUBNET_IDX,xnet_api:\"[$ip]:$XNET_PORT\",public_api:\"[$ip]:$HTTP_PORT\"")
done

# Provisional whitelist: ["*"] = any principal can create canisters via
# provisional_create_canister_with_cycles. ic-prep reads this from a JSON file.
WHITELIST_FILE="$BOOTSTRAP/.provisional_whitelist.json"
mkdir -p "$BOOTSTRAP"
cat >"$WHITELIST_FILE" <<EOF
{ "provisional_whitelist": ["*"] }
EOF

echo "==> ic-prep"
echo "    Replica version: $REPLICA_VERSION"
echo "    Subnet:          $SUBNET_IDX (NNS)"
for i in 0 1 2 3; do
    echo "    node-$i          ${NODE_IPS[$i]}  xnet=$XNET_PORT  http=$HTTP_PORT  metrics=$METRICS_PORT"
done
echo

# Run ic-prep inside the runtime image. --user 0:0 sidesteps any UID
# mismatch between host and container for the output directory.
docker run --rm \
    --platform=linux/amd64 \
    --user 0:0 \
    -v "$BOOTSTRAP:/bootstrap" \
    -w /bootstrap \
    --entrypoint /usr/local/bin/ic-prep \
    ic-replica:dev \
    --working-dir /bootstrap \
    --replica-version "$REPLICA_VERSION" \
    --allow-empty-update-image \
    --nns-subnet-index "$SUBNET_IDX" \
    --provisional-whitelist /bootstrap/.provisional_whitelist.json \
    --use-specified-ids-allocation-range \
    "${NODE_ARGS[@]}"

# Permissions: ic-prep wrote as root inside the container. Make the
# resulting tree readable by the host user so we can inspect it.
docker run --rm \
    --platform=linux/amd64 \
    --user 0:0 \
    -v "$BOOTSTRAP:/bootstrap" \
    ic-replica:dev \
    chown -R "$(id -u):$(id -g)" /bootstrap 2>/dev/null || true

echo
echo "==> Generating per-node replica config files"
for i in 0 1 2 3; do
    ip="${NODE_IPS[$i]}"
    cat >"$BOOTSTRAP/node-$i/ic.json5" <<EOF
{
  // Generated by prep.sh — node-$i ($ip)
  registry_client: {
    local_store: "/etc/ic/registry",
  },
  transport: {
    node_ip: "$ip",
    listening_port: $XNET_PORT,
  },
  state_manager: {
    state_root: "/var/lib/ic/state",
  },
  artifact_pool: {
    consensus_pool_path: "/var/lib/ic/consensus_pool",
    // usize::MAX on 64-bit, matches the sample defaults.
    ingress_pool_max_count: 9223372036854775807,
    ingress_pool_max_bytes: 9223372036854775807,
    backup: {
      spool_path: "/var/lib/ic/backup",
      retention_time_secs: 3600,
      purging_interval_secs: 3600,
    },
  },
  crypto: {
    crypto_root: "/etc/ic/crypto",
  },
  http_handler: {
    listen_addr: "[::]:$HTTP_PORT",
  },
  metrics: {
    exporter: {
      http: "[::]:$METRICS_PORT",
    },
  },
  logger: {
    level: "info",
    format: "text_full",
  },
}
EOF
done

echo
echo "==> Bootstrap layout:"
echo "    $BOOTSTRAP/"
ls -la "$BOOTSTRAP/" | sed 's/^/      /'
echo
for i in 0 1 2 3; do
    echo "    $BOOTSTRAP/node-$i/"
    ls -la "$BOOTSTRAP/node-$i/" 2>/dev/null | sed 's/^/      /'
    echo
done

echo "Done."
echo
echo "Next:"
echo "  - Phase 3: compose.yml that mounts these dirs into 4 containers"
echo "  - Phase 4: ic-nns-init to install NNS canisters once the network is up"
