[package]
name = "release-runscript"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[[bin]]
name = "release-runscript"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
itertools = { workspace = true }
url = { workspace = true }
