load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")

package(default_visibility = ["//rs:ic-os-pkg"])

rust_binary(
    name = "upgrade_proxy",
    srcs = ["src/main.rs"],
    deps = [
        "@crate_index//:anyhow",
        "@crate_index//:hex",
        "@crate_index//:sha2",
        "@crate_index//:tempfile",
        "@crate_index//:tiny_http",
        "@crate_index//:ureq",
    ],
)
