{
 "title": "API Boundary Node Overview",
 "tags": [ "API Boundary Node" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "node_exporter" },
   { "name": "env", "query": "PROD" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API BN Health",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n    up{job=\"ic_boundary\"},\n    \"ic_node\", \"$1\", \"ic_node\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "{{ic_node}}"
    }
   ]
  },
  { "title": "Health Checking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "All Subnets Health Overview",
   "type": "state-timeline",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "count by(subnet_id) (ic_boundary_check_status{job=\"ic_boundary\",api_boundary_node=\"1\"} == 1) / count by(subnet_id) (ic_boundary_check_status{job=\"ic_boundary\",api_boundary_node=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GuestOS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Usage Overall",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(1 - rate(node_cpu_seconds_total{mode='idle',job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}[$__rate_interval])) * 100",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Free Memory % Overall",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg ((node_memory_MemFree_bytes{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"} + node_memory_Cached_bytes{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"} + node_memory_Buffers_bytes{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"} + node_memory_SReclaimable_bytes{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}) / node_memory_MemTotal_bytes{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"} * 100)",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Load Average (5m) Overall",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg (node_load5{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "CPU Usage By API BN",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (ic_node)(1 - rate(node_cpu_seconds_total{mode='idle',job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory % By API BN",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (ic_node)((node_memory_MemFree_bytes{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"} + node_memory_Cached_bytes{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"} + node_memory_Buffers_bytes{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"} + node_memory_SReclaimable_bytes{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}) / node_memory_MemTotal_bytes{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"} * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average (5m) By API BN",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(ic_node) (node_load5{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Requests Per Second By BN",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  ic_node_name,\n  ic_node_id,\n  count() /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND request_type != ''\nGROUP BY\n  t,\n  ic_node_name,\n  ic_node_id\nORDER BY t\n",
     "rawQuery": "SELECT\n  (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n  ic_node_name,\n  ic_node_id,\n  count() /(300000 / 1000)\nFROM\n  default.ic_boundary\nWHERE\n  date >= toDateTime(1718193133) AND date <= toDateTime(1718279533)\n  AND env = 'PROD'\n  AND request_type != ''\nGROUP BY\n  t,\n  ic_node_name,\n  ic_node_id\nORDER BY t",
     "round": "0s",
     "table": "ic_boundary"
    }
   ]
  },
  {
   "title": "Requests Per Second By Status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  status,\n  count() /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND status > 0\nGROUP BY\n  t,\n  status\nORDER BY t\n",
     "rawQuery": "SELECT\n  (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n  status,\n  count() /(300000 / 1000)\nFROM\n  default.ic_boundary\nWHERE\n  date >= toDateTime(1718193178) AND date <= toDateTime(1718279578)\n  AND env = 'PROD'\n  AND status > 0\nGROUP BY\n  t,\n  status\nORDER BY t",
     "round": "0s",
     "table": "ic_boundary"
    }
   ]
  },
  {
   "title": "Requests Per Second By Status Group",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  toInt16(status/100)*100 as status,\n  count() /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND status > 0\nGROUP BY\n  t,\n  status\nORDER BY t\n",
     "rawQuery": "SELECT\n  (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n  toInt16(status/100)*100 as status,\n  count() /(300000 / 1000)\nFROM\n  default.ic_boundary\nWHERE\n  date >= toDateTime(1718193255) AND date <= toDateTime(1718279655)\n  AND env = 'PROD'\n  AND status > 0\nGROUP BY\n  t,\n  status\nORDER BY t",
     "round": "0s",
     "table": "ic_boundary"
    }
   ]
  },
  {
   "title": "Requests Per Second By CacheStatus",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  if(cache_status == '', 'UNKNOWN', cache_status) as cache_status,\n  count() / ($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND status > 0\nGROUP BY\n  t,\n  cache_status\nORDER BY t\n",
     "rawQuery": "SELECT\n  (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n  if(cache_status == '', 'UNKNOWN', cache_status) as cache_status,\n  count() / (300000 / 1000)\nFROM\n  default.ic_boundary\nWHERE\n  date >= toDateTime(1718194028) AND date <= toDateTime(1718280428)\n  AND env = 'PROD'\n  AND status > 0\nGROUP BY\n  t,\n  cache_status\nORDER BY t",
     "round": "0s",
     "table": "ic_boundary"
    }
   ]
  },
  {
   "title": "Requests by Error Cause (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  error_cause,\n  count() /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND error_cause NOT IN ('', 'none')\n  AND status > 0\nGROUP BY\n  t,\n  error_cause\nORDER BY t\n",
     "rawQuery": "/* grafana dashboard=API Boundary Node Overview, user=0 */\nSELECT\n  (intDiv(toUInt32(undefined), 5) * 5) * 1000 as t,\n  error_cause,\n  count() /(5000 / 1000)\nFROM\n  default.ic_boundary\nWHERE\n  undefined >= toDateTime(1738748534) AND undefined <= toDateTime(1738752134)\n  AND env = 'PROD'\n  AND error_cause NOT IN ('', 'none')\n  AND status > 0\nGROUP BY\n  t,\n  error_cause\nORDER BY t",
     "round": "0s",
     "table": "ic_boundary"
    }
   ]
  },
  {
   "title": "Requests Per Second By Subnet",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  subnet_id,\n  count() /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND subnet_id != ''\nGROUP BY\n  t,\n  subnet_id\nORDER BY t\n",
     "rawQuery": "SELECT\n  (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n  subnet_id,\n  count() /(300000 / 1000)\nFROM\n  default.ic_boundary\nWHERE\n  date >= toDateTime(1718193700) AND date <= toDateTime(1718280100)\n  AND env = 'PROD'\n  AND subnet_id != ''\nGROUP BY\n  t,\n  subnet_id\nORDER BY t",
     "round": "0s",
     "table": "ic_boundary"
    }
   ]
  },
  {
   "title": "Requests Per Second By Canister ID (top10 over last 30min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "WITH busy_canisters AS (\n  SELECT\n    canister_id\n  FROM\n    $table\n  WHERE\n    date >= ($__to - ($__to - $__from)/2)/1000 - 900\n    AND date <= ($__to + ($__to - $__from)/2)/1000 + 900\n    AND env = '${env}'\n    AND canister_id != ''\n  GROUP BY\n    canister_id\n  ORDER BY\n    count(*) DESC\n  LIMIT 10\n)\nSELECT\n  $timeSeries as t,\n  canister_id,\n  count(*) /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND canister_id GLOBAL IN (SELECT canister_id FROM busy_canisters)\nGROUP BY\n  t,\n  canister_id\nORDER BY t\n",
     "rawQuery": "WITH busy_canisters AS (\n  SELECT\n    canister_id\n  FROM\n    default.ic_boundary\n  WHERE\n    date >= (1718280103424 - (1718280103424 - 1718193703424)/2)/1000 - 900\n    AND date <= (1718280103424 + (1718280103424 - 1718193703424)/2)/1000 + 900\n    AND env = 'PROD'\n    AND canister_id != ''\n  GROUP BY\n    canister_id\n  ORDER BY\n    count(*) DESC\n  LIMIT 10\n)\nSELECT\n  (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n  canister_id,\n  count(*) /(300000 / 1000)\nFROM\n  default.ic_boundary\nWHERE\n  date >= toDateTime(1718193798) AND date <= toDateTime(1718280198)\n  AND env = 'PROD'\n  AND canister_id GLOBAL IN (SELECT canister_id FROM busy_canisters)\nGROUP BY\n  t,\n  canister_id\nORDER BY t",
     "round": "0s",
     "table": "ic_boundary"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total traffic (In+Out)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "avg by (ic_node)((rate(node_network_receive_bytes_total{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}[$__rate_interval])+rate(node_network_transmit_bytes_total{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}[$__rate_interval]))*8)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total packets (In+Out)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "avg by (ic_node)((rate(node_network_receive_packets_total{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}[$__rate_interval])+rate(node_network_transmit_packets_total{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}[$__rate_interval]))*8)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (ic_node)(node_netstat_Tcp_CurrEstab{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP SynCookies Sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (ic_node)(rate(node_netstat_TcpExt_SyncookiesSent{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP SynCookies Received",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (ic_node)(rate(node_netstat_TcpExt_SyncookiesRecv{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP SynCookies Failed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (ic_node)(rate(node_netstat_TcpExt_SyncookiesFailed{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (ic_node)(rate(node_netstat_TcpExt_TCPTimeouts{job=\"${job}\",ic=\"mercury\",api_boundary_node=\"1\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Versions Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version History",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 17, "x": 0, "y": 163 },
     "targets": [
      {
       "expr": "label_replace(\n    label_replace(\n        (\n            ic_orchestrator_info{ic=\"mercury\", api_boundary_node=\"1\"}),\n        \"ic_node\", \"$1\", \"ic_node\", \"([a-z0-9]+)-.*\"\n    ),\n    \"ic_active_version\", \"$1\", \"ic_active_version\", \"([a-z0-9]{7}).*\"\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Currently Active Versions",
     "type": "table",
     "gridPos": { "h": 13, "w": 7, "x": 17, "y": 163 },
     "targets": [
      {
       "expr": "label_replace(\n    ic_orchestrator_info{ic=\"mercury\", api_boundary_node=\"1\"}, \"ic_node\", \"$1\", \"ic_node\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Rate-Limiting on the API BNs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Rules per API BN",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ic_boundary_generic_limiter_rules{api_boundary_node=\"1\", ic=\"mercury\"}",
       "legendFormat": "{{ic_node}}"
      }
     ]
    },
    {
     "title": "Rate-Limiting Decisions (overall)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 8, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(sum by (decision) (ic_boundary_generic_limiter_decisions{api_boundary_node=\"1\", ic=\"mercury\"})[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fetch Failures",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (ic_node) (rate(\n    label_replace(\n        ic_boundary_generic_limiter_fetches{api_boundary_node=\"1\", ic=\"mercury\", result=\"failure\"}[$__rate_interval],\n        \"ic_node\", \"$1\", \"ic_node\", \"([a-z0-9]+)-.*\"\n    )\n))",
       "legendFormat": "{{ic_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rate-Limiting Canister",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Configuration",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 124 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "active_config_version{ic=\"mercury\", instance=\"u637p-5aaaa-aaaaq-qaaca-cai.raw.ic0.app:443\", job=\"rate-limiting-canister\", owner=\"#eng-boundary-nodes\"}",
       "legendFormat": "Version"
      },
      {
       "expr": "active_rules_count{ic=\"mercury\", instance=\"u637p-5aaaa-aaaaq-qaaca-cai.raw.ic0.app:443\", job=\"rate-limiting-canister\", owner=\"#eng-boundary-nodes\"}",
       "legendFormat": "Rules"
      }
     ]
    },
    {
     "title": "Stable Memory",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 4, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stable_memory_bytes{ic=\"mercury\", instance=\"u637p-5aaaa-aaaaq-qaaca-cai.raw.ic0.app:443\", job=\"rate-limiting-canister\", owner=\"#eng-boundary-nodes\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Registry Poll",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 9, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_successful_registry_poll{ic=\"mercury\", instance=\"u637p-5aaaa-aaaaq-qaaca-cai.raw.ic0.app:443\", job=\"rate-limiting-canister\", owner=\"#eng-boundary-nodes\"}/1000000",
       "legendFormat": "Last Poll"
      }
     ]
    }
   ]
  },
  {
   "title": "Anonymization - Salt Sharing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Salt ID (Canister)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_salt_id{ic=\"mercury\", job=\"salt-sharing-canister\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stable Memory",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 4, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stable_memory_bytes{ic=\"mercury\", instance=\"uz2z3-qyaaa-aaaaq-qaacq-cai.raw.ic0.app:443\", job=\"salt-sharing-canister\", owner=\"#eng-boundary-nodes\"}\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fetch Failures (by API BN)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 7, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (ic_node) (rate(\n    label_replace(\n            ic_boundary_anonymization_salt_fetches{api_boundary_node=\"1\", ic=\"mercury\", status=\"failure\"}[$__rate_interval],\n        \"ic_node\", \"$1\", \"ic_node\", \"([a-z0-9]+)-.*\"\n    )\n))\n",
       "legendFormat": "{{ic_node}}"
      }
     ]
    },
    {
     "title": "Fetch Failures (by failure type)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 15, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (message) (rate(ic_boundary_anonymization_salt_fetches{api_boundary_node=\"1\", ic=\"mercury\", status=\"failure\"}[$__rate_interval]))\n",
       "legendFormat": "{{message}}"
      }
     ]
    },
    {
     "title": "Active Salt ID",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ic_boundary_anonymization_salt_last_salt_id{api_boundary_node=\"1\", ic=\"mercury\"}",
       "legendFormat": "{{ic_node}}"
      }
     ]
    }
   ]
  }
 ]
}