{
 "title": "IC-Gateway",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(ic_gateway_conn_open, env)"
    }
   },
   {
    "name": "hostname",
    "label": "Boundary Name",
    "query": {
     "query": "label_values(ic_gateway_conn_open{env=~\"${env}\"}, ansible_host)"
    }
   },
   { "name": "mov_avg", "query": "30s,1m,2m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/sec per Boundary Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (rate(ic_gateway_http_total{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Requests/sec by Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (status) (rate(ic_gateway_http_total{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Requests Full Duration Percentile=0.9",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (ansible_host, le) (rate(ic_gateway_http_duration_full_sec_bucket{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Requests Duration Percentile=0.9",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (ansible_host, le) (rate(ic_gateway_http_duration_sec_bucket{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Request Size Percentile=0.9",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (ansible_host, le) (rate(ic_gateway_http_request_size_bucket{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Response Size Percentile=0.9",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (ansible_host, le) (rate(ic_gateway_http_response_size_bucket{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "HTTP Request versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (http) (rate(ic_gateway_http_total{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Open Incoming Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_conn_open {ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Connection Duration Percentile=0.9 (by Hostname)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (ansible_host, le) (rate(ic_gateway_conn_duration_sec_bucket{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Requests per connection (pct=0.9)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (ansible_host, le) (rate(ic_gateway_conn_requests_per_conn_bucket{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Outgoing Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by(ansible_host) (rate(ic_gateway_conn_bytes_sent_total{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Incoming Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by(ansible_host) (rate(ic_gateway_conn_bytes_rcvd_total{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "TLS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "TLS sessions per second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (rate(ic_gateway_tls_sessions{ansible_host=~\"$hostname\",env=~\"$env\",action=\"put\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "TLS sessions per second by version",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (tls_version) (rate(ic_gateway_conn_total{ansible_host=~\"$hostname\",env=~\"$env\",tls_version!=\"no\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "TLS sessions per second by cipher",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (tls_cipher) (rate(ic_gateway_conn_total{ansible_host=~\"$hostname\",env=~\"$env\",tls_cipher!=\"no\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "TLS session cache count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_tls_session_cache_count{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "TLS session cache size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_tls_session_cache_size{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "TLS handshake duration Percentile=0.9",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (ansible_host, le) (rate(ic_gateway_conn_tls_handshake_duration_sec_bucket{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "TLS certificates resolve rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (rate(ic_gateway_tls_resolver_total{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "TLS certificate resolving latency Percentile=0.97",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.97, sum by (ansible_host, le) (rate(ic_gateway_tls_resolver_duration_sec_bucket{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "TLSv1.3 Tickets Decrypted per second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (rate(ic_gateway_tls_tickets{ansible_host=~\"$hostname\",env=~\"$env\",action=\"decrypt\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "TLSv1.3 Tickets Encrypted per second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (rate(ic_gateway_tls_tickets{ansible_host=~\"$hostname\",env=~\"$env\",action=\"encrypt\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "TLS supported ciphers (TOP10)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk_avg(10, sum by (cipher) (ic_gateway_tls_resolver_supported_cipher{ansible_host=~\"$hostname\",env=~\"$env\"}))",
       "legendFormat": "{{ cipher }}"
      }
     ]
    },
    {
     "title": "TLS supported signature schemes (TOP10)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk_avg(10, sum by (scheme) (ic_gateway_tls_resolver_supported_scheme{ansible_host=~\"$hostname\",env=~\"$env\",scheme!=\"unknown\"}))",
       "legendFormat": "{{ scheme }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Denylist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Denylist Update Failures",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (rate(ic_gateway_denylist_updates{ansible_host=~\"$hostname\",env=~\"$env\",result=\"fail\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entries In Cache",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by(ansible_host) (ic_gateway_cache_entries{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by(ansible_host) (ic_gateway_cache_memory{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests by Cache Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by(cache_status) (rate(ic_gateway_cache_requests_count{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests by Cache Bypass Reason",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by(cache_bypass_reason) (rate(ic_gateway_cache_requests_count{ansible_host=~\"$hostname\",env=~\"$env\",cache_bypass_reason!=\"none\"}[$mov_avg])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(ic_gateway_memory_allocated{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Resident memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(ic_gateway_memory_resident{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certificates SANs in storage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_cert_storage_count_total{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Certificate issuer packages loaded Ok",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_issuer_packages_loaded{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Certificate issuer packages with errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_issuer_packages_errors{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Certificate Issuer sync latency Percentile=0.9",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (ansible_host, le) (rate(ic_gateway_issuer_fetch_duration_sec_bucket{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Vector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vector data upload rate (raw)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (rate(ic_gateway_vector_sent{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Vector data upload rate (compressed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (rate(ic_gateway_vector_sent_compressed{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Vector event buffer length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_vector_event_buffer_size{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Vector batch size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_vector_batch_size{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Vector batches in the upload queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_vector_batch_buffer_size{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Vector buffer drops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_vector_buffer_drops{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Vector flush retries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (rate(ic_gateway_vector_batch_flush_retries{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "Vector encoding failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (rate(ic_gateway_vector_encoding_failures{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OCSP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "OCSP stapled certificates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(sum by (ansible_host) (ic_gateway_ocsp_certificate_count{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg]))",
       "legendFormat": "{{ansible_host}}"
      }
     ]
    },
    {
     "title": "OCSP stapling latency Percentile=0.9",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (ansible_host, le) (rate(ic_gateway_ocsp_requests_duration_bucket{ansible_host=~\"$hostname\",env=~\"$env\"}[$mov_avg])))",
       "legendFormat": "{{ansible_host}}"
      },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}