{
 "title": "IC HTTP Proxy",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT uniqExact(remote_addr_hashed)\nFROM $table\nWHERE $timeFilter AND env = 'prod'",
     "round": "0s",
     "table": "http_access_ic_http_proxy"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(1)\nFROM $table\nWHERE $timeFilter AND env = 'prod'\n",
     "round": "0s",
     "table": "http_access_ic_http_proxy"
    }
   ]
  },
  {
   "title": "Unique Visitors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, uniqExact(remote_addr_hashed) as visitors\nFROM $table\nWHERE $timeFilter AND env = 'prod'\nGROUP BY t",
     "round": "0s",
     "table": "http_access_ic_http_proxy"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count(1) as requests\nFROM $table\nWHERE $timeFilter AND env = 'prod'\nGROUP BY t",
     "round": "0s",
     "table": "http_access_ic_http_proxy"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT uniqExact(geo_country_code)\nFROM $table\nWHERE $timeFilter and env = 'prod'\n",
     "rawQuery": "SELECT uniqExact(geo_country_code)\nFROM default.http_access_ic_http_proxy\nWHERE date >= toDateTime(1685869277) AND date <= toDateTime(1686042077) and env = 'prod'",
     "round": "0s",
     "table": "http_access_ic_http_proxy"
    }
   ]
  }
 ]
}