load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "upgrade",
    srcs = glob(["src/**/*.rs"]),
    crate_features = select({
        "//conditions:default": [],
    }),
    crate_name = "ic_consensus_upgrade",
    proc_macro_deps = [
        # Keep sorted.
    ],
    version = "0.9.0",
    deps = [
        # Keep sorted.
        "//rs/consensus/utils",
        "//rs/interfaces",
        "//rs/interfaces/state_manager",
        "//rs/monitoring/logger",
        "//rs/replicated_state",
        "//rs/types/types",
        "@crate_index//:num-traits",
        "@crate_index//:slog",
    ],
)

rust_doc(
    name = "consensus_upgrade_doc",
    crate = ":upgrade",
)

rust_test(
    name = "consensus_upgrade_test",
    crate = ":upgrade",
    deps = [
        # Keep sorted.
        "//rs/artifact_pool",
        "//rs/consensus/mocks",
        "//rs/consensus/utils",
        "//rs/interfaces",
        "//rs/interfaces/state_manager",
        "//rs/monitoring/logger",
        "//rs/monitoring/metrics",
        "//rs/protobuf",
        "//rs/registry/fake",
        "//rs/registry/proto_data_provider",
        "//rs/registry/subnet_type",
        "//rs/replicated_state",
        "//rs/test_utilities",
        "//rs/test_utilities/registry",
        "//rs/test_utilities/types",
        "//rs/types/types",
        "@crate_index//:num-traits",
    ],
)

rust_test(
    name = "consensus_upgrade_integration_test",
    srcs = ["tests/integration.rs"],
    deps = [
        # Keep sorted.
        ":upgrade",
        "//rs/artifact_pool",
        "//rs/config",
        "//rs/consensus/mocks",
        "//rs/consensus/utils",
        "//rs/interfaces",
        "//rs/interfaces/registry",
        "//rs/interfaces/state_manager",
        "//rs/monitoring/logger",
        "//rs/monitoring/metrics",
        "//rs/protobuf",
        "//rs/registry/fake",
        "//rs/registry/proto_data_provider",
        "//rs/registry/subnet_type",
        "//rs/replicated_state",
        "//rs/test_utilities",
        "//rs/test_utilities/artifact_pool",
        "//rs/test_utilities/consensus",
        "//rs/test_utilities/registry",
        "//rs/test_utilities/types",
        "//rs/types/types",
    ],
)
