{
 "title": "Backup",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   {
    "name": "ic",
    "query": {
     "query": "up{job=\"replica\"}"
    }
   },
   {
    "name": "ic_subnet",
    "query": {
     "query": "label_values(backup_disk_usage{job=\"backup-pod\",ic=\"$ic\"}, ic_subnet)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "backup pod",
    "query": {
     "query": "label_values(backup_disk_usage{job=\"backup-pod\",ic=\"$ic\"}, instance)"
    }
   },
   {
    "name": "dir",
    "query": {
     "query": "label_values(backup_disk_usage{job=\"backup-pod\",ic=\"$ic\",instance=~\"$instance\"}, dir)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Restored Height",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "backup_last_restored_height{ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{ic_subnet}}"
    },
    {
     "expr": "quantile by (ic, job, ic_subnet) (0.5, artifact_pool_consensus_height_stat{type=\"finalization\",pool_type=\"validated\",stat=\"max\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"})",
     "legendFormat": "Current subnet height {{ic_subnet}}"
    }
   ]
  },
  {
   "title": "Last Synchronized Height",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "backup_last_synced_height{ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{ic_subnet}}"
    },
    {
     "expr": "quantile by (ic, job, ic_subnet) (0.5, artifact_pool_consensus_height_stat{type=\"finalization\",pool_type=\"validated\",stat=\"max\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"})",
     "legendFormat": "Current subnet height {{ic_subnet}}"
    }
   ]
  },
  {
   "title": "Replay Running Time ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "backup_replay_time_minutes{ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{ic_subnet}}"
    }
   ]
  },
  {
   "title": "Space & Inodes Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by(resource, dir, instance) (backup_disk_usage{ic=\"$ic\", dir=~\"$dir\", instance=~\"$instance\"})",
     "legendFormat": "{{resource}}({{dir}})@{{instance}}"
    }
   ]
  },
  {
   "title": "Artifacts Syncing Time ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "backup_sync_minutes{ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{ic_subnet}}"
    }
   ]
  },
  {
   "title": "Version Number",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "backup_version_number{ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{ic_subnet}}"
    }
   ]
  }
 ]
}