{
 "title": "HTTPS Outcalls",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "label": "ic", "query": { "query": "label_values(ic)" } },
   {
    "name": "ic_subnet",
    "label": "subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{ic=\"$ic\",job=\"replica\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   },
   { "name": "period", "label": "Aggregation period", "query": "20s,30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Notes\n\nThe exchange rate canister, which uses this feature is on the system subnet:\n\nuzr34-akd3s-xrdag-3ql62-ocgoh-ld2ao-tamcv-54e7j-krwgb-2gm4z-oqe\n"
   }
  },
  { "title": "Global IC feature metrics ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total cycles used (trillions)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by ($ic) (max by (ic_subnet) (replicated_state_consumed_cycles_from_replica_start{ic=\"$ic\", use_case=\"HTTPOutcalls\"}/1000000000000))",
     "legendFormat": "Cycles [T]"
    }
   ]
  },
  {
   "title": "Total http requests",
   "type": "timeseries",
   "description": "This metric is not persisted across upgrades. So a decrease usually means that a subnet upgraded",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by ($ic) (max by (ic_subnet) (canister_http_success_delivered{job=\"replica\",ic=\"$ic\"}))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by ($ic) (max by (ic_subnet) (canister_http_divergences_delivered{job=\"replica\",ic=\"$ic\"}))",
     "legendFormat": "Diverged"
    },
    {
     "expr": "sum by ($ic) (max by (ic_subnet) (canister_http_timeouts_delivered{job=\"replica\",ic=\"$ic\"}))",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Http requests rate by subnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n    avg by (ic_subnet) (rate(canister_http_success_delivered{job=\"replica\",ic=\"$ic\"}[$period])),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} Success"
    },
    {
     "expr": "label_replace(\n    avg by (ic_subnet) (rate(canister_http_timeouts_delivered{job=\"replica\",ic=\"$ic\"}[$period])),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} Timeout"
    },
    {
     "expr": "label_replace(\n    avg by (ic_subnet) (rate(canister_http_divergences_delivered{job=\"replica\",ic=\"$ic\"}[$period])),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} Diverged"
    }
   ]
  },
  {
   "title": "Total http requests without exchange rate canister",
   "type": "timeseries",
   "description": "This metric is not persisted across upgrades. So a decrease usually means that a subnet upgraded",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by ($ic) (max by (ic_subnet) (canister_http_success_delivered{job=\"replica\", ic=\"$ic\", ic_subnet!=\"uzr34-akd3s-xrdag-3ql62-ocgoh-ld2ao-tamcv-54e7j-krwgb-2gm4z-oqe\"}))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by ($ic) (max by (ic_subnet) (canister_http_divergences_delivered{job=\"replica\",ic=\"$ic\", ic_subnet!=\"uzr34-akd3s-xrdag-3ql62-ocgoh-ld2ao-tamcv-54e7j-krwgb-2gm4z-oqe\"}))",
     "legendFormat": "Diverged"
    },
    {
     "expr": "sum by ($ic) (max by (ic_subnet) (canister_http_timeouts_delivered{job=\"replica\",ic=\"$ic\", ic_subnet!=\"uzr34-akd3s-xrdag-3ql62-ocgoh-ld2ao-tamcv-54e7j-krwgb-2gm4z-oqe\"}))",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Cycle usage in T by subnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n    avg by (ic_subnet) (replicated_state_consumed_cycles_from_replica_start{use_case=\"HTTPOutcalls\"}/1000000000000),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cycle burn rate in T/s by subnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n    avg by (ic_subnet) (rate(replicated_state_consumed_cycles_from_replica_start{ic = \"$ic\", job=\"replica\",use_case=\"HTTPOutcalls\"}[$period])/1000000000000),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Feature metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Total http requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n    max by (ic_subnet) (canister_http_success_delivered{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)\n",
     "legendFormat": "{{ic_subnet}} Success"
    },
    {
     "expr": "label_replace(\n    max by (ic_subnet) (canister_http_timeouts_delivered{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)\n",
     "legendFormat": "{{ic_subnet}} Timeout"
    },
    {
     "expr": "label_replace(\n    max by (ic_subnet) (canister_http_divergences_delivered{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} Diverged"
    }
   ]
  },
  {
   "title": "Http requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "tx/sec" } },
   "targets": [
    {
     "expr": "label_replace(\n    avg by (ic_subnet) (rate(canister_http_success_delivered{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}[$period])),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} Success"
    },
    {
     "expr": "label_replace(\n    avg by (ic_subnet) (rate(canister_http_timeouts_delivered{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}[$period])),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} Timeout"
    },
    {
     "expr": "label_replace(\n    avg by (ic_subnet) (rate(canister_http_divergences_delivered{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}[$period])),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} Diverged"
    }
   ]
  },
  { "title": "Adapter metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Adapter memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "adapter_canisterhttp_process_resident_memory_bytes{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests made by each adapter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adapter_canisterhttp_requests_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Adapter RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(adapter_canisterhttp_requests_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Incoming adapter network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(adapter_canisterhttp_network_traffic_bytes_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",link=\"down\"}[$period])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing adapter network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(adapter_canisterhttp_network_traffic_bytes_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",link=\"up\"}[$period])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total adapter errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "adapter_canisterhttp_request_errors_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}",
     "legendFormat": "{{cause}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Adapter error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(adapter_canisterhttp_request_errors_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])",
     "legendFormat": "{{cause}}/{{instance}}"
    }
   ]
  },
  { "title": "Adapter Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Inflight Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canister_http_in_client_requests{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Duration Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(canister_http_external_http_request_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])) by (le)) ",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(canister_http_external_http_request_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])) by (le)) ",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(canister_http_external_http_request_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])) by (le)) ",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Rate by Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "tx/sec" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(canister_http_external_http_request_duration_seconds_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Transform Duration Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(canister_http_transform_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])) by (le)) \n",
     "legendFormat": "p90"
    },
    {
     "expr": "\nhistogram_quantile(0.5, sum(rate(canister_http_transform_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])) by (le)) \n",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(canister_http_transform_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])) by (le)) \n",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}