= SetupOS and HostOS Config Store

The SetupOS and HostOS config stores are largely the same. All the SetupOS configuration files listed below are sanitized and copied to the HostOS config partition.

== SetupOS configuration files

The SetupOS configuration files are all the files relevant to controlling the IC-OS installation.

=== Config partition

After burning the SetupOS disk image onto a USB drive, the config partition will be available. It can be mounted on any operating system that supports FAT file systems.

The `config` partition contains the following configuration files:

  config.ini                      # Data center-specific network settings
  ssh_authorized_keys             # SSH private key for obtaining HostOS console access
  node_operator_private_key.pem   # (OPTIONAL) Node Operator private key used in the pseudo-HSM onboarding

==== config.ini

The `config.ini` file contains all network-related settings, which must be provided by the Node Technician before running the deployment.

The configuration file expects the following key-value pairs in lower-case format. For example:

  ipv6_prefix=2a00:fb01:400:100
  ipv6_gateway=2a00:fb01:400:100::1

[NOTE]
Customize the above example values for your own network. This information will be available from your ISP.

==== ssh_authorized_keys

Node Technicians can add a private key to the admin file in `ssh_authorized_keys/` in order to gain SSH access to the HostOS.

Note that ssh access is still contingent on the configuration of the firewalls.

[NOTE]
HostOS SSH access does not grant Node Technicians access to the GuestOS or any of its underlying data.

==== node_operator_private_key.pem

This file is necessary for the pseudo-HSM onboarding process. To use the pseudo-HSM onboarding process, a Node Technician must create this file on the SetupOS config partition, containing the Node Operator private key. If they don't create this file on the SetupOS config partition, they must use the traditional HSM onboarding process.

=== Other SetupOS configuration files

There are other configuration files that do not exist in the config partition. These files are not intended to be modified by Node Technicians and are kept separate to avoid cluttering the config partition. They should be modified only for testing and development purposes.

These files include:

  deployment.json     # Deployment-specific configurations
  nns_public_key.pem  # NNS public key

==== deployment.json

The default settings can be found in the `data/deployment.json.template` file.

==== nns_public_key.pem

The `nns_public_key.pem` file contains the public key of the NNS. For mainnet, it is:

  -----BEGIN PUBLIC KEY-----
  MIGCMB0GDSsGAQQBgtx8BQMBAgEGDCsGAQQBgtx8BQMCAQNhAIFMDm7HH6tYOwi9
  gTc8JVw8NxsuhIY8mKTx4It0I10U+12cDNVG2WhfkToMCyzFNBWDv0tDkuRn25bW
  W5u0y3FxEvhHLg1aTRRQX/10hLASkQkcX4e5iINGP5gJGguqrg==
  -----END PUBLIC KEY-----
