= Configuration

Each IC-OS has a 100 MB config partition. All IC-OS config partitions are initialized to be empty, except for SetupOS.

In production, configuration is propagated from a partition on the USB installer through each of SetupOS, HostOS and GuestOS.
This process is controlled by the (link:../../rs/ic_os/config/README.md[ic-os config tool]) and an assortment of bash scripts.

All access to the config partition should be done through the ic-os config tool.

== User-facing configuration files

SetupOS constructs its config struct from the following user-facing configuration files:
  config.ini                      # Data center-specific network settings
  ssh_authorized_keys             # SSH private keys
  node_operator_private_key.pem   # Node Operator private key created in the Node Provider onboarding
  deployment.json                 # Deployment-specific configurations
  nns_public_key.pem              # NNS public key

Refer to link:../../rs/ic_os/config/README.md[rs/ic_os/config] and link:../components/setupos-scripts/setup-hostos-config.sh[setup-hostos-config.sh] for more details.

== HostOS -> GuestOS

TODO: update...

HostOS builds the "bootstrap config image". Refer to link:../components/hostos-scripts/build-bootstrap-config-image.sh[build-bootstrap-config-image.sh]

The bootstrap config image contains a tar file with the GuestOS configuration files.
When the HostOS launches the GuestOS, the bootstrap config image is attached to the GuestOS as a virtual USB. Refer to link:../components/hostos-scripts/guestos/guestos.xml.template[guestos.xml.template]

When the GuestOS boots, it checks for available removable media devices (i.e. the bootstrap config image). If such a device is found, the media must contain a VFAT filesystem and a single file called `ic-bootstrap.tar`.

GuestOS then reads from `ic-bootstrap.tar` (link:../components/init/bootstrap-ic-node[see bootstrap-ic-node]), and the contents are unpacked and distributed in one of two places:

* *System state:* Node initialization material (initial registry & keys) is copied directly into target directories for replica use.
* *Config partition:* All other contents of the injected config are copied into the `/boot/config` directory. These configurations need to be available on subsequent boots (not just the first boot of the system), and need to be preserved across upgrades.
** The contents of `/boot/config` are then used in various ways to parameterize system services as they start. For example, ssh keys are installed to target accounts, network settings are applied by network set-up scripts, etc.
** `generate-replica-config.sh` uses `ic.json5.template` to produce the replica configuration (also cf. service file definition). Template placeholders are populated with information from `/boot/config`.

[NOTE]
GuestOS only reads a predefined set of files from the bootstrap config image (i.e., it "sanitizes" the bootstrap config image).

[NOTE]
The reason for the bootstrap config image redirection is to ensure that GuestOS maintains control over what goes onto its config partition. Theoretically, a malicious Node Technician could modify their HostOS image and place any file onto the bootstrap config image. However, GuestOS will only copy a predefined set of files to its config partition.

== GuestOS config partition

TODO: update...

The config partition stores information that must be preserved across system upgrades and needs to be available during early boot time. Consequently, this information cannot reside within the encrypted payload data partition.

Currently, all contents in the config partition are stored as plain-text without integrity protection.

These files are stored in `/boot/config` or `/var/lib/ic`. To see where each configuration file is stored, refer to link:../../components/init/bootstrap-ic-node/guestos/bootstrap-ic-node.sh[bootstrap-ic-node]

=== CONFIGURED file

This file serves as a tag to indicate that the one-time bootstrap configuration has been completed. If the `/boot/config/CONFIGURED` file is not present, the boot sequence will search for a virtual USB stick (the bootstrap config image) containing the injected configuration files, and create the file.

=== store.keyfile

This file contains the key material used to derive the wrapping key for all block device encryption. The `store.keyfile` is created during the first boot, and encrypted partitions are configured with it.

In the absence of a sealing key (which will be available in SEV-protected trusted execution environments), the `store.keyfile` is stored as plain-text. Once a sealing key becomes available, it should be used to wrap the contents of this file.

== Implementation notes

=== Guidance for adding configuration bits

TODO: update...

To add a new configuration file/directory:

1. Add handling to `build-bootstrap-config-image.sh` to include the new file/directory in the bootstrap config image.

2. Add handling to `bootstrap-ic-node.sh` for the new file/directory.

3. Add interpretation of configuration file/directory to suitable place, e.g. generate-replica-config.sh

4. Adapt testnet and/or prod deployment config as needed
** E.g. for testnets, you may need to update link:../../testnet/tools/icos_deploy.sh[icos_deploy.sh]. If you are adding a production deployment config file, you may need to add a file to the SetupOS config partition to be piped through to HostOS.

*Values and defaults*: Please ensure that the system is operational even in the absence of specific configuration bits, and fall back to sane production defaults. Already deployed nodes will by definition lack new configuration variables and need to behave properly. And defaults unsuitable for tests need to be overridden in tests (not the other way around).

*Format*: The configuration files are "free-form". In principle, any format will work. But please use simple formats (e.g. files containing key=value pair lines). Parsing is done inside shell scripts and safely parsing "fancy" formats may be tricky.
Consider that values may be controlled by an attacker on boot. Bootstrapping a node with bogus values can cause the node to malfunction. Our security goal is to disallow an Node Technician to gain control over the node via code injection or similar.

*Configuration files*: New configuration bits might be added to either existing configuration files that have a suitable structure (e.g. key=value pairs), or new files. If in doubt, opt for adding additional configuration files.

*Interpretation of configuration bits*: Any script or service in the system may pull configuration bits out of /boot/config to customize its behavior. E.g. if adding parameter-driven customization of ic.json5, then augment the generate-replica-config.sh script to pull the configuration values and substitute them into the generated configuration.

=== Testing

TODO: update...

* *bootstrap-ic-node.sh* can be temporarily tweaked (internally adapt paths, then run the process_bootstrap function):
** run stand-alone
** verify that the config image is unpacked
** verify its files are in the correct locations

* *bootstrap-ic-node.sh* can be temporarily tweaked (internally adapt paths; basically just running the process_bootstrap function of it) to run stand-alone and verify that the config image is unpacked and its files sorted into the correct locations.

* *generate-replica-config.sh* can be run stand-alone to verify that it produces the intended ic.json5 configuration from the template.

After all is done, it is advised to prepare a configuration for a single node and boot it in a VM before conducting testnet deployments.

=== Injecting external state

TODO: update...

*Typical bootstrap process:* On first boot, the system will perform technical initialization (filesystems, etc.) and afterwards, initialize itself to act as a node in the IC. The node is initialized using key generation on the node itself (such that the private key never leaves the node) and through joining the IC (the node gets the rest of its state via joining the IC). "Registration" to the target IC is initiated by the node itself by sending a Node Operator-signed "join" request to its NNS. 

However, the typical bootstrap process can be modified such that the node is initialized using externally generated private keys and an externally generated initial state. All "registration" to the target IC is assumed to have been performed by other means.

The behavior is triggered through the presence of the following files:

- ic_crypto
- ic_registry_local_store

This behavior is suitable for the following use cases:

- Bootstrapping an IC instance: In this case, suitable state for all nodes is generated by ic-prep and then distributed across multiple nodes. This is used, for example, during testnet setup.

- Externally controlled join of a node to a subnet: In this case, ic-prep is used to prepare key material to the node, while ic-admin is used to modify the target NNS such that it "accepts" the new node as part of the IC.
