= SEV SNP Validation

This doc explains how to validate a Host machine for SEV-SNP. Steps explain how to setup a SEV-SNP enabled host and prepare an Ubuntu image to be launched as SEV-SNP guest.

== Prepare Host
* In the BIOS, these settings are required to be set. Please consult https://wiki.internetcomputer.org/wiki/IC_OS_Installation_Runbook#6._UEFI_Setup_and_Boot_Menu[NP wikis] for the particular vendor:
```
SMEE = [Enable]
SEV ASID space limit Control = Manual
SEV-ES ASID space limit = 100
SNP Memory Coverage = [Enabled]
SEV-SNP = [Enabled]
```
* Download the https://github.com/dfinity/AMDSEV/releases[latest snp release] tar file from the DFINITY Github and untar it:
```
$ wget https://github.com/dfinity/AMDSEV/releases/download/snp-release-<date>/snp-release-<date>.tar.gz
$ tar xvf snp-release-<date>.tar.gz
```

* Install the linux kernel by running the install script in the release directory
```
$ cd snp-release-<date>
$ sudo ./install.sh
```
* Reboot the machine and (if needed) choose the SNP host kernel from the grub menu
* Run the following commands to verify that the SNP is enabled on the host
```
$ uname -r
5.17.0-rc6-snp-guest-dfa5ba8348e4

$ sudo dmesg | grep  -i -e sev -e ccp -e rmp
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.14.0-rc2-snp-host-6d4469b86f90 root=/dev/mapper/vgroot-lvroot ro mem_encrypt=on kvm_amd.sev=1 amd_iommu=on
[    0.520036] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.14.0-rc2-snp-host-6d4469b86f90 root=/dev/mapper/vgroot-lvroot ro mem_encrypt=on kvm_amd.sev=1 amd_iommu=on
[    1.768903] SEV-SNP: RMP table physical address 0x0000007fef500000 - 0x000000806fcfffff
[    2.767472] [Hardware Error]: event severity: fatal
[    8.328990] ccp 0000:22:00.1: enabling device (0000 -> 0002)
[    8.330886] ccp 0000:22:00.1: no command queues available
[    8.331699] ccp 0000:22:00.1: sev enabled
[    8.331702] ccp 0000:22:00.1: psp enabled
[    8.331973] ccp 0000:a6:00.1: enabling device (0000 -> 0002)
[    8.333711] ccp 0000:a6:00.1: no command queues available
[    8.382289] ccp 0000:22:00.1: SEV firmware update successful
[   17.253755] ccp 0000:22:00.1: SEV-SNP API:1.51 build:3
[   17.267208] SEV supported: 410 ASIDs
[   17.267209] SEV-ES and SEV-SNP supported: 99 ASIDs

$ cat /sys/module/kvm_amd/parameters/sev
Y

$ cat /sys/module/kvm_amd/parameters/sev_es
Y

$ cat /sys/module/kvm_amd/parameters/sev_snp
Y
```
== Prepare Guest
* Install these utils
```
$ sudo apt install libvirt-daemon-system virtinst qemu-utils cloud-image-utils
```
* Get an ubuntu image
```
$ wget https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
```
* Create QCOW2 image
```
$ sudo qemu-img create -b focal-server-cloudimg-amd64.img -f qcow2 -F qcow2 sev-guest.qcow2 100G
```
* Create a cloud-init config file that sets a default password
```
$ cat >cloud-config <<EOF
#cloud-config
password: password
chpasswd: { expire: False }
ssh_pwauth: False
EOF

$ sudo cloud-localds user-data.img cloud-config
```
* Launch a (non-SNP) guest VM
```
sudo ./launch-qemu.sh -hda sev-guest.qcow2 -config user-data.img
```
** Login with password specified in cloud-config (for this example “ubuntu/password”
** To exit VM use `Ctrl-]`

* Download the https://github.com/dfinity/AMDSEV/releases[latest Guest kernel] from the DFINITY Github and install it:
```
wget https://github.com/dfinity/AMDSEV/releases/download/snp-release-2023-05-24/linux-image-6.1.0-rc4-snp-guest-93fa8c5918a4_6.1.0-rc4-snp-guest-93fa8c5918a4-1_amd64.deb

sudo dpkg -i linux-image-6.1.0-rc4-snp-guest-93fa8c5918a4_6.1.0-rc4-snp-guest-93fa8c5918a4-1_amd64.deb
```
* Shutdown the VM
* Launch the SNP guest VM
```
sudo ./launch_qemu.sh -hda sev-guest.qcow2 -sev-snp
```
* Verify that SNP is enabled on the VM
```
$ dmesg | grep -i snp
AMD Memory Encryption Features active: SEV SEV-ES SEV-SNP
```
