#!/bin/bash

# This generator normally scans gpt partition table in order to auto-mount
# filesystems based on partition labels. It does not perform anything useful
# in our case, so simply disable it. (Otherwise, needs security policy to
# allow it to do a number of things to avoid failure messages).
