= IC guest OS SELinux policy

Access control in the IC guest OS is governed by the SELinux
mandatory access control framework. The basis for the policy
used is the _reference policy_ as shipped with the Ubuntu
distribution.

The purpose of the policy is to:

* confine system services (to guard against bugs and escalation attacks)

* confine 3rd party code (e.g. journalbeat)

* enforce sandboxing restrictions an WebAssembly execution (work in progress)

* enforce isolation of crypto service provider and its secret keys (work in progress)

This document describes how the policy is built, customized
and applied to the system as well as ways to diagnose and
develop the policy.

== Filesystem labeling

The root filesystem is set up in such a way that it contains correctly
computed labels at boot time already (since root filesystem will
turn read only, this is actually a necessity). To accomplish this,
the +make_ext4fs+ tool is used to build the filesystem with
labels derived from +/etc/selinux/default/contexts/files/file_contexts+
as per security policy for the system.

For the other partitions and filesystems used, their labeling is
managed dynamically at runtime:

* the +/var+ partition is created together with the first boot
  of the system and is wiped on upgrades. It is labeled once
  initially on creation

* +/boot/grub+, +/boot/efi+ are labeled as per their filesystem type (vfat);
  this is then accounted for in the policy

* persistent data stores are labeled per file using +restorecon+
  on every boot -- except for the +backup+ partition where the
  context for its entire contents is set at mount time

== Policy modules

Several policy modules are defined in +rootfs/prep+. These are built
and then merged with the reference policy on the target system.
Further policy modules required for operation can be put here.

The purpose of the existing policy modules is described here.

=== +systemd-fixes+ and +misc-fixes+

The reference policy shipped with Ubuntu is slightly out of sync
with the software versions contained in the distribution, particularly
+systemd+. This fixes a few policy oversights that are due to this
mismatch.

=== +fscontext-fixes+

Fixes for file contexts due to use of different toolset (+make_ext4fs+
instead of +restorecon + mkfs.ext4+) and due to booting a pre-labeling
filesystem before first boot.

=== +setup-var+

The +/var+ filesystem is set up at boot, using an existing +/var+
filesystem tree contained in the root filesystem as "template".
This makes it necessary for the fs creation utility to read all
labels contained in this template directory.

=== +journalbeat+

Policy to confine the +journalbeat+ service.

=== +ic-node+

Policy for the components of the IC software stack. The division is to be kept
roughly as follows:

* orchestrator has sufficient authority to install system upgrades (replica itself does not)

* orchestrator has sufficient authority to launch replica

* all feedback interaction from replica to orchestrator is limited to the state file store

== Policy development and debugging

It is recommended to either run the system entirely in permissive mode,
or at least run the domains under development in permissive mode during
early development phase.

To detect policy violations, issue as root on the target system:
----
journalctl -af _TRANSPORT=audit
----

and adapt policy accordingly.

As a first-order approximation, suitable policy can be generated by:
----
audit2allow -p /etc/selinux/default/policy/policy.32 <avc-messages.txt
----

or

----
audit2allow -R -p /etc/selinux/default/policy/policy.32 <avc-messages.txt
----

with support for reference policy macros.
