= IC guest OS SELinux support

Access control in the IC guest OS is governed by the SELinux
mandatory access control framework. The basis for the policy
used is the _reference policy_ as shipped with the Ubuntu
distribution.

The purpose of the policy is to:

* confine system services (to guard against bugs and escalation attacks)

* confine 3rd party code

* enforce sandboxing restrictions on WebAssembly execution

* enforce relative isolation of various IC software stack pieces (e.g. crypto service provider)

This document provides a high-level overview and describes
some operational aspects. More details to specific aspects is provided
in documents linked.

== SELinux build integration

The security policy is constructed at build time and
integrated into the built system images. This comes
in two pieces:

* the filesystem(s) are built with security labels attached to every file

* the built runtime policy is set up to be loaded at system boot

Technically, the policy consists of a baseline policy as well
as various policy modules that are linked together at build time
to form the effective policy. Some of the modules are provided from
upstream, some of the modules are built from the IC source tree.

Both aspects of the build process are described in more detail
in the link:SELinux-Build{outfilesuffix}[SELinux build process] page.

== SELinux policy structure

In the implementation, the security policy consists of:

* the baseline _reference policy_ (maintained by upstream SELinux project, and partially Debian/Ubuntu)

* local fixes / adaptations to the reference policy

* policies for our own software stack as well as third party software we install

The policy structures the system partitioning it into various different
security domains. The individual domains and security goals that
are accomplished through the structure is explained in the
link:SELinux-Policy{outfilesuffix}[SELinux policy] page.

== SELinux operation notes

=== Policy enforcement

The security policy as a whole can be run in two different modes:

* _permissive_: operations forbidden by policy are only logged, but allowed anyways

* _enforcing_: operations forbidden by policy are stopped and logged (calling process gets EPERM)

The mode is controlled at boot time and built into the image. The recommended
approach for development is to have the system running in _permissive_ mode
to observe policy/reality mismatches and be able to fix them.

Additionally, it is also possible to declare individual domains as
permissive. In this case, processes running under any of the permissive
domains behave in the same way as described above (operations only logged,
but not stopped) while all processes in all other domains are subject to
full enforcement. This allows to run a "partially completed" policy in
production while continuing refinement / development on some parts.

=== Audit messages

Policy violations generally result in the generation of audit messages
(see also above regarding enforcement). The messages are of the following
form:

----
Aug 20 11:15:07 unnamed audit[778]: AVC avc:  denied  { getattr } for  pid=778 comm="systemd-detect-" path="/proc/cmdline" dev="proc" ino=4026532019 scontext=system_u:system_r:systemd_detect_virt_t:s0 tcontext=system_u:object_r:proc_t:s0 tclass=file permissive=1
----

The most important bits relevant for interpretation are:

* +pid=...+ and +comm=...+: the acting process (but note that a process can alter its own argv[0] so it may not reflect what was launched)

* +tclass=file+ and +{ getattr }+: the operation that was attempted (a getattr-like syscall such as "stat" on a regular file object)

* +path=...+: (not always given) additional data to help identifying the target object

* +scontext=...:systemd_detect_virt_t:...+: the label of the acting source process, of particular interest is the _type_ component (as this is what is modelled primarily in the policy)

* +tcontext=...:proc_t:...+: the label of the target object affected

Only the first policy violation of a certain "kind" will be logged
(in order to prevent log spam). Here, "kind" refers to the
(source label, target label, operation) triple. In particular, if
a process repeatedly attempts a forbidden access to files of a
certain label, only the first violation will be logged while all
other files carrying the certain label will remain silent. Similarly,
if two processes running in the same domain perform the same
kind of forbidden access, only the first instance will be reported
while the second remains silent.

=== Online log inspection

All audit messages can be inspected on the target system (assuming sufficient
privileges):

----
journalctl -af _TRANSPORT=audit
----

This allows to inspect the messages that are held in the logs of
the system and is most suitable for interactive debugging / development
of policy relating to a change. Obviously, it will only show something
if the corresponding "action" has occurred on the system under test,
so it only makes sense in a development process where the behavior
of the system in question can be triggered interactively.

=== Offline log analysis

There presently exists a pipeline that scrapes all logs from the
aggregator. It extracts audit messages describing security policy
violations and aggregates them. The pipeline is contained in this
repository:

https://gitlab.com/dfinity-lab/teams/node-team/gitlab-selinux-logitlab-selinux-logs-processorgs-processor

This is regularly aggregated into a tracking document where addressing
of individual issues is coordinated from:

https://docs.google.com/spreadsheets/d/1frRmZtolOkOi4sf51rFPSyf7U2KnCMunOh6CB8uyJwA/edit#gid=859667600


Presently there is the log analysis pipeline

=== Automatic rule generation

From a given set of policy violations, it is possible to automatically
generate rules allowing all described actions. As a first-order approximation,
suitable policy can be generated by:

----
audit2allow -p /etc/selinux/default/policy/policy.32 <avc-messages.txt
----

or

----
audit2allow -R -p /etc/selinux/default/policy/policy.32 <avc-messages.txt
----

with support for reference policy macros.

This however needs to be combined with an understanding of what the
operations "mean". Particularly, it is sometimes indicated to
restructure / reconfigure the system instead to prevent the affected
action from taking place. Another suitable approach is to deny
an "inconsequential" action but suppress log generation.
