{
 "title": "ckETH Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "deployment", "label": "Deployment", "query": "mainnet,sepolia,staging" },
   {
    "name": "token",
    "label": "Token",
    "query": {
     "query": "label_values(ledger_cycle_balance{job=~\"ck[a-z]+-$deployment-ledger\"}, token)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Canister Cycles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TC" } },
   "targets": [
    {
     "expr": "cycle_balance{canister=\"cketh-minter\", job=\"cketh-$deployment-minter\"} / 1e12",
     "legendFormat": "minter"
    },
    {
     "expr": "cycle_balance{canister=\"ledger-suite-orchestrator\", job=\"cketh-$deployment-orchestrator\"} / 1e12",
     "legendFormat": "orchestrator"
    },
    {
     "expr": "cycle_balance{canister=\"icrc1-ledger\", token=~\"$token\"} / 1e12",
     "legendFormat": "ledger ({{token}})"
    },
    {
     "expr": "cycle_balance{canister=\"icrc1-index\", token=~\"$token\"} / 1e12",
     "legendFormat": "index ({{token}})"
    },
    {
     "expr": "cycle_balance{canister=\"icrc1-archive\", token=~\"$token\"}/1e12",
     "legendFormat": "archive ({{token}})"
    }
   ]
  },
  {
   "title": "Cycle Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "BC/h" } },
   "targets": [
    {
     "expr": "-delta(cycle_balance{canister=\"cketh-minter\", job = \"cketh-$deployment-minter\"}[1h])/1e9",
     "legendFormat": "minter"
    },
    {
     "expr": "-delta(cycle_balance{canister=\"ledger-suite-orchestrator\", job = \"cketh-$deployment-orchestrator\"}[1h])/1e9",
     "legendFormat": "orchestrator"
    },
    {
     "expr": "-delta(cycle_balance{canister=\"icrc1-ledger\", token=~\"$token\"}[1h])/1e9",
     "legendFormat": "ledger ({{token}})"
    },
    {
     "expr": "-delta(cycle_balance{canister=\"icrc1-index\", token=~\"$token\"}[1h])/1e9",
     "legendFormat": "index ({{token}})"
    },
    {
     "expr": "-delta(cycle_balance{canister=\"icrc1-archive\", token=~\"$token\"}[1h])/1e9",
     "legendFormat": "archive ({{token}})"
    }
   ]
  },
  {
   "title": "Heap Memory (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cketh_minter_heap_memory_bytes{job=\"cketh-$deployment-minter\"} or heap_memory_bytes{job=\"cketh-$deployment-minter\"}",
     "legendFormat": "minter"
    },
    {
     "expr": "ledger_suite_orchestrator_heap_memory_bytes{job=\"cketh-$deployment-orchestrator\"} or heap_memory_bytes{job=\"cketh-$deployment-orchestrator\"}",
     "legendFormat": "orchestrator"
    },
    {
     "expr": "ledger_total_memory_bytes{token=~\"$token\"} or heap_memory_bytes{token=~\"${token}\", job=~\".*-ledger\"}",
     "legendFormat": "ledger ({{token}})"
    },
    {
     "expr": "index_total_memory_bytes{token=~\"$token\"} or heap_memory_bytes{token=~\"${token}\", job=~\".*-index\"}",
     "legendFormat": "index ({{token}})"
    },
    {
     "expr": "archive_total_memory_bytes{token=~\"$token\"} or heap_memory_bytes{token=~\"${token}\", job=~\".*-archive\"}",
     "legendFormat": "archive ({{token}})"
    }
   ]
  },
  {
   "title": "Stable Memory (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cketh_minter_stable_memory_bytes{job=\"cketh-$deployment-minter\"} or stable_memory_bytes{job=\"cketh-$deployment-minter\"}",
     "legendFormat": "minter"
    },
    {
     "expr": "ledger_suite_orchestrator_stable_memory_bytes{job=\"cketh-$deployment-orchestrator\"} or stable_memory_bytes{job=\"cketh-$deployment-orchestrator\"}",
     "legendFormat": "orchestrator"
    },
    {
     "expr": "ledger_stable_memory_bytes{token=~\"$token\"} or stable_memory_bytes{token=~\"${token}\", job=~\".*-ledger\"}",
     "legendFormat": "ledger ({{token}})"
    },
    {
     "expr": "index_stable_memory_bytes{token=~\"$token\"} or stable_memory_bytes{token=~\"${token}\", job=~\".*-index\"}",
     "legendFormat": "index ({{token}})"
    },
    {
     "expr": "archive_stable_memory_bytes{token=~\"$token\"} or stable_memory_bytes{token=~\"${token}\", job=~\".*-archive\"}",
     "legendFormat": "archive ({{token}})"
    }
   ]
  },
  {
   "title": "ETH Block Sync",
   "type": "timeseries",
   "description": "Ethereum block synchronization.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "cketh_minter_last_observed_block{job = \"cketh-$deployment-minter\"}",
     "legendFormat": "last_finalized"
    },
    {
     "expr": "cketh_minter_last_processed_block{job = \"cketh-$deployment-minter\"}",
     "legendFormat": "last_scraped (ckETH)"
    },
    {
     "expr": "ckerc20_minter_last_processed_block{job = \"cketh-$deployment-minter\"}",
     "legendFormat": "last_scraped (ckERC20)"
    }
   ]
  },
  {
   "title": "Minter Upgrade Cost (Instructions)",
   "type": "timeseries",
   "description": "The approximate number of instructions required to upgrade the minter (in Billions of Instructions).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cketh_event_count{job = \"cketh-$deployment-minter\"} * 40000",
     "legendFormat": "upgrade cost"
    }
   ]
  },
  {
   "title": "ETH deposits by status",
   "type": "timeseries",
   "description": "The number of ETH deposits by status.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "cketh_minter_accepted_deposits{job = \"cketh-$deployment-minter\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "ETH RPC Call Retries p95",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cketh_eth_rpc_call_retry_count_bucket{job=\"cketh-$deployment-minter\"}[$__rate_interval])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oldest Incomplete Withdrawal Age and Last Max Fee per Gas",
   "type": "timeseries",
   "description": "The age of the oldest incomplete withdrawal request in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cketh_oldest_incomplete_eth_withdrawal_request_age_seconds{job = \"cketh-$deployment-minter\"}",
     "legendFormat": "oldest withdrawal age (s)"
    },
    {
     "expr": "cketh_minter_last_max_fee_per_gas{job = \"cketh-$deployment-minter\"} / 1e9",
     "legendFormat": "Last max fee per gas (gwei)"
    }
   ]
  },
  {
   "title": "Orchestrator tasks duration [s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(orchestrator_tasks_duration_seconds_sum{job =~ \"cketh-$deployment-orchestrator\"}[$__interval])) by (task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Minter balance (base unit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cketh_minter_eth_balance{job=\"cketh-$deployment-minter\"}",
     "legendFormat": "minter balance (ETH)"
    },
    {
     "expr": "cketh_minter_erc20_balances{job=\"cketh-$deployment-minter\", erc20_token=~\"$token\"}",
     "legendFormat": "minter balance ({{erc20_token}})"
    },
    {
     "expr": "ledger_total_supply{token=~\"$token\"}",
     "legendFormat": "token supply ({{token}})"
    }
   ]
  },
  {
   "title": "Orchestrator Managed Canisters and Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "ledger_suite_orchestrator_managed_ledgers{job=~\"cketh-$deployment-orchestrator\"}",
     "legendFormat": "Ledgers ($deployment)"
    },
    {
     "expr": "ledger_suite_orchestrator_managed_indexes{job=~\"cketh-$deployment-orchestrator\"}",
     "legendFormat": "Indexes ($deployment)"
    },
    {
     "expr": "ledger_suite_orchestrator_managed_archives{job=~\"cketh-$deployment-orchestrator\"}",
     "legendFormat": "Archives ($deployment)"
    },
    {
     "expr": "ledger_suite_orchestrator_tasks{job=~\"cketh-$deployment-orchestrator\"}",
     "legendFormat": "Pending tasks ($deployment)"
    }
   ]
  },
  {
   "title": "Minter Transaction Fees (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cketh_minter_total_effective_tx_fees{job=\"cketh-$deployment-minter\"} / 1e18",
     "legendFormat": "Effective"
    },
    {
     "expr": "cketh_minter_total_unspent_tx_fees{job=\"cketh-$deployment-minter\"} / 1e18",
     "legendFormat": "Unspent"
    }
   ]
  },
  {
   "title": "Ledger Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ledger_archived_transactions{token =~ \"$token\"} + ledger_transactions{token =~ \"$token\"}",
     "legendFormat": "ledger ({{token}})"
    },
    {
     "expr": "index_number_of_blocks{token =~ \"$token\"}",
     "legendFormat": "index ({{token}})"
    }
   ]
  }
 ]
}