{
 "title": "Exchange Rate Canister",
 "tags": [
  "production",
  "ic integrations"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Canister Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Outgoing HTTP Calls",
   "type": "timeseries",
   "description": "The internal counter for outgoing HTTP calls made to crypto exchanges.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "xrc_http_outcall_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Types",
   "type": "timeseries",
   "description": "Various classes of errors seen",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(xrc_cycles_related_errors[1m])",
     "legendFormat": "Cycles Related Errors"
    },
    {
     "expr": "increase(xrc_crypto_asset_errors[1m])",
     "legendFormat": "Crypto Asset Errors"
    },
    {
     "expr": "increase(xrc_forex_asset_errors[1m])",
     "legendFormat": "Forex Asset Errors"
    },
    {
     "expr": "increase(xrc_inconsistent_rate_errors[1m])",
     "legendFormat": "Inconsistent Rate Errors"
    },
    {
     "expr": "increase(xrc_rate_limited_errors[1m])",
     "legendFormat": "Rate Limited Errors"
    },
    {
     "expr": "increase(xrc_stablecoin_errors[1m])",
     "legendFormat": "Stablecoin Errors"
    }
   ]
  },
  {
   "title": "# of entries in cache",
   "type": "timeseries",
   "description": "Current number of entries in the crypto exchange cache. Max is at 1000. If higher, there is an issue with the canister.",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 11 },
   "targets": [
    { "expr": "xrc_cache_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Forex Store in MiB",
   "type": "gauge",
   "description": "How much space the forex data is utilizing",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "xrc_forex_store_size_bytes / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Errors Per Minute",
   "type": "timeseries",
   "description": "Pending error is returned when there is an already active request.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "increase(xrc_pending_errors[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Privileged Canisters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Privileged Canister Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    { "expr": "increase(xrc_cmc_requests[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Privileged Canister Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "increase(xrc_cmc_errors_returned[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Non-Privileged Canisters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Non-Privileged Canister Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    { "expr": "increase(xrc_requests[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Non-Privileged Canister Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "increase(xrc_errors_returned[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}