{
 "title": "Execution Metrics",
 "tags": [ "production" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "query": { "query": "label_values(up,ic)" } },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   },
   {
    "name": "node_instance",
    "label": "Node Instance",
    "query": {
     "query": "label_values(up{job=~\"node_exporter(-tls)?\",ic=\"$ic\",instance=~\"(${instance_host}):[0-9]+\"}, instance)"
    }
   },
   {
    "name": "heatmap_period",
    "label": "Heatmap aggregation period",
    "query": "20s,30s,1m,2m,5m,10m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Execution Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Finalization rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "label_replace (\n  quantile by (ic_subnet) (\n    0.5,\n    rate((artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"} != 0)[$__rate_interval:10s])),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Certification lag (finalized_height - certified_height)",
     "type": "timeseries",
     "description": "The average number of rounds between finalization and certification.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic_subnet) (\n    0.5,\n      avg_over_time((artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"} != 0)[$__rate_interval:10s])\n    - on(instance, ic_subnet) \n      avg_over_time((certification_last_certified_height{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} != 0)[$__rate_interval:10s])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Ingress messages in history",
     "type": "timeseries",
     "description": "The average number of entries kept in the ingress history",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic_subnet) (0.5, replicated_state_ingress_history_length{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Expired ingress messages rate",
     "type": "timeseries",
     "description": "The average rate of ingress messages that expire before being picked up for execution.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n   quantile by (ic_subnet) (\n     0.5,\n     rate(scheduler_expired_ingress_messages_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[1h])\n     /\n     sum without (status) (rate(mr_inducted_ingress_message_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\", status=\"success\"}[1h]))\n   ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Replicated message rate by type",
     "type": "timeseries",
     "description": "Replicated messages executed per second, by type.\n\nThe left Y axis measures replicated messages (shown above the zero line); the right Y axis measures non-replicated queries (shown below the zero line). Note the different scales, as there are usually way more non-replicated queries than other types of messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(api_type, wasm_execution_mode) (\n  quantile by(api_type, ic_subnet, wasm_execution_mode) (\n    0.5,\n    sum without(status) (\n      rate(sandboxed_execution_executed_message_slices_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",api_type!~\"non[ -]replicated.*|inspect message\"}[$__rate_interval])\n    )\n  )\n)",
       "legendFormat": "{{api_type}} {{wasm_execution_mode}}"
      }
     ]
    },
    {
     "title": "Failed replicated message rate, by type",
     "type": "timeseries",
     "description": "Failed replicated message executions per second, by  subnet and error condition.\n\nThe left Y axis measures replicated messages (shown above the zero line); the right Y axis measures non-replicated queries (shown below the zero line). Note the different scales, as there are usually way more non-replicated queries than other types of messages.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (api_type, status, wasm_execution_mode) (\n    quantile by (api_type, status, ic_subnet, wasm_execution_mode) (\n        0.5,\n        rate(sandboxed_execution_executed_message_slices_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",api_type!~\"non[ -]replicated.*|inspect message\",status!~\"Success|NoResponse|Paused\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "{{api_type}}, {{status}}, {{wasm_execution_mode}}"
      }
     ]
    },
    {
     "title": "Non-replicated query rate",
     "type": "timeseries",
     "description": "Non-replicated queries executed per second\n\nThe left Y axis measures replicated messages (shown above the zero line); the right Y axis measures non-replicated queries (shown below the zero line). Note the different scales, as there are usually way more non-replicated queries than other types of messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (api_type, wasm_execution_mode) (rate(sandboxed_execution_executed_message_slices_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",api_type=~\"non[ -]replicated.*|inspect message\"}[$__rate_interval]))",
       "legendFormat": "{{api_type}} {{wasm_execution_mode}}"
      }
     ]
    },
    {
     "title": "Failed non-replicated query rate, by type",
     "type": "timeseries",
     "description": "Failed query executions per second, by  subnet and error condition.\n\nThe left Y axis measures replicated messages (shown above the zero line); the right Y axis measures non-replicated queries (shown below the zero line). Note the different scales, as there are usually way more non-replicated queries than other types of messages.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum by (status, ic_subnet, wasm_execution_mode) (\n    rate(sandboxed_execution_executed_message_slices_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",api_type=~\"non[ -]replicated.*|inspect message\",status!~\"Success|NoResponse\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}: {{status}}, {{wasm_execution_mode}}"
      }
     ]
    },
    {
     "title": "Process CPU usage",
     "type": "timeseries",
     "description": "The average CPU usage measured in CPU time spent per second.\n\nValues larger than 1 indicate multiple threads running in parallel.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  avg by (ic_subnet) (rate(process_cpu_seconds_total{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n    ",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Process threads",
     "type": "timeseries",
     "description": "The average number of threads.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace( \n  avg by (ic_subnet) (process_threads{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n) \n\n  ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Replica resident memory",
     "type": "timeseries",
     "description": "The RAM usage of the replica process.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by(ic_subnet) (\n    0.5,\n    process_resident_memory_bytes{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Round execution threads",
     "type": "timeseries",
     "description": "The average number of execution threads.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_inner_iteration_thread_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      (rate(execution_round_inner_iteration_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]) != 0)\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n  ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current heap delta",
     "type": "timeseries",
     "description": "Over-approximation of the RAM used for storing dirty Wasm pages until the next checkpoint.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic_subnet) (\n    0.5,\n    current_heap_delta{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Total canister memory",
     "type": "timeseries",
     "description": "The total memory usage of all canisters combined.\n\nThis is the logical memory and is not necessarily kept in RAM.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic_subnet) (\n    0.5,\n    canister_memory_usage_bytes{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Number of states in memory",
     "type": "timeseries",
     "description": "Total number of states loaded to memory by the state manager.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n   quantile by(ic_subnet) (\n     0.5,\n     sum(state_manager_resident_state_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}) by (ic_subnet, instance)\n   ),\n   \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total number of rounds skipped due to large heap delta",
     "type": "timeseries",
     "description": "The total number of skipped round executions.\n\nThe rounds are skipped because the uncommitted canister state kept in memory is too large. This number should go to zero on the next checkpoint.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n   quantile by (ic_subnet) (\n     0.5,\n     round_skipped_due_to_current_heap_delta_above_limit{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n   ),\n   \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Accessed bytes per second",
     "type": "timeseries",
     "description": "The rate at which canisters access new locations in memory requires the corresponding page to be fetched.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic_subnet, api_type, memory_type) (\n    0.5,\n    rate(sandboxed_execution_accessed_pages_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]) * 4096\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}} {{api_type}} {{memory_type}}"
      }
     ]
    },
    {
     "title": "Hypervisor allocated memory",
     "type": "timeseries",
     "description": "The RAM used for storing dirty Wasm pages until the next checkpoint.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(\n    4096\n  *\n    quantile by (ic_subnet) (\n      0.5,\n      sandboxed_execution_allocated_pages{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n    ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Wasm accessed page distribution",
     "type": "heatmap",
     "description": "Distribution of memory pages accessed per executed message, aggregated over **$heatmap_period**.\n\nA memory page is 4096 bytes,",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(sandboxed_execution_accessed_pages_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Rust resident memory",
     "type": "timeseries",
     "description": "The RAM usage of the Rust heap.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic_subnet) (\n    0.5,\n    jemalloc_resident_bytes{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Total number of changes in canister history per canister",
     "type": "heatmap",
     "description": "The total number of changes in canister history per canister on a subnet.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    quantile by(le, ic_subnet) (\n    0.5,\n    rate(mr_canister_history_total_num_changes_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)\n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Dirty bytes per second",
     "type": "timeseries",
     "description": "The rate at which canisters write to new locations in memory producing dirty pages that need to be saved.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic_subnet, api_type, memory_type) (\n    0.5,\n    rate(sandboxed_execution_dirty_pages_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]) * 4096\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}} {{api_type}} {{memory_type}}"
      }
     ]
    },
    {
     "title": "Heap delta rate limited canisters per round",
     "type": "heatmap",
     "description": "Counts of heap delta rate limited canisters per round, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(scheduler_heap_delta_rate_limited_canisters_per_round_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)\n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Wasm dirty pages distribution",
     "type": "heatmap",
     "description": "Distribution of dirty pages (resulting from memory writes) per executed message, aggregated over **$heatmap_period**.\n\nA memory page is 4096 bytes,",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(sandboxed_execution_dirty_pages_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)\n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "The number of iterations per round",
     "type": "timeseries",
     "description": "How many times the inner round iteration was executed within the outer round",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n       rate(execution_round_inner_iteration_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n     /\n     rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Heap delta debits",
     "type": "heatmap",
     "description": "Distribution of heap delta debits per round, aggregated over **$heatmap_period**. Any entry over the current rate limit should indicate a canister that doesn't get to run in a given round. The current limit is stored in the SchedulerConfig.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(scheduler_canister_heap_delta_debits_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)\n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Wasm compile time, avg",
     "type": "timeseries",
     "description": "The average duration of Wasm compilation",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(hypervisor_wasm_compile_time_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(hypervisor_wasm_compile_time_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "DTS executions per round",
     "type": "timeseries",
     "description": "The number of DTS executions per round.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  quantile by(ic_subnet) (\n      0.5,\n        rate(scheduler_canister_paused_install_code_sum{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        /\n        rate(scheduler_canister_paused_install_code_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "paused_install_code"
      },
      {
       "expr": "sum(\n  quantile by(ic_subnet) (\n      0.5,\n        rate(scheduler_canister_aborted_install_code_sum{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        /\n        rate(scheduler_canister_aborted_install_code_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "paused_aborted_code"
      },
      {
       "expr": "sum(\n  quantile by(ic_subnet) (\n      0.5,\n        rate(scheduler_canister_paused_execution_sum{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        /\n        rate(scheduler_canister_paused_execution_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "paused_execution"
      },
      {
       "expr": "sum(\n  quantile by(ic_subnet) (\n      0.5,\n        rate(scheduler_canister_aborted_execution_sum{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        /\n        rate(scheduler_canister_aborted_execution_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "aborted_execution"
      }
     ]
    }
   ]
  },
  {
   "title": "Canisters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-idle canisters",
     "type": "timeseries",
     "description": "Non-idle canisters that have a heartbeat or an incoming message.\n\nSuch canisters can be scheduled for execution in a round (but are not necessarily executed due to instruction limits).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(scheduler_executable_canisters_per_round_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(scheduler_executable_canisters_per_round_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Non-idle canisters distribution",
     "type": "heatmap",
     "description": "Distribution of non-idle canisters that have a heartbeat or an incoming message, aggregated over **$heatmap_period**.\n\nSuch canisters can be scheduled for execution in a round (but are not necessarily executed due to instruction limits).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(scheduler_executable_canisters_per_round_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Executed canisters",
     "type": "timeseries",
     "description": "Canisters that were actually executed in a round.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(scheduler_executed_canisters_per_round_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(scheduler_executed_canisters_per_round_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Executed canisters distribution",
     "type": "heatmap",
     "description": "Distribution of canisters that were actually executed in a round, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(scheduler_executed_canisters_per_round_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Canister age, rounds",
     "type": "timeseries",
     "description": "Number of rounds for which a canister was not scheduled",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(scheduler_canister_age_rounds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(scheduler_canister_age_rounds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Canister age distribution, rounds",
     "type": "heatmap",
     "description": "Distribution of number of rounds for which a canister was not scheduled, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(scheduler_canister_age_rounds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Total canisters",
     "type": "timeseries",
     "description": "The number of all canister in a subnet.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n   quantile by (ic_subnet) (\n     0.5,\n     sum without(status) (\n       replicated_state_registered_canisters{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n     )\n   ),\n   \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Code section size",
     "type": "heatmap",
     "description": "Distribution of the size of code sections for compiled canister Wasms, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(hypervisor_code_section_size_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cycles Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cycle burn rate",
     "type": "timeseries",
     "description": "The total number of cycles burned per second in a subnet.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic_subnet) (\n    0.5,\n    deriv(\n      (replicated_state_consumed_cycles_since_replica_started{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} > 0)[$__rate_interval:10s]\n    )\n  )\n>=\n  0,\n   \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Cycle burn rate by use cases",
     "type": "timeseries",
     "description": "The total number of cycles burned per second in a subnet by use cases.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic_subnet, use_case) (\n    0.5,\n    deriv(\n      (replicated_state_consumed_cycles_from_replica_start{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} > 0)[$__rate_interval:10s]\n    )\n  )\n>=\n  0,\n   \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}-{{use_case}}"
      }
     ]
    },
    {
     "title": "Subnet cycles balance (in trillions)",
     "type": "timeseries",
     "description": "Total cycle balance (in trillions of cycles) across all canisters on a subnet",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n   quantile by (ic_subnet) (\n     0.5,\n       (scheduler_canister_balance_cycles_total{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} != 0)\n     /\n       1e12\n   ),\n   \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Subnet cycles consumed (in trillions)",
     "type": "timeseries",
     "description": "Total cycle balance (in trillions of cycles) across all canisters on a subnet",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n   quantile by (ic_subnet) (\n     0.5,\n       (replicated_state_consumed_cycles_since_replica_started{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} != 0)\n     /\n       1e12\n   ),\n   \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Execute Round Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Info",
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 204 },
     "options": {
      "content": "- Charts break down the `execute_round` function time into known steps and `(other)`\n- `(other)` represents untracked time\n- `(other)` should be near zero; a non-zero value indicates a problem\n"
     }
    },
    {
     "title": "Execute Round Duration, avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "execution_round"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_preparation_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· preparation"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_consensus_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· consensus_queue"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_postponed_raw_rand_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· postponed_raw_rand"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_advance_long_install_code_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· advance_long_install"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_scheduling_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· scheduling"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_subnet_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· subnet_queue"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_inner_heartbeat_overhead_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· canister_tasks"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_inner_preparation_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· inner_loop_prep"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_inner_execution_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· inner_loop_exe"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_inner_finalization_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· inner_loop_fin"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_finalization_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· finalization"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      clamp_min(\n        rate(execution_round_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_preparation_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_consensus_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_postponed_raw_rand_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_advance_long_install_code_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_scheduling_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_inner_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_finalization_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]),\n        0\n      )\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· (other)"
      }
     ]
    },
    {
     "title": "Execute Round Duration %, avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "execution_round"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_preparation_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· preparation"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_consensus_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· consensus_queue"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_postponed_raw_rand_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· postponed_raw_rand"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_advance_long_install_code_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· advance_long_install"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_scheduling_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· scheduling"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_subnet_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· subnet_queue"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_inner_heartbeat_overhead_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· canister_tasks"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_inner_preparation_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· inner_loop_prep"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_inner_execution_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· inner_loop_exe"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_inner_finalization_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· inner_loop_fin"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_finalization_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· finalization"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      clamp_min(\n        rate(execution_round_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_preparation_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_consensus_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_postponed_raw_rand_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_advance_long_install_code_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_scheduling_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_inner_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        -\n        rate(execution_round_finalization_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]),\n        0\n      )\n    /\n      rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "· (other)"
      }
     ]
    }
   ]
  },
  {
   "title": "Round/Thread/Message Durations and Instructions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Round duration, avg",
     "type": "timeseries",
     "description": "The average duration of an execution round.\n\nRelated submetrics:\n- subnet queue duration,\n- consensus queue duration,\n- message duration.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      (rate(execution_round_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]) != 0)\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Round instructions, avg",
     "type": "timeseries",
     "description": "The average number of Wasm instructions executed in an execution round.\n\nRelated submetrics:\n- subnet queue instructions,\n- consensus queue instructions,\n- message instructions.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_instructions_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      (rate(execution_round_instructions_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]) != 0)\n  ),\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Round duration distribution",
     "type": "heatmap",
     "description": "Distribution of the duration of executing a round, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(execution_round_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Round instructions distribution",
     "type": "heatmap",
     "description": "Distribution of Wasm instructions executed while  executing a message in an execution round, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(execution_round_instructions_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Round duration, max",
     "type": "timeseries",
     "description": "The maximum duration of an execution round.\n\nRelated submetrics:\n\n- subnet queue duration,\n- consensus queue duration,\n- message duration.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n    histogram_quantile (\n      1.0,\n      rate(execution_round_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}-round"
      }
     ]
    },
    {
     "title": "Round instructions, max",
     "type": "timeseries",
     "description": "The maximum number of Wasm instructions executed in an execution round.\n\nRelated submetrics:\n\n- subnet queue instructions,\n- consensus queue instructions,\n- message instructions.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n    histogram_quantile (\n      1.0,\n      rate(execution_round_instructions_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Thread duration distribution",
     "type": "heatmap",
     "description": "Distribution of the duration of executing messages in a thread, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(execution_round_inner_iteration_thread_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Thread instructions distribution",
     "type": "heatmap",
     "description": "Distribution of Wasm instructions executed in a thread while  executing a message, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(execution_round_inner_iteration_thread_instructions_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Replicated message duration, avg",
     "type": "timeseries",
     "description": "The average duration of a replicated message execution in an execution round.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      (\n          rate(execution_round_inner_iteration_thread_message_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n      )\n    /\n      (\n          rate(execution_round_inner_iteration_thread_message_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        != 0\n      )\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Replicated message instructions, avg",
     "type": "timeseries",
     "description": "The average number of Wasm instructions executed in a replicated message in an execution round.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      (\n          rate(execution_round_inner_iteration_thread_message_instructions_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n      )\n    /\n      (\n          rate(execution_round_inner_iteration_thread_message_instructions_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n        != 0\n      )\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Replicated message duration, max",
     "type": "timeseries",
     "description": "The maximum duration of a replicated message execution in an execution round.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n    histogram_quantile (\n      1.0,\n        rate(execution_round_inner_iteration_thread_message_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Replicated message instructions, max",
     "type": "timeseries",
     "description": "The maximum number of Wasm instructions executed in a replicated message in an execution round.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n    histogram_quantile (\n      1.0,\n        rate(execution_round_inner_iteration_thread_message_instructions_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Replicated message duration distribution",
     "type": "heatmap",
     "description": "Distribution of the duration of executing a replicated message, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(execution_round_inner_iteration_thread_message_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Replicated message instructions distribution",
     "type": "heatmap",
     "description": "Distribution of Wasm instructions executed while  executing a replicated message in an execution round, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n        increase(execution_round_inner_iteration_thread_message_instructions_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Non-replicated query duration, avg",
     "type": "timeseries",
     "description": "The average duration of non-replicated query execution.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n    sum by(ic_subnet) (\n          rate(execution_query_duration_seconds_sum{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  / \n    sum by(ic_subnet) (\n      rate(execution_query_duration_seconds_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Non-replicated query instructions, avg",
     "type": "timeseries",
     "description": "The average number of Wasm instructions executed while handling a non-replicated query.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n    sum by(ic_subnet) (\n      rate(execution_query_instructions_sum{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  /\n    sum by(ic_subnet) (\n      rate(execution_query_instructions_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Non-replicated query duration, max",
     "type": "timeseries",
     "description": "The maximum duration of a non-replicated query execution.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 281 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  max by(ic_subnet) (\n    histogram_quantile(1.0, rate(execution_query_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]))\n  )\n ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Non-replicated query instructions, max",
     "type": "timeseries",
     "description": "The maximum number of Wasm instructions executed while handling a non-replicated query.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 281 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  max by(ic_subnet) (\n    histogram_quantile(1.0, rate(execution_query_instructions_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]))\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Non-replicated query duration distribution",
     "type": "heatmap",
     "description": "Distribution of non-replicated query execution durations, aggregated over **$heatmap_period**.\n\nNote that queries are not replicated and query load is more or less evenly spread across replicas.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 289 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    sum by(le, ic_subnet) (\n      increase(execution_query_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Non-replicated query instructions distribution",
     "type": "heatmap",
     "description": "Distribution of non-replicated queries by Wasm instructions executed, aggregated over **$heatmap_period**.\n\nNote that queries are not replicated and query load is more or less evenly spread across replicas.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 289 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    sum by(le, ic_subnet) (\n      increase(execution_query_instructions_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Non-replicated inspect_message duration, avg",
     "type": "timeseries",
     "description": "The average duration of non-replicated inspect_message execution.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n    sum by(ic_subnet) (\n          rate(execution_inspect_message_duration_seconds_sum{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  / \n    sum by(ic_subnet) (\n      rate(execution_inspect_message_duration_seconds_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Non-replicated inspect_message instructions, avg",
     "type": "timeseries",
     "description": "The average number of Wasm instructions executed while handling a non-replicated inspect_message.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n    sum by(ic_subnet) (\n      rate(execution_inspect_message_instructions_sum{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  /\n    sum by(ic_subnet) (\n      rate(execution_inspect_message_instructions_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Non-replicated inspect_message duration, max",
     "type": "timeseries",
     "description": "The maximum duration of a non-replicated inspect_message execution.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  max by(ic_subnet) (\n    histogram_quantile(1.0, rate(execution_inspect_message_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]))\n  )\n ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Non-replicated inspect_message instructions, max",
     "type": "timeseries",
     "description": "The maximum number of Wasm instructions executed while handling a non-replicated inspect_message.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  max by(ic_subnet) (\n    histogram_quantile(1.0, rate(execution_inspect_message_instructions_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]))\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Non-replicated inspect_message duration distribution",
     "type": "heatmap",
     "description": "Distribution of non-replicated inspect_message execution durations, aggregated over **$heatmap_period**.\n\nNote that inspect_message executions are not replicated and load is more or less evenly spread across replicas.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 313 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    sum by(le, ic_subnet) (\n      increase(execution_inspect_message_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Non-replicated inspect_message instructions distribution",
     "type": "heatmap",
     "description": "Distribution of non-replicated inspect_message executions by Wasm instructions executed, aggregated over **$heatmap_period**.\n\nNote that inspect_message executions are not replicated and load is more or less evenly spread across replicas.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 313 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    sum by(le, ic_subnet) (\n      increase(execution_inspect_message_instructions_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Call tree age distribution",
     "type": "heatmap",
     "description": "Distribution of call tree ages at the time when canister calls were made, aggregated over **$heatmap_period**.\n\nThis is how long ago the call context at the root of the call tree was created.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 321 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    quantile without(ic_node, instance) (\n      0.5,\n      increase(execution_environment_request_call_tree_age_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Call tree depth distribution",
     "type": "heatmap",
     "description": "Distribution of the call tree depth at which canister calls were made, aggregated over **$heatmap_period**.\n\nA call tree depth of zero means that the canister call was made from the call context of an Ingress messages or heartbeat / timer. Calls with a call tree depth of 1 or higher were made from the call context of a canister call.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 321 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    quantile without(ic_node, instance) (\n      0.5,\n      increase(execution_environment_request_call_tree_depth_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Call duration distribution",
     "type": "heatmap",
     "description": "Distribution of call durations, aggregated over **$heatmap_period**.\n\nNote that a call may span multiple message executions and be suspended for arbitrarily long while waiting for a response.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 329 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    quantile by(le, ic_subnet) (\n      0.5,\n      increase(execution_call_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sandbox",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sandbox resident memory",
     "type": "timeseries",
     "description": "The RSS of all sandbox processes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 350 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(\n    1024\n  *\n    quantile by (ic_subnet) (\n      0.5,\n      sandboxed_execution_subprocess_anon_rss_total_kib{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n      +\n      sandboxed_execution_subprocess_memfd_rss_total_kib{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n    ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}-total"
      },
      {
       "expr": "label_replace(\n    1024\n  *\n    quantile by (ic_subnet) (\n      0.5,\n      sandboxed_execution_subprocess_anon_rss_total_kib{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n    ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}-private"
      }
     ]
    },
    {
     "title": "Sandbox spawn process duration",
     "type": "timeseries",
     "description": "The average duration of spawning a sandbox process",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 350 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(sandboxed_execution_spawn_process_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(sandboxed_execution_spawn_process_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Sandboxed execution duration",
     "type": "timeseries",
     "description": "The average duration of executing a message in the sandbox process",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 358 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet, api_type) (\n    0.5,\n      rate(sandboxed_execution_replica_execute_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(sandboxed_execution_replica_execute_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}-{{api_type}}-total"
      },
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet, api_type) (\n    0.5,\n      rate(sandboxed_execution_sandbox_execute_run_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(sandboxed_execution_sandbox_execute_run_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}-{{api_type}}-sandbox"
      }
     ]
    },
    {
     "title": "Sandbox processes",
     "type": "timeseries",
     "description": "The number of sandbox processes in a subnet.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 358 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      idelta(sandboxed_execution_subprocess_active_last_used_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Sandbox cache hit ratio %",
     "type": "timeseries",
     "description": "Sandbox cache hit ratio = hits / number_of_message_slices ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 366 },
     "targets": [
      {
       "expr": "label_replace(\n    quantile by (ic_subnet) ( \n        0.5,\n        (\n            sum by (instance, ic_node, ic_subnet) (\n                rate(sandboxed_execution_replica_cache_lookups{ic=\"$ic\",ic_subnet=~\"$ic_subnet\", job=\"replica\", lookup_result=\"embedder_cache_hit_success\"}[$__rate_interval])\n            )\n            /\n            (\n                sum by (instance, ic_node, ic_subnet) (\n                    rate(sandboxed_execution_replica_cache_lookups{ic=\"$ic\",ic_subnet=~\"$ic_subnet\", job=\"replica\", lookup_result=\"embedder_cache_hit_success\"}[$__rate_interval])\n                )\n                +\n                (\n                    sum by (instance, ic_node, ic_subnet) (\n                        rate(sandboxed_execution_replica_cache_lookups{ic=\"$ic\",ic_subnet=~\"$ic_subnet\", job=\"replica\", lookup_result=\"embedder_cache_hit_sandbox_evicted\"}[$__rate_interval])\n                    )\n                    or\n                    sum by (instance, ic_node, ic_subnet) (\n                        rate(sandboxed_execution_replica_cache_lookups{ic=\"$ic\",ic_subnet=~\"$ic_subnet\", job=\"replica\", lookup_result=\"embedder_cache_hit_success\"}[$__rate_interval])\n                    ) * 0\n                )\n            )\n        )\n    ) ,\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compilation cache size",
     "type": "timeseries",
     "description": "Memory and disk usage of compilation cache. Note that individual nodes may vary in cache footprints and this is the median for each subnet.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(\n    quantile by (location,ic_subnet) (\n      0.5,\n      hypervisor_compilation_cache_size{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n    ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}-{{location}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subnet Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subnet queue duration, avg",
     "type": "timeseries",
     "description": "The average duration of draining the subnet message queue in an execution round.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 375 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_subnet_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_subnet_queue_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Subnet queue instructions, avg",
     "type": "timeseries",
     "description": "The average number of Wasm instructions executed while draining the subnet message queue in an execution round.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 375 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_subnet_queue_instructions_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_subnet_queue_instructions_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Subnet queue duration distribution",
     "type": "heatmap",
     "description": "Distribution of the duration draining the subnet message queue in an execution round, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 383 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(execution_round_subnet_queue_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Subnet queue instructions distribution",
     "type": "heatmap",
     "description": "Distribution of Wasm instructions executed while draining the subnet message queue in an execution round, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 383 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      increase(execution_round_subnet_queue_instructions_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Subnet queue duration, max",
     "type": "timeseries",
     "description": "The maximum duration of draining the subnet message queue in an execution round.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 391 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n    histogram_quantile (\n      1.0,\n      rate(execution_round_subnet_queue_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Subnet queue instructions, max",
     "type": "timeseries",
     "description": "The maximum number of Wasm instructions executed while draining the subnet message queue in an execution round.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 391 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n    histogram_quantile (\n      1.0,\n      rate(execution_round_subnet_queue_instructions_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Consensus queue duration, avg",
     "type": "timeseries",
     "description": "The average duration of draining the consensus message queue in an execution round.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 399 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_consensus_queue_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_consensus_queue_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Consensus queue instructions, avg",
     "type": "timeseries",
     "description": "The average number of Wasm instructions executed while draining the consensus message queue in an execution round.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 399 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n      rate(execution_round_consensus_queue_instructions_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    /\n      rate(execution_round_consensus_queue_instructions_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval]) \n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Subnet messages by type",
     "type": "timeseries",
     "description": "The number of subnet messages executed per second grouped by the method name.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 407 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(method_name) (\n  quantile by(method_name, ic_subnet) (\n    0.5,\n    sum without(outcome, status) (\n      rate(execution_subnet_message_duration_seconds_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$__rate_interval])\n    )\n  )\n)",
       "legendFormat": "{{api_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-replicated query rate",
     "type": "timeseries",
     "description": "Non-replicated queries executed per second\n\nThe left Y axis measures replicated messages (shown above the zero line); the right Y axis measures non-replicated queries (shown below the zero line). Note the different scales, as there are usually way more non-replicated queries than other types of messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 416 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (api_type) (rate(sandboxed_execution_executed_message_slices_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",api_type=~\"non[ -]replicated.*|inspect message\"}[$__rate_interval]))",
       "legendFormat": "{{api_type}}"
      }
     ]
    },
    {
     "title": "Query cache hit ratio",
     "type": "timeseries",
     "description": "Query cache hit ratio = hits / (hits + misses)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 416 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum by(ic_subnet) (\n    rate(execution_query_cache_hits_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  )\n  / \n  (\n    sum by(ic_subnet) (\n      rate(execution_query_cache_hits_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n    +\n    sum by(ic_subnet) (\n      rate(execution_query_cache_misses_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n    )\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Query cache hit rate",
     "type": "timeseries",
     "description": "Query cache hits per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 424 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum by(ic_subnet) (\n    rate(execution_query_cache_hits_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Query cache miss rate",
     "type": "timeseries",
     "description": "Query cache misses per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 424 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum by(ic_subnet) (\n    rate(execution_query_cache_misses_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Query cache eviction rate",
     "type": "timeseries",
     "description": "Query cache evictions per second, i.e. cache entries removed due to the cache size limit",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 432 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum by(ic_subnet) (\n    rate(execution_query_cache_evicted_entries_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Evicted cache entries duration distribution",
     "type": "heatmap",
     "description": "Distribution of evicted cache entries duration, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 432 },
     "targets": [
      {
       "expr": "sum by (le) (\n  avg by(le, ic_subnet) (\n    increase(execution_query_cache_evicted_entries_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Query cache invalidation rate",
     "type": "timeseries",
     "description": "Query cache invalidations per second, i.e. cache entries removed due to some changes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 440 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum by(ic_subnet) (\n    rate(execution_query_cache_invalidated_entries_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Invalidated cache entries duration distribution",
     "type": "heatmap",
     "description": "Distribution of invalidated cache entries duration, aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 440 },
     "targets": [
      {
       "expr": "sum by (le) (\n  avg by(le, ic_subnet) (\n    increase(execution_query_cache_invalidated_entries_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Total query cache invalidation reason",
     "type": "timeseries",
     "description": "Total query cache invalidation reasons per second, i.e. the number of cache entries removed due to some changes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 448 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum(\n    rate(execution_query_cache_invalidated_entries_by_time_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "System time"
      },
      {
       "expr": "label_replace(\n  sum(\n    rate(execution_query_cache_invalidated_entries_by_canister_version_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "Canister version"
      },
      {
       "expr": "label_replace(\n  sum(\n    rate(execution_query_cache_invalidated_entries_by_canister_balance_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "Canister balance"
      }
     ]
    },
    {
     "title": "Query cache invalidation rate by time",
     "type": "timeseries",
     "description": "Query cache invalidations by time per second, i.e. the number of cache entries removed due to the time changes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 448 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum by(ic_subnet) (\n    rate(execution_query_cache_invalidated_entries_by_time_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Subnet query cache size",
     "type": "timeseries",
     "description": "The total size of the whole subnet query caches, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 456 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum by(ic_subnet) (\n    execution_query_cache_count_bytes{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Subnet query cache elements",
     "type": "timeseries",
     "description": "The total number of the whole subnet query cache elements.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 456 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum by(ic_subnet) (\n    execution_query_cache_len{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Average query cache element size",
     "type": "timeseries",
     "description": "The average query cache element size, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 464 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\n  sum by(ic_subnet) (\n    execution_query_cache_count_bytes{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n  )\n  /\n  sum by(ic_subnet) (\n    execution_query_cache_len{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}\n  )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Canister Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Subnet Canister Log Memory Usage",
     "type": "timeseries",
     "description": "Total canister log memory usage across all canisters on a subnet",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 473 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(\n   quantile by (ic_subnet) (\n      0.5,\n         rate(canister_log_memory_usage_bytes_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n      / \n         rate(state_manager_max_resident_height{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$__rate_interval])\n      != 0\n   ),\n   \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)\n",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Average Subnet Canister Log Memory Usage",
     "type": "timeseries",
     "description": "Average memory usage for canister logs across each subnet",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 473 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(\n  avg by (ic_subnet) (\n    rate(canister_log_memory_usage_bytes_v2_sum{ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$heatmap_period])\n    /\n    rate(canister_log_memory_usage_bytes_v2_count{ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$heatmap_period])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
       "legendFormat": "{{ic_subnet}}"
      }
     ]
    },
    {
     "title": "Fetch Canister Logs Query Execution Rate",
     "type": "timeseries",
     "description": "The rate of `fetch_canister_logs` management canister query executions per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 481 },
     "fieldConfig": { "defaults": { "unit": "calls/s" } },
     "targets": [
      {
       "expr": "sum by(method_name) (\n  quantile by(method_name, ic_subnet) (\n    0.5,\n    sum without(status) (\n      rate(execution_subnet_query_message_duration_seconds_count{\n        job=\"replica\", \n        ic=\"$ic\", \n        ic_subnet=~\"$ic_subnet\", \n        instance=~\"$instance\",\n        method_name=\"query_ic00_fetch_canister_logs\"\n      }[$__rate_interval])\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Canister Log Memory Usage",
     "type": "heatmap",
     "description": "Distribution of canister log memory usage (per canister), aggregated over **$heatmap_period**.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 481 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n        rate(canister_log_memory_usage_bytes_v2_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n      / ignoring(le) group_left\n        rate((state_manager_max_resident_height{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} != 0)[$heatmap_period:10s])\n    )\n  )\n)\n",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}