{
 "title": "Latencies",
 "description": "Latency distribution of replica operations",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "label": "IC", "query": { "query": "label_values(ic)" } },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\"}, ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "Instances",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   },
   {
    "name": "http_request_type",
    "label": "HTTP Request Type",
    "query": {
     "query": "label_values(replica_http_request_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}, request_type)"
    }
   },
   {
    "name": "state_manager_api_op",
    "label": "API Operation",
    "query": {
     "query": "label_values(state_manager_api_call_duration_seconds_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}, op)"
    }
   },
   {
    "name": "state_manager_checkpoint_op",
    "label": "Checkpoint Operation",
    "query": {
     "query": "label_values(state_manager_checkpoint_op_duration_seconds_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}, op)"
    }
   },
   {
    "name": "consensus_validation_type",
    "label": "Validation Type",
    "query": {
     "query": "label_values(consensus_validation_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}, type)"
    }
   },
   { "name": "period", "label": "Period", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "IC Alerts",
   "type": "natel-discrete-panel",
   "description": "Alert history for _**$ic**_.\n\n* *green* - not firing\n* *yellow* - firing, `severity=\"info\"`\n* *orange* - firing, `severity=\"ticket\"`\n* *red* - firing, `severity=\"page\"`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\nlabel_replace(\nlabel_replace(\nlabel_replace(\nlabel_replace(\nsum without (severity, alertstate) (\n  max_over_time(ALERTS{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",alertstate=\"firing\",severity=\"page\"}[$__interval]) * 3\n    or on (job, ic, alertname, alertstate)\n  max_over_time(ALERTS{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",alertstate=\"firing\",severity=\"ticket\"}[$__interval]) * 2\n    or on (job, ic, alertname, alertstate)\n  max_over_time(ALERTS{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",alertstate=\"firing\",severity=\"info\"}[$__interval]) * 1\n),\n\"__name__\", \"$1 \", \"alertname\", \"(.*)\"),\n\"alertname\", \"\", \"alertname\", \".*\"),\n\"ic\", \"\", \"ic\", \".*\"),\n\"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"),\n\"ic_node\", \"$1\", \"ic_node\", \"([a-z0-9]+)-.*\"),\n\"instance\", \"$1...$2\", \"instance\", \"(\\\\[[^.:]+[.:]).*([.:][^.:]+\\\\]?:[0-9]+)\")"
    }
   ]
  },
  {
   "title": "Running replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  up{job=\"replica\", instance=~\"$instance\", ic=\"$ic\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "  max_over_time(process_start_time_seconds{job=\"replica\", instance=~\"$instance\", ic=\"$ic\"}[5m])\n!= bool\n  max_over_time(process_start_time_seconds{job=\"replica\", instance=~\"$instance\", ic=\"$ic\"}[5m] offset $__interval)",
     "legendFormat": "{{instance}} restart"
    }
   ]
  },
  {
   "title": "Interesting latency histograms",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": {
    "content": "* `consensus_get_payload_duration_bucket`\n* `consensus_on_state_change_duration_seconds_bucket`\n* `consensus_processing_time_bucket`\n* `dkg_processing_time_bucket`\n* `execution_subnet_message_duration_seconds_bucket`\n* `ingress_processing_time_bucket`\n* `message_state_transition_completed_wallclock_duration_seconds_bucket`\n* `mr_process_batch_duration_seconds_bucket`\n* `ni_dkg_processing_time_bucket`\n* `p2p_gossip_op_duration_bucket`\n* `scheduler_message_execution_duration_seconds_bucket`\n* `xnet_builder_build_payload_duration_seconds_bucket`"
   }
  },
  {
   "title": "Finalization Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "quantile(1, rate(artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"}[$period]))",
     "legendFormat": "Max"
    },
    {
     "expr": "quantile(.8, rate(artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"}[$period]))",
     "legendFormat": "80th percentile"
    },
    {
     "expr": "quantile(.5, rate(artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"}[$period]))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "quantile(.2, rate(artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"}[$period]))",
     "legendFormat": "20th percentile"
    },
    {
     "expr": "quantile(0, rate(artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"}[$period]))",
     "legendFormat": "Min"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$http_request_type Request Durations, Aggregated",
   "type": "graph",
   "description": "$http_request_type HTTP request duration distribution across selected subnets, aggregated over **$period** (configurable).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "repeat": "http_request_type",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(ic, le) (\n  rate(replica_http_request_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",request_type=~\"$http_request_type\",status=~\"[23]..+\"}[$period])\n))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(.95, sum by(ic, le) (\n  rate(replica_http_request_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",request_type=~\"$http_request_type\",status=~\"[23]..+\"}[$period])\n))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(.9, sum by(ic, le) (\n  rate(replica_http_request_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",request_type=~\"$http_request_type\",status=~\"[23]..+\"}[$period])\n))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(.5, sum by(ic, le) (\n  rate(replica_http_request_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",request_type=~\"$http_request_type\",status=~\"[23]..+\"}[$period])\n))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(1e-9, sum by(ic, le) (\n  rate(replica_http_request_duration_seconds_bucket{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",request_type=~\"$http_request_type\",status=~\"[23]..+\"}[$period])\n))",
     "legendFormat": "Min"
    }
   ]
  },
  { "title": "State Manager API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "State Manager API `$state_manager_api_op` Duration",
   "type": "graph",
   "description": "State Manager API operation duration distribution across selected instances, aggregated over **$period** (configurable).\n\nThe purple overlay shows the time share (proportion of time spent in `$state_manager_api_op`).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "repeat": "state_manager_api_op",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(ic, le) (rate(state_manager_api_call_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_api_op\"}[$period])))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(.95, sum by(ic, le) (rate(state_manager_api_call_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_api_op\"}[$period])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(.9, sum by(ic, le) (rate(state_manager_api_call_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_api_op\"}[$period])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(.5, sum by(ic, le) (rate(state_manager_api_call_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_api_op\"}[$period])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(1e-9, sum by(ic, le) (rate(state_manager_api_call_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_api_op\"}[$period])))",
     "legendFormat": "Min"
    },
    {
     "expr": "  sum(rate(state_manager_api_call_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_api_op\"}[$period]))\n/\n  sum(rate(state_manager_api_call_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_api_op\"}[$period]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "  sum(rate(state_manager_api_call_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_api_op\"}[$period]))\n/\n  count(state_manager_api_call_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_api_op\"})",
     "legendFormat": "Time share"
    }
   ]
  },
  { "title": "State Manager Checkpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "State Manager Checkpoint  `$state_manager_checkpoint_op` Duration",
   "type": "graph",
   "description": "State Manager checkpoint operation duration distribution across selected instances, aggregated over **$period** (configurable).\n\nThe purple overlay shows the time share (proportion of time spent in `$state_manager_api_op`).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "repeat": "state_manager_checkpoint_op",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(ic, le) (rate(state_manager_checkpoint_op_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_checkpoint_op\"}[$period])))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(.95, sum by(ic, le) (rate(state_manager_checkpoint_op_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_checkpoint_op\"}[$period])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(.9, sum by(ic, le) (rate(state_manager_checkpoint_op_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_checkpoint_op\"}[$period])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(.5, sum by(ic, le) (rate(state_manager_checkpoint_op_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_checkpoint_op\"}[$period])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(1e-9, sum by(ic, le) (rate(state_manager_checkpoint_op_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_checkpoint_op\"}[$period])))",
     "legendFormat": "Min"
    },
    {
     "expr": "  sum(rate(state_manager_checkpoint_op_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_checkpoint_op\"}[$period]))\n/\n  sum(rate(state_manager_checkpoint_op_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_checkpoint_op\"}[$period]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "  sum(rate(state_manager_checkpoint_op_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_checkpoint_op\"}[$period]))\n/\n  count(state_manager_checkpoint_op_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",op=~\"$state_manager_checkpoint_op\"})",
     "legendFormat": "Time share"
    }
   ]
  },
  { "title": "Consensus Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Consensus Validation  `$consensus_validation_type` Duration",
   "type": "graph",
   "description": "Consensus validation duration distribution by artifact type across selected instances, aggregated over **$period** (configurable).\n\nThe purple overlay shows the time share (proportion of time spent validating `$consensus_validation_type`).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "repeat": "consensus_validation_type",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(ic, le) (rate(consensus_validation_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=~\"$consensus_validation_type\"}[$period])))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(.95, sum by(ic, le) (rate(consensus_validation_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=~\"$consensus_validation_type\"}[$period])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(.9, sum by(ic, le) (rate(consensus_validation_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=~\"$consensus_validation_type\"}[$period])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(.5, sum by(ic, le) (rate(consensus_validation_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=~\"$consensus_validation_type\"}[$period])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(1e-9, sum by(ic, le) (rate(consensus_validation_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=~\"$consensus_validation_type\"}[$period])))",
     "legendFormat": "Min"
    },
    {
     "expr": "  sum(rate(consensus_validation_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=~\"$consensus_validation_type\"}[$period]))\n/\n  sum(rate(consensus_validation_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=~\"$consensus_validation_type\"}[$period]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "  sum(rate(consensus_validation_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=~\"$consensus_validation_type\"}[$period]))\n/\n  count(consensus_validation_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=~\"$consensus_validation_type\"})",
     "legendFormat": "Time share"
    }
   ]
  }
 ]
}