{
 "title": "NNS dapp",
 "time": { "from": "now-4w", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "query0", "query": { "query": "" } },
   { "name": "query1", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Daily active users",
   "type": "timeseries",
   "description": "Number of distinct principals that made a get_account call from any frontend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT toStartOfDay(date) as t, count(distinct ic_sender)\nFROM $table\nWHERE true\n    AND $timeFilter\n    AND ic_canister_id == 'qoctq-giaaa-aaaaa-aaaea-cai'\n    AND ic_method_name == 'get_account'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT toStartOfDay(date) as t, count(distinct ic_sender)\nFROM default.http_access_nns_dapp\nWHERE true\n    AND date >= toDateTime(1690816960) AND date <= toDateTime(1691421760)\n    AND ic_canister_id == 'qoctq-giaaa-aaaaa-aaaea-cai'\n    AND ic_method_name == 'get_account'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "http_access_nns_dapp"
    }
   ]
  },
  {
   "title": "7-day active users",
   "type": "timeseries",
   "description": "Number of distinct principals that made a get_account call from any frontend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "WITH\nweekdays as (\n    SELECT number as day FROM system.numbers limit 7\n),\nactivity_days as (\n    SELECT toStartOfDay(date) as t, ic_sender\n    FROM default.http_access_nns_dapp\n    WHERE true\n        AND date >= addDays(toDateTime($__from / 1000) , -7)\n        AND ic_canister_id == 'qoctq-giaaa-aaaaa-aaaea-cai'\n        AND ic_method_name == 'get_account'\n)\nSELECT addDays(t, day) as date, count(distinct ic_sender)\nFROM activity_days, weekdays\nWHERE $timeFilter\nGROUP BY date\nORDER BY date",
     "rawQuery": "WITH\nweekdays as (\n    SELECT number as day FROM system.numbers limit 7\n),\nactivity_days as (\n    SELECT toStartOfDay(date) as t, ic_sender\n    FROM default.http_access_nns_dapp\n    WHERE true\n        AND date >= addDays(toDateTime(1689586368951 / 1000) , -7)\n        AND ic_canister_id == 'qoctq-giaaa-aaaaa-aaaea-cai'\n        AND ic_method_name == 'get_account'\n)\nSELECT addDays(t, day) as date, count(distinct ic_sender)\nFROM activity_days, weekdays\nWHERE date >= toDateTime(1689586425) AND date <= toDateTime(1692178425)\nGROUP BY date\nORDER BY date",
     "round": "0s",
     "table": "http_access_nns_dapp"
    }
   ]
  },
  {
   "title": "28-day active users",
   "type": "timeseries",
   "description": "Number of distinct principals that made a get_account call from any frontend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "WITH\nweekdays as (\n    SELECT number as day FROM system.numbers limit 28\n),\nactivity_days as (\n    SELECT toStartOfDay(date) as t, ic_sender\n    FROM default.http_access_nns_dapp\n    WHERE true\n        AND date >= addDays(toDateTime($__from / 1000) , -28)\n        AND ic_canister_id == 'qoctq-giaaa-aaaaa-aaaea-cai'\n        AND ic_method_name == 'get_account'\n)\nSELECT addDays(t, day) as date, count(distinct ic_sender)\nFROM activity_days, weekdays\nWHERE $timeFilter\nGROUP BY date\nORDER BY date",
     "rawQuery": "WITH\nweekdays as (\n    SELECT number as day FROM system.numbers limit 28\n),\nactivity_days as (\n    SELECT toStartOfDay(date) as t, ic_sender\n    FROM default.http_access_nns_dapp\n    WHERE true\n        AND date >= addDays(toDateTime(1691573663604 / 1000) , -28)\n        AND ic_canister_id == 'qoctq-giaaa-aaaaa-aaaea-cai'\n        AND ic_method_name == 'get_account'\n)\nSELECT addDays(t, day) as date, count(distinct ic_sender)\nFROM activity_days, weekdays\nWHERE date >= toDateTime(1691573663) AND date <= toDateTime(1692178463)\nGROUP BY date\nORDER BY date",
     "round": "0s",
     "table": "http_access_nns_dapp"
    }
   ]
  },
  {
   "title": "Bounce rate",
   "type": "timeseries",
   "description": "Ratio of IP addresses making an http request on nns.ic0.app that also make a get_account request in the same hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "WITH\n    'https://nns.ic0.app' AS ORIGIN,\n    ('get_account') AS RELEVANT_ACTION,\n    page_load_ips as\n    (\n    SELECT DISTINCT toUInt32(toStartOfHour(date)) * 1000 as t, remote_addr_hashed\n    FROM $table\n    WHERE $timeFilter\n    AND http_origin == ORIGIN\n    AND ic_method_name == 'http_request'\n    GROUP BY t, remote_addr_hashed\n    ),\n    action_ips as\n    (\n    SELECT DISTINCT toUInt32(toStartOfHour(date)) * 1000 as t, remote_addr_hashed\n    FROM $table\n    WHERE $timeFilter\n    AND http_origin == ORIGIN\n    AND ic_method_name IN RELEVANT_ACTION\n    GROUP BY t, remote_addr_hashed\n    )\nSELECT t, num_no_action / num_page_loads as bounce_rate\nFROM (\n         \n         SELECT t, count(DISTINCT remote_addr_hashed) as num_no_action\n         FROM page_load_ips LEFT JOIN action_ips ON page_load_ips.remote_addr_hashed == action_ips.remote_addr_hashed\n         WHERE action_ips.remote_addr_hashed == ''\n         GROUP BY t\n     ) as no_action_count  INNER JOIN\n     (\n         \n         SELECT t, count(DISTINCT remote_addr_hashed) as num_page_loads\n         FROM\n             (\n                 SELECT t, remote_addr_hashed\n                 FROM action_ips\n                 UNION DISTINCT\n                 SELECT t, remote_addr_hashed\n                 FROM page_load_ips\n             )\n         GROUP BY t\n     ) as all_count ON no_action_count.t == all_count.t\nORDER BY t",
     "rawQuery": "WITH\n    'https://nns.ic0.app' AS ORIGIN,\n    ('get_account') AS RELEVANT_ACTION,\n    page_load_ips as\n    (\n    SELECT DISTINCT toUInt32(toStartOfHour(date)) * 1000 as t, remote_addr_hashed\n    FROM default.http_access_nns_dapp\n    WHERE date >= toDateTime(1690817010) AND date <= toDateTime(1691421810)\n    AND http_origin == ORIGIN\n    AND ic_method_name == 'http_request'\n    GROUP BY t, remote_addr_hashed\n    ),\n    action_ips as\n    (\n    SELECT DISTINCT toUInt32(toStartOfHour(date)) * 1000 as t, remote_addr_hashed\n    FROM default.http_access_nns_dapp\n    WHERE date >= toDateTime(1690817010) AND date <= toDateTime(1691421810)\n    AND http_origin == ORIGIN\n    AND ic_method_name IN RELEVANT_ACTION\n    GROUP BY t, remote_addr_hashed\n    )\nSELECT t, num_no_action / num_page_loads as bounce_rate\nFROM (\n         \n         SELECT t, count(DISTINCT remote_addr_hashed) as num_no_action\n         FROM page_load_ips LEFT JOIN action_ips ON page_load_ips.remote_addr_hashed == action_ips.remote_addr_hashed\n         WHERE action_ips.remote_addr_hashed == ''\n         GROUP BY t\n     ) as no_action_count  INNER JOIN\n     (\n         \n         SELECT t, count(DISTINCT remote_addr_hashed) as num_page_loads\n         FROM\n             (\n                 SELECT t, remote_addr_hashed\n                 FROM action_ips\n                 UNION DISTINCT\n                 SELECT t, remote_addr_hashed\n                 FROM page_load_ips\n             )\n         GROUP BY t\n     ) as all_count ON no_action_count.t == all_count.t\nORDER BY t",
     "round": "0s",
     "table": "http_access_nns_dapp"
    }
   ]
  },
  {
   "title": "Accounts created rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "accounts / day" }
   ],
   "targets": [
    {
     "expr": "rate(accounts_count{job=\"nns-dapp-canister\"}[24h]) * 86400",
     "legendFormat": "accounts"
    }
   ]
  },
  {
   "title": "NNS dapp accounts",
   "type": "graph",
   "description": "Total number of main accounts created in NNS dapp.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Total accounts" }
   ],
   "targets": [
    { "expr": "accounts_count", "legendFormat": "accounts" }
   ]
  },
  {
   "title": "Subaccounts created rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "subaccounts / day" }
   ],
   "targets": [
    {
     "expr": "rate(sub_accounts_count{job=\"nns-dapp-canister\"}[24h]) * 86400",
     "legendFormat": "ICP transactions"
    }
   ]
  },
  {
   "title": "Subaccounts",
   "type": "graph",
   "description": "Total number of subaccounts created in NNS dapp.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Total subaccounts" }
   ],
   "targets": [
    { "expr": "accounts_count", "legendFormat": "ICP transactions" }
   ]
  },
  {
   "title": "Hardware wallets attached rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "HW wallets / day" }
   ],
   "targets": [
    {
     "expr": "rate(hardware_wallet_accounts_count{job=\"nns-dapp-canister\"}[24h]) * 86400",
     "legendFormat": "ICP transactions"
    }
   ]
  },
  {
   "title": "Hardware wallets attached",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Total HW wallets" }
   ],
   "targets": [
    { "expr": "hardware_wallet_accounts_count", "legendFormat": "ICP transactions" }
   ]
  },
  {
   "title": "Heap memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "GiB" }
   ],
   "targets": [
    { "expr": "nns_dapp_wasm_memory_size_gib", "legendFormat": "ICP transactions" }
   ]
  },
  {
   "title": "Stable memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "nns_dapp_stable_memory_size_gib",
     "legendFormat": "ICP transactions"
    }
   ]
  },
  {
   "title": "Hardware wallets per account",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "HW wallets / account" }
   ],
   "targets": [
    {
     "expr": "hardware_wallet_accounts_count / accounts_count",
     "legendFormat": "ICP transactions"
    }
   ]
  }
 ]
}