{
 "title": "Query Stats",
 "description": "Query Stats Feature Dashboard",
 "tags": [ "production" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "IC", "query": "prometheus" },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{ic=\"$ic\",job=\"replica\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   },
   { "name": "period", "label": "Aggregation period", "query": "20s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "ic",
    "label": "IC",
    "query": {
     "query": "label_values(up{job=\"replica\"}, ic)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Finalization Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"} != 0,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "graph",
   "description": "Current epoch reported by different query stats components",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  quantile by(ic_subnet, job) (\n    0.5,\n    query_stats_collector_current_epoch{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\", job=\"replica\"}\n  ),\n  \"ic_subnet\", \"$1 (collector)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    },
    {
     "expr": "label_replace(\n  quantile by(ic_subnet, job) (\n    0.5,\n    query_stats_payload_builder_current_epoch{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\", job=\"replica\"}\n  ),\n  \"ic_subnet\", \"$1 (payload builder)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    },
    {
     "expr": "label_replace(\n  quantile by(ic_subnet, job) (\n    0.5,\n    query_stats_aggregator_current_epoch{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\", job=\"replica\"}\n  ),\n  \"ic_subnet\", \"$1 (aggregator)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  },
  {
   "title": "Number of Canister Statistics",
   "type": "graph",
   "description": "Number of unique canister ids that the different components have stored data for.\nNote: The aggregator can store data for the same canister for multiple epochs, and might therefore have more canister statistics than exist on the subnet.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  sum by(ic_subnet, job) (\n    query_stats_collector_num_canister_ids{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\", job=\"replica\"}\n  ),\n  \"ic_subnet\", \"$1 (collector)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    },
    {
     "expr": "label_replace(\n  sum by(ic_subnet, job) (\n    query_stats_payload_builder_num_canister_ids{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\", job=\"replica\"}\n  ),\n  \"ic_subnet\", \"$1 (payload builder)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    },
    {
     "expr": "label_replace(\n  quantile by(ic_subnet, job) (\n    0.5,\n    query_stats_aggregator_num_records{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\", job=\"replica\"}\n  ),\n  \"ic_subnet\", \"$1 (aggregator)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  },
  {
   "title": "Delivery",
   "type": "timeseries",
   "description": "Presents the sum of instructions, as delivered by various components onwards through the feature.\nThe order is:\nCollector -> Payload Builder -> Aggregator -> Delivered.\nThe Execution metric is what Execution reports and might be subject to different calculations than the rest of the components.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by(ic_subnet) (\n      increase(query_stats_delivered_num_instructions{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[12h])\n    )\n  ,\n  \"ic_subnet\", \"$1 (delivery)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    },
    {
     "expr": "label_replace(\n    sum by(ic_subnet) (\n      increase(execution_query_instructions_sum{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[12h])\n    )\n  ,\n  \"ic_subnet\", \"$1 (execution)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    sum by(ic_subnet) (\n      increase(query_stats_collector_num_instructions{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[12h])\n    )\n  ,\n  \"ic_subnet\", \"$1 (collector)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    sum by(ic_subnet) (\n      increase(query_stats_payload_builder_current_num_instructions{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[12h])\n    )\n  ,\n  \"ic_subnet\", \"$1 (payload builder)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    quantile by(ic_subnet) (\n      0.5,\n      increase(query_stats_aggregator_received_num_instructions{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[12h])\n    )\n  ,\n  \"ic_subnet\", \"$1 (aggregator)\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Empty Stats Ratio",
   "type": "timeseries",
   "description": "Ratio of empty stats with respect to the total number of stats. A number close to 0 indicates good data quality and indicates that the reported metrics are accurate. A value close to 1 indicates that the available data is very lean and the reported metrics might be inaccurate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by(ic_subnet) (\n      increase(query_stats_empty_stats_aggregated{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[12h])\n    ) / \n    sum by(ic_subnet) (\n      increase(query_stats_total_aggregated{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[12h])\n    )\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  },
  {
   "title": "Undercounting Ratio",
   "type": "timeseries",
   "description": "The ratio between the instructions received at the collector with respect to the instructions delivered to the canisters minus one.\nA value close to 0 indicates good data quality. A positive value indicates undercounting.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by(ic_subnet) (\n      increase(query_stats_collector_num_instructions{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[12h])\n    ) /\n    sum by(ic_subnet) (\n      increase(query_stats_delivered_num_instructions{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[12h])\n    ) - 1\n  ,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([a-z0-9]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  }
 ]
}