{
 "title": "XNet",
 "tags": [ "production" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ic",
    "label": "IC",
    "query": {
     "query": "label_values(up{job=\"replica\"}, ic)"
    }
   },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\"}, ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   },
   {
    "name": "build_status",
    "label": "Build status",
    "query": {
     "query": "label_values(xnet_builder_build_payload_duration_seconds_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}, status)"
    }
   },
   {
    "name": "query_status",
    "label": "Query status",
    "query": {
     "query": "label_values(xnet_builder_query_slice_duration_seconds_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}, status)"
    }
   },
   {
    "name": "period",
    "label": "Aggregation period",
    "query": "20s,30s,1m,2m,5m,10m,30m,1h,3h,6h,12h,1d"
   },
   {
    "name": "heatmap_period",
    "label": "Heatmap aggregation period",
    "query": "20s,30s,1m,2m,5m,10m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Cumulative Stream Sizes, by Subnet",
   "type": "timeseries",
   "description": "Median across replicas in a subnet of the total number of messages across all outgoing streams.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n  quantile by (ic, ic_subnet) (\n    0.5,\n    sum without(destination, remote) (mr_stream_messages{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"})\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  },
  {
   "title": "Induct XNet Message Attempts per Second, by Status",
   "type": "timeseries",
   "description": "Averaged over **$period** (configurable).\n\nSum by induction status of per-subnet median inducted requests and responses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(ic, status) (\n    quantile by(ic, ic_subnet, type, status) (\n        0.5,\n        rate(mr_inducted_xnet_message_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])\n    )\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Payload Builder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "XNet Payloads Built per Second, by Subnet",
   "type": "timeseries",
   "description": "Averaged over **$period** (configurable).\n\nThe absolute value depends on how many replicas are selected by Consensus to build blocks, but should be relatively constant over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by(ic, ic_subnet) (\n    rate(xnet_builder_build_payload_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=~\"$build_status\"}[$period])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    },
    {
     "expr": "label_replace(\n  quantile by(ic, ic_subnet) (\n    .5,\n    rate(artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"}[$period])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "Finalization {{ic_subnet}}"
    }
   ]
  },
  {
   "title": "XNet Payload Building Duration, Aggregated",
   "type": "heatmap",
   "description": "XNet payload building duration distribution across selected subnets, aggregated over **$heatmap_period**.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (\n  avg by(le, ic_subnet) (\n    increase(xnet_builder_build_payload_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=~\"$build_status\"}[$heatmap_period])\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "XNet Payloads Built per Second, by Status",
   "type": "timeseries",
   "description": "Averaged over **$period** (configurable).\n\nThe absolute value depends on how many replicas are selected by Consensus to build blocks, but should be relatively constant over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(ic, status) (rate(xnet_builder_build_payload_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=~\"$build_status\"}[$period]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "XNet Payload Building Duration 90th Percentile, by Status",
   "type": "timeseries",
   "description": "XNet payload building duration 90th percentile by status, across selected subnets.\n\nAveraged over **$period** (configurable).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.9, sum by(ic, status, le) (rate(xnet_builder_build_payload_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=~\"$build_status\"}[$period])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Payload Builder: Pulls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "XNet Pull Attempts per Second, by Subnet",
   "type": "timeseries",
   "description": "Averaged over **$period** (configurable).\n\nThe absolute value depends on how many replicas are selected by Consensus to build blocks, but should be relatively constant over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by(ic, ic_subnet) (\n    rate(xnet_builder_pull_attempt_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  },
  {
   "title": "XNet Pull Attempts per Second, by Status",
   "type": "timeseries",
   "description": "Averaged over **$period** (configurable).\n\nThe absolute value depends on how many replicas are selected by Consensus to build blocks, but should be relatively constant over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(ic, status) (rate(xnet_builder_pull_attempt_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "XNet Queries per Second, by Subnet",
   "type": "timeseries",
   "description": "Averaged over **$period** (configurable).\n\nThe absolute value depends on how many replicas are selected by Consensus to build blocks, but should be relatively constant over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by(ic, ic_subnet) (\n    rate(xnet_builder_query_slice_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=~\"$query_status\"}[$period])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  },
  {
   "title": "XNet Queries per Second, by Status",
   "type": "timeseries",
   "description": "Averaged over **$period** (configurable).\n\nThe absolute value depends on how many replicas are selected by Consensus to build blocks, but should be relatively constant over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(ic, status) (rate(xnet_builder_query_slice_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=~\"$query_status\"}[$period]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "XNet Query Duration 90th Percentile, by Status",
   "type": "timeseries",
   "description": "XNet query duration 90th percentile by status, across selected subnets.\n\nAveraged over **$period** (configurable).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.9, sum by(ic, status, le) (rate(xnet_builder_query_slice_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=~\"$query_status\"}[$period])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "XNet Query Duration, Aggregated",
   "type": "heatmap",
   "description": "XNet query duration distribution across selected subnets, aggregated over **$heatmap_period**.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (le) (\n  avg by(le, ic_subnet) (\n    increase(xnet_builder_query_slice_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=~\"$query_status\"}[$heatmap_period])\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "XNet Response Size",
   "type": "heatmap",
   "description": "Response byte size, as measured by `XNetPayloadBuilder`, aggregated over **$heatmap_period**.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by (le) (\n  avg by(le, ic_subnet) (\n    increase(xnet_builder_response_body_size_bytes_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=\"success\"}[$heatmap_period])\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "XNet Payload Size",
   "type": "heatmap",
   "description": "Response payload (encoded stream slice) byte size, as measured by `XNetEndpoint`, aggregated over **$heatmap_period**.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by (le) (\n  avg by(le, ic_subnet) (\n    increase(xnet_builder_slice_payload_size_bytes_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "XNet Endpoint QPS, by Subnet",
   "type": "timeseries",
   "description": "Averaged over **$period** (configurable).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by(ic, ic_subnet,resource) (\n    rate(xnet_endpoint_request_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} {{resource}}"
    }
   ]
  },
  {
   "title": "XNet Endpoint Query Duration, Aggregated",
   "type": "heatmap",
   "description": "XNet endpoint query duration distribution across selected subnets, aggregated over **$heatmap_period**.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum by (le) (\n  avg by(le, ic_subnet) (\n    increase(xnet_endpoint_request_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",resource=\"stream\"}[$heatmap_period])\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "XNet Endpoint QPS, by Status",
   "type": "timeseries",
   "description": "Averaged over **$period** (configurable).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(ic, status, resource) (rate(xnet_endpoint_request_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period]))",
     "legendFormat": "/{{resource}} {{status}}"
    }
   ]
  },
  {
   "title": "XNet Endpoint Query Duration 90th Percentile, by Status",
   "type": "timeseries",
   "description": "XNet endpoint query duration 90th percentile by status, across selected subnets.\n\nAveraged over **$period** (configurable).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.9, sum by(ic, status, le, resource) (rate(xnet_endpoint_request_duration_seconds_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period])))",
     "legendFormat": "/{{resource}} {{status}}"
    }
   ]
  },
  {
   "title": "Throughput, by Subnet",
   "type": "timeseries",
   "description": "`/stream` responses and bytes per second, averaged over **$period** (configurable).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by(ic, ic_subnet) (\n    rate(xnet_endpoint_response_size_bytes_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",resource=\"stream\"}[$period])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} bytes out"
    },
    {
     "expr": "label_replace(\n  sum by(ic, ic_subnet) (\n    rate(xnet_builder_response_body_size_bytes_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=\"success\"}[$period])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} bytes in"
    },
    {
     "expr": "label_replace(\n  sum by(ic, ic_subnet) (\n    rate(xnet_endpoint_response_size_bytes_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",resource=\"stream\"}[$period])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} responses out"
    },
    {
     "expr": "label_replace(\n  sum by(ic, ic_subnet) (\n    rate(xnet_builder_response_body_size_bytes_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=\"success\"}[$period])\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} responses in"
    }
   ]
  },
  {
   "title": "Response Overhead, by Subnet",
   "type": "timeseries",
   "description": "`/stream` payload overhead (certification, witness) in bytes and as a percentage, averaged over **$period** (configurable).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\nclamp_min(\n  (\n    sum by(ic, ic_subnet) (rate(xnet_endpoint_response_size_bytes_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",resource=\"stream\"}[$period]))\n  /\n    sum by(ic, ic_subnet) (rate(xnet_endpoint_response_size_bytes_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",resource=\"stream\"}[$period]))\n  )\n-\n  (\n    sum by(ic, ic_subnet) (rate(xnet_endpoint_slice_payload_size_bytes_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period]))\n  /\n    sum by(ic, ic_subnet) (rate(xnet_endpoint_slice_payload_size_bytes_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period]))\n  ),\n0\n),\n\"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} (bytes)"
    },
    {
     "expr": "label_replace(\nclamp_min(\n  1 -\n    (\n      sum by(ic, ic_subnet) (rate(xnet_endpoint_slice_payload_size_bytes_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period]))\n    /\n      sum by(ic, ic_subnet) (rate(xnet_endpoint_slice_payload_size_bytes_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period]))\n    )\n  /\n    (\n      sum by(ic, ic_subnet) (rate(xnet_endpoint_response_size_bytes_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",resource=\"stream\"}[$period]))\n    /\n      sum by(ic, ic_subnet) (rate(xnet_endpoint_response_size_bytes_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",resource=\"stream\"}[$period]))\n    ),\n  0\n),\n\"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}} (ratio)"
    }
   ]
  },
  {
   "title": "XNet Endpoint Response Size",
   "type": "heatmap",
   "description": "Response byte size, as measured by `XNetEndpoint`, aggregated over **$heatmap_period**.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum by (le) (\n  avg by(le, ic_subnet) (\n    increase(xnet_endpoint_response_size_bytes_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",resource=\"stream\"}[$heatmap_period])\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "XNet Endpoint Payload Size",
   "type": "heatmap",
   "description": "Response payload (encoded stream slice) byte size, as measured by `XNetEndpoint`, aggregated over **$heatmap_period**.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "sum by (le) (\n  avg by(le, ic_subnet) (\n    increase(xnet_endpoint_slice_payload_size_bytes_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "XNet Message Time in Stream",
   "type": "heatmap",
   "description": "Distribution of durations spent by XNet messages in streams (between routing and GC) across selected subnets, aggregated over **$heatmap_period**.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum by (le) (\n  quantile without(ic_node, instance) (\n    0.5,\n    sum without(remote) (\n      increase(mr_time_in_stream_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "XNet Message Time in Backlog",
   "type": "heatmap",
   "description": "Distribution of times between finding out about the existence of a message (from the stream header) and its induction across selected subnets, aggregated over **$heatmap_period**.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "sum by (le) (\n  quantile without(ic_node, instance) (\n    0.5,\n    sum without(remote) (\n      increase(mr_time_in_backlog_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$heatmap_period])\n    )\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Speculative",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dropped XNet Responses",
     "type": "heatmap",
     "description": "Difference between the response byte size distributions, measured by `XNetEndpoint` and `XNetPayloadBuilder`. Aggregated over **$heatmap_period**.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "sum by (le) (\n  avg by(le, ic_subnet) (\n    increase(xnet_endpoint_response_size_bytes_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",resource=\"stream\"}[$heatmap_period])\n  )\n)\n-\nsum by (le) (\n  avg by(le, ic_subnet) (\n    increase(xnet_builder_response_body_size_bytes_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\",status=\"success\"}[$heatmap_period])\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}