= The ckBTC Minter Canister +


The ckBTC Minter canister converts BTC to ckBTC and back.
It works with a link:../../../rosetta-api/icrc1/README.md[Ledger Canister], handling the _ckBTC_ token transfers, and a link:../../canister/README.adoc[Bitcoin Canister], interfacing with the Bitcoin network.
The ckBTC Minter canister is a https://github.com/dfinity/ICRC-1/blob/8c526e1dae38622eb0940643996e8187d2063513/standards/ICRC-1/README.md#minting-account-[minter] for the ckBTC Ledger canister: it can mint and burn ckBTC tokens.

== Interact with the ckBTC minter
To interact with the testnet bitcoin minter please move to rs/bitcoin/ckbtc/testnet.

=== Bitcoin to ckBTC
```
 ┌────┐         ┌──────┐┌──────────────┐
 │User│         │Minter││BitcoinNetwork│
 └─┬──┘         └──┬───┘└──────┬───────┘
   │               │           │        
   │get_btc_address│           │        
   │──────────────>│           │        
   │               │           │        
   │    address    │           │        
   │<──────────────│           │        
   │               │           │        
   │    Send BTC to address    │        
   │──────────────────────────>│        
   │               │           │        
   │update_balance │           │        
   │──────────────>│           │        
 ┌─┴──┐         ┌──┴───┐┌──────┴───────┐
 │User│         │Minter││BitcoinNetwork│
 └────┘         └──────┘└──────────────┘
```

1. Obtain the deposit address:
+
----
dfx canister --network ic call minter get_btc_address "(record {subaccount=null;})"
----
+
2. Send bitcoin to the BTC address the minter gave you.
3. Wait until your Bitcoin transaction got enough confirmations.
   Mainnet ckBTC can require up to 72 confirmations, corresponding to a 12-hour waiting period on average.
4. Notify the minter about the transfer.
+
----
dfx canister --network ic call minter update_balance "(record {subaccount=null;})"
----
+

You now have some ckBTC, you can enjoy the Internet Computer speed and low fees!

If you would like to transfer them to your wallet (plug, stoic, ...), copy the principal of your wallet and paste it over PRINCIPAL and change AMOUNT to the desired amount (in satoshis) in the following command:
----
dfx canister --network ic call ledger icrc1_transfer "(record { to = record { owner = principal "PRINCIPAL" }; amount = AMOUNT; })"
----
If you want to override the default transfer arguments (for more information on the supported parameters, see the https://github.com/dfinity/ICRC-1/blob/main/standards/ICRC-1/README.md[ICRC-1 Token Standard]), you can modify the following command: 
----
dfx canister --network ic call ledger icrc1_transfer "(record { from_subaccount = null; to = record { owner = principal "PRINCIPAL"; subaccount = null; }; amount = AMOUNT; fee = null; memo = null; created_at_time = null;})"
----

=== ckBTC to Bitcoin
```
 ┌────┐    ┌────────────┐         ┌──────┐                  ┌───────────────┐
 │User│    │ckBTC Ledger│         │Minter│                  │Bitcoin Network│
 └─┬──┘    └─────┬──────┘         └──┬───┘                  └───────┬───────┘
   │             │                   │                              │        
   │icrc2_approve│                   │                              │        
   │────────────>│                   │                              │        
   │             │                   │                              │        
   │   retrieve_btc_with_approval    │                              │        
   │────────────────────────────────>│                              │        
   │             │                   │                              │        
   │             │icrc2_transfer_from│                              │        
   │             │<──────────────────│                              │        
   │             │                   │                              │        
   │             │                   │Send BTC to withdrawal address│        
   │             │                   │─────────────────────────────>│        
 ┌─┴──┐    ┌─────┴──────┐         ┌──┴───┐                  ┌───────┴───────┐
 │User│    │ckBTC Ledger│         │Minter│                  │Bitcoin Network│
 └────┘    └────────────┘         └──────┘                  └───────────────┘
```
1. Approve the minter's principal:
+
----
dfx canister --network ic call ledger icrc2_approve "(record {spender=record{owner=principal \"mqygn-kiaaa-aaaar-qaadq-cai\"}; amount=AMOUNT})"
----
+
2. Call the `retrieve_btc_with_approval` endpoint with the desired BTC destination address where you want to receive your Bitcoin.
   Replace BTC_ADDRESS with your BTC address (the minter supports all address formats).
   Replace AMOUNT with the amount that you transferred minus the transfer fee of 0.0000001 ckBTC (the equivalent of 10 Satoshi).
+
----
dfx canister --network ic call minter retrieve_btc_with_approval "(record {address=\"BTC_ADDRESS\"; amount=AMOUNT;})"
----
+
You now have your BTC back on the Bitcoin network (caution: transaction finalization may take a while).

[NOTE]
====
You can query the status of your `retrieve_btc_with_approval` request using the following command (replace `BLOCK_INDEX` with the block index you get when calling retrieve_btc): 
----
dfx canister --network ic call minter retrieve_btc_status "(record { block_index = BLOCK_INDEX; })"
----
====

=== ckBTC to Bitcoin (old flow)
```
 ┌────┐                ┌──────┐┌────────────┐    ┌───────────────┐
 │User│                │Minter││ckBTC ledger│    │Bitcoin Network│
 └─┬──┘                └──┬───┘└─────┬──────┘    └───────┬───────┘
   │                      │          │                   │        
   │get_withdrawal_account│          │                   │        
   │─────────────────────>│          │                   │        
   │                      │          │                   │        
   │       account        │          │                   │        
   │<─────────────────────│          │                   │        
   │                      │          │                   │        
   │     icrc1_transfer(account)     │                   │        
   │────────────────────────────────>│                   │        
   │                      │          │                   │        
   │     retrieve_btc     │          │                   │        
   │─────────────────────>│          │                   │        
   │                      │          │                   │        
   │                      │Send BTC to withdrawal address│        
   │                      │─────────────────────────────>│        
 ┌─┴──┐                ┌──┴───┐┌─────┴──────┐    ┌───────┴───────┐
 │User│                │Minter││ckBTC ledger│    │Bitcoin Network│
 └────┘                └──────┘└────────────┘    └───────────────┘
```

1. Obtain the withdrawal address and store it in a variable.
+
----
withdrawal_address=$(dfx canister --network ic call minter get_withdrawal_account)
----
+
2. Clean the output of the previous command to get the desired format:
+
----
cleaned_withdrawal_address="$(printf "%s\n" "$withdrawal_address" | sed -re 's/^\(|,|\)$//g')"
----
+
3. Transfer the ckBTCs you want to convert, to *cleaned_withdrawal_address* on the ckBTC ledger.
   Replace AMOUNT with the amount that you want to convert.
+
----
dfx canister --network ic call ledger icrc1_transfer "(record {from=null; to=$cleaned_withdrawal_address; amount=AMOUNT; fee=null; memo=null; created_at_time=null;})"
----
+
4. Call the `retrieve_btc` endpoint with the desired BTC destination address where you want to receive your Bitcoin.
   Replace BTC_ADDRESS with your BTC address (the minter supports all address formats).
   Replace AMOUNT with the amount that you transferred minus the transfer fee of 0.0000001 ckBTC (the equivalent of 10 Satoshi).
+
----
dfx canister --network ic call minter retrieve_btc "(record {address=\"BTC_ADDRESS\"; amount=AMOUNT})"
----

You now have your BTC back on the Bitcoin network (caution: transaction finalization may take a while). 

=== Ledger Memos

All ckBTC transactions issued by the ckBTC minter and recorded on the ledger use a memo field to store additional information about the transaction. The ckBTC minter records a transaction on the ledger in the following cases:

. minting ckBTC after a deposit of BTC,
. burning ckBTC after a withdrawal request to BTC,
. minting ckBTC to reimburse a failed withdrawal or to pay the kyt fees.

=== Design
The general idea is to encode the memo as a https://cbor.io/[CBOR] message and use the transaction type to select the message type. The messages will follow the compact encoding described in the https://twittner.gitlab.io/minicbor/minicbor_derive/index.html[minicbor] package documentation with the following https://datatracker.ietf.org/doc/html/rfc8610[CDDL] schema:

.Example Implementation in Typescript
====
There is an example implementation of how to decode the ckBTC ledger memos in Typescript in the https://github.com/dfinity/oisy-wallet/tree/main[Oisy Wallet] repository:

* https://github.com/dfinity/oisy-wallet/blob/384013a67a994555b6bd1cd6baeba0a83c444839/src/frontend/src/icp/utils/ckbtc-memo.utils.ts[Decode ckBTC ledger burn and mint memo]
* https://github.com/dfinity/oisy-wallet/blob/384013a67a994555b6bd1cd6baeba0a83c444839/src/frontend/src/tests/icp/utils/ckbtc-memo.utils.spec.ts[Tests to decode ckBTC ledger memo]
====