#!/bin/sh
mkdir -p -m 755 /etc/prometheus
for name in replica orchestrator node_exporter; do
  echo '[]' > "/etc/prometheus/$name.json"
done

mkdir -p /config/grafana/dashboards

if uname -a | grep -q Ubuntu; then
  # k8s
  chmod g+s /etc/prometheus
  cp -f /config/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
  cp -R /config/grafana/dashboards /var/lib/grafana/
  chown -R grafana:grafana /var/lib/grafana/dashboards
  chown -R admin:prometheus /etc/prometheus
  systemctl reload prometheus
else
  # farm
  chown -R admin:users /etc/prometheus
fi
