"""
Enumerate every rootfs file dependency for SetupOS
"""

rootfs_files = {
    Label("etc/default/locale"): "/etc/default/locale",
    Label("etc/fstab"): "/etc/fstab",
    Label("etc/hostname"): "/etc/hostname",
    Label("etc/hosts"): "/etc/hosts",
    Label("etc/initramfs-tools/initramfs.conf"): "/etc/initramfs-tools/initramfs.conf",
    Label("etc/resolv.conf"): "/etc/resolv.conf",
    Label("etc/systemd/resolved.conf.d/fallback.conf"): "/etc/systemd/resolved.conf.d/fallback.conf",
    Label("etc/systemd/system-generators/systemd-gpt-auto-generator"): "/etc/systemd/system-generators/systemd-gpt-auto-generator",
    Label("etc/systemd/system/config.service"): "/etc/systemd/system/config.service",
    Label("etc/systemd/system/generate-network-config.service"): "/etc/systemd/system/generate-network-config.service",
    Label("etc/systemd/system/serial-getty@.service"): "/etc/systemd/system/serial-getty@.service",
    Label("etc/systemd/system/setupos.service"): "/etc/systemd/system/setupos.service",
    Label("opt/ic/bin/config.sh"): "/opt/ic/bin/config.sh",
    Label("opt/ic/bin/devices.sh"): "/opt/ic/bin/devices.sh",
    Label("opt/ic/bin/disk.sh"): "/opt/ic/bin/disk.sh",
    Label("opt/ic/bin/fetch-property.sh"): "/opt/ic/bin/fetch-property.sh",
    Label("opt/ic/bin/functions.sh"): "/opt/ic/bin/functions.sh",
    Label("opt/ic/bin/guestos.sh"): "/opt/ic/bin/guestos.sh",
    Label("opt/ic/bin/hardware.sh"): "/opt/ic/bin/hardware.sh",
    Label("opt/ic/bin/hostos.sh"): "/opt/ic/bin/hostos.sh",
    Label("opt/ic/bin/network.sh"): "/opt/ic/bin/network.sh",
    Label("opt/ic/bin/output-wrapper.sh"): "/opt/ic/bin/output-wrapper.sh",
    Label("opt/ic/bin/setupos.sh"): "/opt/ic/bin/setupos.sh",
    Label("prep/fscontext-fixes/fscontext-fixes.fc"): "/prep/fscontext-fixes/fscontext-fixes.fc",
    Label("prep/fscontext-fixes/fscontext-fixes.if"): "/prep/fscontext-fixes/fscontext-fixes.if",
    Label("prep/fscontext-fixes/fscontext-fixes.te"): "/prep/fscontext-fixes/fscontext-fixes.te",
    Label("prep/misc-fixes/misc-fixes.if"): "/prep/misc-fixes/misc-fixes.if",
    Label("prep/misc-fixes/misc-fixes.te"): "/prep/misc-fixes/misc-fixes.te",
    Label("prep/prep.sh"): "/prep/prep.sh",
    Label("prep/systemd-fixes/systemd-fixes.if"): "/prep/systemd-fixes/systemd-fixes.if",
    Label("prep/systemd-fixes/systemd-fixes.te"): "/prep/systemd-fixes/systemd-fixes.te",
}
