= SEV Trusted Execution

== SEV Keys

=== ARK
ARK is the AMD Root key which is an RSA 2048 key pair. It is the root of trust of AMD and its signatures signify AMD authenticity. The public part is stored in the VM as a constant.


=== ASK
ASK is the AMD SEV Signing Key (ASK), which is signed by the AMD root signing key (ARK). There is a different key for each hardware series, e.g., for Milan, Rome and Naples link:https://developer.amd.com/sev/[sev]. At best it comes from the host level so the VM does not need to know it just gets the right one depending on the platform from the host and checks if it is signed by the hardcoded ARK.


=== VCEK
VCEK is the Versioned Chip Endorsement Key (VCEK). It is specific to the firmware of the secure processor of the platform and the chip_id. It is signed by the ASK of the platform


== References

=== AMD Keyserver Interface

There are additional details about the AMD keyserver interface where one can get the VCEK here link:https://www.amd.com/system/files/TechDocs/57230.pdf[techdoc].

