= IC Boundary Node Guest OS boot sequence

The system boot starts with the initramfs which performs some preparatory
operations already. It takes a first look at the `/config` filesystem to
load a machine-id file if it exists. If it is found, then it is bind-mounted
on top of the root filesystem to provide the machine-id in subsequent boot
(and which would otherwise be randomly generated by systemd once it takes
over). This ensures stability of machine-id after first boot.

After switch to the proper root filesystem, the following essential IC-specific
service are started in the IC-OS boot sequence:

- Mount `/boot` filesystems (including `/boot/config`)

- Save machine-id

- Set up ssh host keys

- Set up node exporter keys

- Config injection

- Set up ssh account keys

- Generate network configuration

- Set up hostname

- IPv6 address monitor / retry

- Start journalbeat

- Start node exporter

- Start nginx

- Start boundary-node-control-plane

- Start ic_router_control_plane_watcher

- Start icx_proxy

- Start danted socks-proxy

== Mount `/boot` filesystems

The partition used to be mounted as `/boot` depends on the partition
set that we are booting from (see link:DiskLayout{outfilesuffix}[disk layout]
for description of partition layout). The mount description for `/boot` is therefore
not held in `/etc/fstab` but is generated by the shell script
`/etc/systemd/system-generators/mount-generator`.

Afterwards, the first three partitions are mounted as `/boot/efi`, `/boot/grub`
and `/boot/config`, respectively. The `config` partition is
used as (small) store for data that is preserved across upgrades
and is available at early boot time already (see link:ConfigStore{outfilesuffix}[config store]).

== Save machine-id

Relevant information can be found in the guestos link:../../guestos/doc/Boot.adoc#_save_machine_id[documentation].

== Set up ssh host keys

Service: `setup-ssh-keys.service`, script: `/opt/ic/bin/setup-ssh-keys.sh`,
depends on `/boot/config` mount.

This checks if ssh host keys for the system exist in the `config` partition
(creating them if necessary -- only on first boot after deployment). The
keys are then copied to tmpfs and bind-mounted to `/etc/ssh`. Keeping
host keys in the `config` partition ensures that they are stable across
system upgrades.

== Set up node exporter keys

Service: `setup-node_exporter-keys.service`, script `/opt/ic/bin/setup-node_exporter-keys.sh`,
depends on `/boot/config` mount.

This generates the TLS key pair for the `node_exporter` service on first boot.
The keys are then bind-mounted into a suitable location within `/etc`.

Similar to the ssh keys, the keys are held in the `config` partition such that
they are persisted across upgrades and available in early boot.

== IC boundary node config injection

Service: `bootstrap-ic-node.service`, script `/opt/bin/ic/boostrap-ic-node.sh`,
depends on mount of all filesystems.

This is only executed once on first boot after provisioning. It looks for a "virtual
USB stick" attached to the VM that contains a tar file with initial configuration
for parts of the system (see link:ConfigStore{outfilesuffix}[config store] for a description). Required
files in the `config` partition as well as payload store are created.

== Set up ssh account keys

Service: `setup-ssh-account-keys.services`, script `/opt/ic/bin/setup-ssh-account-keys.sh`.
Depends on `bootstrap-ic-node.service`.

The `authorized_keys` files for the role accounts are taken from the
config partition and bind-mounted into the correct locations in
the account user home directories.

== Generate network configuration

Service: `generate-network-config.service`, script `/opt/ic/bin/generate-network-config.sh`.
Depends on `bootstrap-ic-node.service`, runs before `systemd-networkd.service`.

This parses the network configuration given in the `config` partition and
generates network configuration directives for `systemd-networkd` to apply
later.

== Set up hostname

Service:  `generate-network-config.service`, script  `/opt/ic/bin/generate-network-config.sh `.
Depends on `bootstrap-ic-node.service`, runs before  `systemd-networkd.service `.

Sets hostname as defined in the `config` partition.

== IPv6 address monitor / retry

Service: `retry-ipv6-config.service`, script `/opt/ic/bin/retry-ipv6-config.sh`.

Periodically checks whether an IPv6 address has been assigned to the primary
interface and issues `networkctl reconfigure` as needed. The reason is that
`systemd-networkd` gives up on trying SLAAC autoconfiguration after a while,
so systems will fail to receive network configuration under certain conditions
if the router in their network is down at boot.

== Start journalbeat

Service: `journalbeat.service`. Pre-exec script `/opt/ic/bin/generate-journalbeat-config.sh`.
Depends on `bootstrap-ic-node.service`.

This launches journalbeat (if requested so by injected configuration). The configuration
for the binary itself is generated dynamically from the configuration pieces held
in the `config` partition.

== Start node_exporter

Service: `node_exporter.service`. Depends on `setup-node_exporter-keys.service`.

Starts the `node_exporter` service to make machine metrics accessible externally.

==  Start nginx

Service: `nginx.service`

Default starter script that comes with the package. Relevant information is here: `nginx.service.d/override.conf` and in `/etc/nginx`


==  Start boundary-node-control-plane

Service:  `boundary-node-control-plane.service`. Has a pre-execution phase that extracts the NNS URLs from `/boot/config/nns.conf`

Generates JSON with routing tables, IP:port, node certificates these are stored in `/etc/nginx/ic_routes`

==  Start ic_router_control_plane_watcher
Service: `ic-router-control-plane-watcher.service`

Starts `/etc/nginx/ic/ic_router_control_plane_watcher.sh`, which on chnage collects information from `/etc/nginx/ic_routes` and feeds them into `ic_router_control_plane.py` which produces `ic_router_table.js`
that is usd by the njs-plugin of nginx to route requests to the IC.

==  Start icx_proxy

Service: icx-proxy.service

- TODO BOUN-179

==  Start danted socks-proxy

Service: danted.service

- TODO BOUN-179

