= Boundary Node Guest OS Components

The Boundary Node has a number of specific components:

== Nginx and `ic_router.js`
Nginx is used to serve assets such as the service worker, it acts as a proxy that dispatches requests to the IC and performs rate limiting. Nginx is extended by two modules

- link:https://nginx.org/en/docs/njs/[njs] which provides a subset of the JavaScript language that allows extending nginx functionality
- Support for cbor parsing via link:https://github.com/dfinity/nginx-module-cbor-input[nginx-module-cbor-input]

In particular njs is used to for the link:../rootfs/etc/nginx/ic_router.js[`ic_router.js`]. The router maps a   `canister_id`  to a `subnet_id` and for the subnet to a `node_id`.

== `icx-proxy`
Transforms HTTP-to-canister request as API calls.
More details can be found link:https://github.com/dfinity/icx-proxy[here].

== `boundary-node-control-plane`
- Contacts NNS and caches registry data and watches for changes
- Heartbeats all nodes, moves down nodes from routing tables in case they are not reachable
- Generates JSON with routing tables, IP:port, node certificates

== `ic_router_control_plane_watcher.sh`
- Shell script that watches for NNS registry changes for routing (i.e., JSON file changes
 preformed by the boundary-node-control-plane), starts the `ic-router-control-plane.py` script.

== `ic-router-control-plane.py`
- Python script that reads JSON files generated by `boundary-node-control-plane` containing /routes/
- Generates `ic_router_tables.js` used by ic_router.js
- Generates `nginx_tables.conf` with “upstream” declarations

== Service worker
JS script that is delivered to the browser to transform plain HTTP requests into API requests

== Prober
- Creates canisters that are probed
- Performs dynamic probes and export the results to Prometheus

== Socks proxy
- TODO BOUN-179

== Dante socks-proxy

- TODO BOUN-179

