{
 "title": "Alerts",
 "tags": [ "Boundary Node" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overall Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "up{job=\"boundary_node_node_exporter\", env=\"prod\"}",
     "legendFormat": "{{ ansible_host }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (ansible_host) (\n  node_memory_MemTotal_bytes{job=\"boundary_node_node_exporter\"}\n  - node_memory_MemFree_bytes{job=\"boundary_node_node_exporter\"}\n  - (node_memory_Cached_bytes{job=\"boundary_node_node_exporter\"}\n  + node_memory_Buffers_bytes{job=\"boundary_node_node_exporter\"}\n  + node_memory_SReclaimable_bytes{job=\"boundary_node_node_exporter\"})\n)",
     "legendFormat": "{{ ansible_host }}"
    }
   ]
  },
  {
   "title": "OOM Occurrences",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ansible_host) (\n  increase(node_vmstat_oom_kill{\n    job=\"boundary_node_node_exporter\",\n  }[1m])\n)",
     "legendFormat": "{{ ansible_host }}"
    }
   ]
  },
  { "title": "File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Available Disk Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (ansible_id, device) (\n  (node_filesystem_avail_bytes{\n    job=\"boundary_node_node_exporter\",\n    fstype!~\"autofs|iso9660|ramfs|tmpfs\",\n    mountpoint!=\"/boot/config\",\n  } * 100)\n  /\n  node_filesystem_size_bytes{\n    job=\"boundary_node_node_exporter\",\n    fstype!~\"autofs|iso9660|ramfs|tmpfs\",\n    mountpoint!=\"/boot/config\",\n  }\n) < 100",
     "legendFormat": "{{ ansible_id }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Available Disk Space (4 Hour Projection)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "predict_linear(node_filesystem_avail_bytes{\n  job=\"boundary_node_node_exporter\",\n  fstype!~\"autofs|iso9660|ramfs|tmpfs\",\n  mountpoint!=\"/boot/config\",\n}[1h], 4 * 3600)",
     "legendFormat": "{{ ansible_id }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Available Disk Space (24 Hour Projection)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n\n    predict_linear(\n        node_filesystem_avail_bytes{\n            job=\"boundary_node_node_exporter\",\n            fstype!~\"autofs|iso9660|ramfs|tmpfs\",\n            mountpoint!=\"/boot/config\",\n        }[1h],\n        24 * 60 * 60                                                      # Predict the next 24 hours\n    ) * on (ansible_host) group_left() (\n        node_time_seconds{job=\"boundary_node_node_exporter\"} -\n        node_boot_time_seconds{job=\"boundary_node_node_exporter\"} >bool   # 0 out the 24 hour predictions\n        3 * 60 * 60                                                       # if uptime is small \n    )\n    +\n    on (ansible_host, mountpoint, device) predict_linear(\n        node_filesystem_avail_bytes{\n            job=\"boundary_node_node_exporter\",\n            fstype!~\"autofs|iso9660|ramfs|tmpfs\",\n            mountpoint!=\"/boot/config\",\n        }[1h],\n        6 * 60 * 60                                                       # Predict the next 6 hours\n    ) * on (ansible_host) group_left() (\n        node_time_seconds{job=\"boundary_node_node_exporter\"} -\n        node_boot_time_seconds{job=\"boundary_node_node_exporter\"} <=bool  # 0 out the 6 hour predictions\n        3 * 60 * 60                                                       # if uptime is large \n    ),\n\n    \"ansible_host\", \"$1\", \"ansible_host\", \"(.*?)\\\\..+\"\n)",
     "legendFormat": "{{ ansible_host }} - {{ mountpoint }}"
    }
   ]
  }
 ]
}