{
 "title": "Replicas",
 "tags": [
  "Boundary Node",
  "Clickhouse"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "Production : prod, Development : dev"
   },
   { "name": "table_replicas", "query": "http_access_by_replica" },
   { "name": "table_canisters", "query": "http_access_by_canister" },
   {
    "name": "node_id",
    "label": "Node ID",
    "query": "SELECT\n DISTINCT ic_node_id\nFROM\n $table_replicas\nWHERE\n date >= ${__from:date:seconds}\n AND\n date <= ${__to:date:seconds}\n AND\n ic_request_type != ''\n AND\n ic_node_id != ''\n"
   },
   {
    "name": "request_type",
    "label": "Request Type",
    "query": "SELECT\n DISTINCT ic_request_type\nFROM\n $table_replicas\nWHERE\n date >= ${__from:date:seconds}\n AND\n date <= ${__to:date:seconds}\n AND\n ic_node_id = '${node_id}'\n AND\n ic_request_type != ''\n"
   },
   {
    "name": "datasource",
    "query": "vertamedia-clickhouse-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Canisters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  uniq(ic_canister_id)\nFROM $table_canisters\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_node_id      =  '$node_id',         $node_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\n",
     "rawQuery": "SELECT\n  uniq(ic_canister_id)\nFROM http_access_by_canister\nWHERE\n  date >= toDateTime(1684059042) AND date <= toDateTime(1684145442)\n   AND env             =  'prod' \n   AND ic_node_id      =  '25p5a-3yzir-ifqqt-5lggj-g4nxg-v2qe2-vxw57-qkxtd-wjohn-kfbfp-bqe' \n   \n  AND ic_request_type != ''",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Unique Clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT uniqCombinedMerge(unique_ips) AS \"By IP\", uniqCombinedMerge(unique_senders) AS \"By SenderID\"\nFROM $table_replicas\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_node_id      =  '$node_id',         $node_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''",
     "rawQuery": "SELECT uniqCombinedMerge(unique_ips) AS \"By IP\", uniqCombinedMerge(unique_senders) AS \"By SenderID\"\nFROM http_access_by_replica\nWHERE\n  date >= toDateTime(1684059068) AND date <= toDateTime(1684145468)\n   AND env             =  'prod' \n   AND ic_node_id      =  '25p5a-3yzir-ifqqt-5lggj-g4nxg-v2qe2-vxw57-qkxtd-wjohn-kfbfp-bqe' \n   \n  AND ic_request_type != ''",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  sum(request_size_sum) / (${__to:date:seconds} - ${__from:date:seconds}) * 8 AS In,\n  sum(response_size_sum) / (${__to:date:seconds} - ${__from:date:seconds}) * 8 AS Out\nFROM $table_replicas\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_node_id      =  '$node_id',         $node_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\n",
     "rawQuery": "SELECT\n  sum(request_size_sum) / (1684145470 - 1684059070) * 8 AS In,\n  sum(response_size_sum) / (1684145470 - 1684059070) * 8 AS Out\nFROM http_access_by_replica\nWHERE\n  date >= toDateTime(1684059102) AND date <= toDateTime(1684145502)\n   AND env             =  'prod' \n   AND ic_node_id      =  '25p5a-3yzir-ifqqt-5lggj-g4nxg-v2qe2-vxw57-qkxtd-wjohn-kfbfp-bqe' \n   \n  AND ic_request_type != ''",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Data Transferred",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  sum(request_size_sum) AS In,\n  sum(response_size_sum) AS Out\nFROM $table_replicas\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_node_id      =  '$node_id',         $node_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\n",
     "rawQuery": "SELECT\n  sum(request_size_sum) AS In,\n  sum(response_size_sum) AS Out\nFROM http_access_by_replica\nWHERE\n  date >= toDateTime(1684059116) AND date <= toDateTime(1684145516)\n   AND env             =  'prod' \n   AND ic_node_id      =  '25p5a-3yzir-ifqqt-5lggj-g4nxg-v2qe2-vxw57-qkxtd-wjohn-kfbfp-bqe' \n   \n  AND ic_request_type != ''",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    countMerge(request_count) / ($__interval_ms / 1000) AS Rate,\n    status\nFROM $table_replicas\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_node_id      =  '$node_id',         $node_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\nGROUP BY t, status\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n    countMerge(request_count) / (300000 / 1000) AS Rate,\n    status\nFROM http_access_by_replica\nWHERE\n  date >= toDateTime(1709723122) AND date <= toDateTime(1709809522)\n   AND env             =  'prod' \n   AND ic_node_id      =  '23jbm-6z6mi-ki2ut-fkz5x-yy4uy-6llls-yyodh-xv537-2qonk-2iod3-jae' \n   \n  AND ic_request_type != ''\nGROUP BY t, status\nORDER BY t",
     "round": "0s",
     "table": "http_access_by_canister"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "-- Calculating all quantiles in one go is much faster\nSELECT\n  t,\n  q[1] AS p50,\n  q[2] AS p95,\n  q[3] AS p99\nFROM (\n SELECT\n     $timeSeries as t,\n     quantilesMerge(0.50, 0.95, 0.99)(request_time_ms) AS q\n FROM $table_replicas\n WHERE\n   $timeFilter\n   $conditionalTest(AND env             =  '$env',             $env)\n   $conditionalTest(AND ic_node_id      =  '$node_id',         $node_id)\n   $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n   AND ic_request_type != ''\n GROUP BY t\n ORDER BY t\n)",
     "rawQuery": "\nSELECT\n  t,\n  q[1] AS p50,\n  q[2] AS p95,\n  q[3] AS p99\nFROM (\n SELECT\n     (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n     quantilesMerge(0.50, 0.95, 0.99)(request_time_ms) AS q\n FROM http_access_by_replica\n WHERE\n   date >= toDateTime(1684059145) AND date <= toDateTime(1684145545)\n    AND env             =  'prod' \n    AND ic_node_id      =  '25p5a-3yzir-ifqqt-5lggj-g4nxg-v2qe2-vxw57-qkxtd-wjohn-kfbfp-bqe' \n    \n   AND ic_request_type != ''\n GROUP BY t\n ORDER BY t\n)",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Requests by Type (p95 Latency)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ic_request_type,\n    quantileMerge(0.95)(request_time_ms)\nFROM $table_replicas\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_node_id      =  '$node_id',         $node_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\nGROUP BY t, ic_request_type\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n    ic_request_type,\n    quantileMerge(0.95)(request_time_ms)\nFROM http_access_by_replica\nWHERE\n  date >= toDateTime(1684059166) AND date <= toDateTime(1684145566)\n   AND env             =  'prod' \n   AND ic_node_id      =  '25p5a-3yzir-ifqqt-5lggj-g4nxg-v2qe2-vxw57-qkxtd-wjohn-kfbfp-bqe' \n   \n  AND ic_request_type != ''\nGROUP BY t, ic_request_type\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Requests by Type (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ic_request_type,\n    countMerge(request_count) / ($__interval_ms / 1000)\nFROM $table_replicas\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_node_id      =  '$node_id',         $node_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\nGROUP BY t, ic_request_type\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n    ic_request_type,\n    countMerge(request_count) / (300000 / 1000)\nFROM http_access_by_replica\nWHERE\n  date >= toDateTime(1706537062) AND date <= toDateTime(1706623462)\n   AND env             =  'prod' \n   AND ic_node_id      =  '23jbm-6z6mi-ki2ut-fkz5x-yy4uy-6llls-yyodh-xv537-2qonk-2iod3-jae' \n   \n  AND ic_request_type != ''\nGROUP BY t, ic_request_type\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Request Origins",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    geo_country_code AS Country,\n    countMerge(request_count) AS TotalRequests\nFROM $table_replicas\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_node_id      =  '$node_id',         $node_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\nGROUP BY Country",
     "rawQuery": "SELECT\n    geo_country_code AS Country,\n    countMerge(request_count) AS TotalRequests\nFROM http_access_by_replica\nWHERE\n  date >= toDateTime(1709723174) AND date <= toDateTime(1709809574)\n   AND env             =  'prod' \n   AND ic_node_id      =  '23jbm-6z6mi-ki2ut-fkz5x-yy4uy-6llls-yyodh-xv537-2qonk-2iod3-jae' \n   \n  AND ic_request_type != ''\nGROUP BY Country",
     "round": "0s",
     "table": "http_access"
    }
   ]
  }
 ]
}