= drun

A simple tool to install and test a canister, provided as a Wasm binary file, using PocketIC. The
primary use case is that of an Motoko-developer who wants to test Wasm binaries running on a single
node.

== Synopsis

[source,shell]
....
$ bazel run //rs/drun -- <messages_file>
....

* `<messages_file>`: A line-based ASCII-encoded text file containing the messages to be processed.

== Message Input File Format

Each line of the input file contains at most one message to be processed. All messages are processed
synchronously: The next message starts executing when the previous message has finished executing.
Three message types are currently supported: `ingress`, `query` and `install`.

=== Create Canister Messages

Create canister messages have the following format:

----
create
----

=== Code Installation Messages

Code installation messages have the following format:

----
<mode> <canister_id> <wasmfile> <payload>
----

* `<mode>` is one of `install`, `reinstall` or `upgrade`
- `drun` automatically detects whether the Wasm binary expects enhanced orthogonal persistence (as used in Motoko) and if so, sets the `wasm_memory_persistence` upgrade option.

* `<canister_id>` is the desired ID for the canister to be installed, given in textual
representation (e.g. `rwlgt-iiaaa-aaaaa-aaaaa-cai`) as specified in https://internetcomputer.org/docs/current/references/ic-interface-spec#textual-ids.

* `<wasmfile>` is a path to a Wasm file that should be installed in this drun execution.

* `<payload>` is a octet-string that is either encoded as an arbitrary length hex-string
(e.g. `0xffffff`) or a double quoted ASCII string. See string escape rules
section below for escape rules in strings.

=== Ingress Messages

Ingress messages have the following format:

----
ingress <canister_id> <method_name> <method_payload>
----

* `<canister_id>` is the ID of the canister for which this ingress message is destined. A canister
with the given ID has to be installed perviously using `install <canister_id> ..`.

* `<method_name>` is a C-like identifier (`[a-zA-Z_][a-zA-Z0-9_]*`). Examples: `_identifier`,
`read`, `write`, ...

* `<method_payload>` is a octet-string that is either encoded as an arbitrary length hex-string
(e.g. `0xffffff`) or a double quoted ASCII string. See string escape rules
section below for escape rules in strings.

=== Query Messages

----
query <canister_id> <method_name> <method_payload>
----

Same as above, except that the method call will be processed as a query, not as an ingress message.

=== String escape rules

** `\\` to escape `\`
** `\"` to escape `"`
** `\x[0-9a-f]{2}` for a hexadecimal representation (i.e., `"A\x01\x02\x03"`  is equivalent to
`0x65010203`)
** `\b[01]{8}` for a bitwise representation (i.e., `"A\b00000001\b00000010\b00000011"` is equivalent
to `0x65010203`).

== Output Format

Each message produces exactly one line of output.

=== Ingress Messages

Each successfully completed ingress message produces an output of the following form:
----
ingress Ok: <WasmResult>
----

See <<WASM Result>> for more details on `<WasmResult>`.

Each failed ingress message produces an output of the following form:
----
ingress Err: <String>
----

=== Query Messages

Each successfully completed query produces an output of the following form:
----
Ok: <WasmResult>
----

See <<WASM Result>> for more details on `<WasmResult>`.

Each failed query produces an output of the following form:
----
Err: <String>
----

==== WASM Result

If the message is successfully replied, the output is of the form:

----
Reply: 0x010203
----

If the message is rejected, the output is of the form:

----
Reject: <String>
----
