{
 "title": "State Sync Manager",
 "description": "Consensus Finalization Height",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "label": "IC", "query": { "query": "label_values(ic)" } },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{ic=\"$ic\",job=\"replica\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   },
   { "name": "period", "label": "Aggregation period", "query": "20s,30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "state syncs started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  state_sync_manager_started_sync_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "state sync adverts receive rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(state_sync_manager_adverts_received_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$period]),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "highest/lowest state height broadcasted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  state_sync_manager_highest_state_broadcasted{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "high {{instance}}"
    },
    {
     "expr": "label_replace(\nlabel_replace(\n  state_sync_manager_lowest_state_broadcasted{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "low {{instance}}"
    }
   ]
  },
  { "title": "Ongoing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "state delivered to MR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  state_sync_manager_chunk_size_decompressed_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "state received from p2p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  state_sync_manager_chunk_size_compressed_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "allowed parallel downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  state_sync_manager_allowed_parallel_downloads{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "chunks to download calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  state_sync_manager_chunks_to_download_calls_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "peers serving state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  state_sync_manager_peers_serving_state{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "chunks to download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  state_sync_manager_chunks_to_download_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "average chunk download duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(state_sync_manager_chunk_download_duration_sum{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$period]) /\n  rate(state_sync_manager_chunk_download_duration_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$period]),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "chunk download result",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  state_sync_manager_chunk_download_results_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{status}}"
    }
   ]
  },
  {
   "title": "chunk download 0.9 percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  histogram_quantile(0.9, rate(state_sync_manager_chunk_download_duration_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$period])),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "chunk compresssion buckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"1\"}) /  sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} non-compressable"
    },
    {
     "expr": "label_replace(\nlabel_replace(\n  (sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"1.25\"}) - sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"1\"})) /  sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} 1-1.25"
    },
    {
     "expr": "label_replace(\nlabel_replace(\n  (sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"1.5\"}) - sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"1.25\"})) /  sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} 1.25-1.5"
    },
    {
     "expr": "label_replace(\nlabel_replace(\n  (sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"2\"}) - sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"1.5\"})) /  sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} 1.5-2"
    },
    {
     "expr": "label_replace(\nlabel_replace(\n  (sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"3\"}) - sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"2\"})) /  sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} 2-3"
    },
    {
     "expr": "label_replace(\nlabel_replace(\n  (sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"5\"}) - sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"3\"})) /  sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} 3-5"
    },
    {
     "expr": "label_replace(\nlabel_replace(\n  (sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"10\"}) - sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"5\"})) /  sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} 5-10"
    },
    {
     "expr": "label_replace(\nlabel_replace(\n  (sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"+Inf\"}) - sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", le=\"10\"})) /  sum by (ic_subnet) (state_sync_manager_chunk_compression_ratio_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} 10-Inf"
    }
   ]
  }
 ]
}