{
 "title": "Ledger",
 "tags": [
  "production",
  "fi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ck_token",
    "label": "ck token",
    "query": {
     "query": "label_values(ledger_transactions_by_height_entries, token)"
    }
   },
   {
    "name": "sns_token",
    "label": "SNS Token",
    "query": {
     "query": "label_values(ledger_transactions_by_height_entries, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ICP ledger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ledger daily transactions rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ledger_transactions_by_hash_cache_entries{token=\"icp\"}",
     "legendFormat": "by_hash_cache_size"
    },
    {
     "expr": "ledger_transactions_by_height_entries{token=\"icp\"}",
     "legendFormat": "by_height_size:"
    }
   ]
  },
  {
   "title": "Ledger block rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ledger_total_blocks{ic=\"mercury\",token=\"icp\"}[$__rate_interval])",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Instruction usage in most recent upgrade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ledger_total_upgrade_instructions_consumed{token=\"icp\"} < 1000000000000",
     "legendFormat": "total"
    },
    {
     "expr": "ledger_post_upgrade_instructions_consumed{token=\"icp\"} < 1000000000000",
     "legendFormat": "post-upgrade"
    },
    {
     "expr": "ledger_pre_upgrade_instructions_consumed{token=\"icp\"} < 1000000000000",
     "legendFormat": "pre-upgrade"
    }
   ]
  },
  {
   "title": "(Ledger and Archive 20s ago) vs Index",
   "type": "timeseries",
   "description": "The total number of blocks in the ledger + archives 20 seconds ago, minus the current number of blocks in the index. If this value is >0, it means the index has had 20s to process all the blocks but has not managed - it may be stuck.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (value, token) (ledger_total_blocks{ic=\"mercury\",token=\"icp\"} offset 20s) - sum by (value, token)(index_number_of_blocks{ic=\"mercury\",token=\"icp\"})",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Stable memory bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ledger_stable_memory_bytes{token=\"icp\"} or stable_memory_bytes{token=\"icp\", job=~\"ledger-canister\"}",
     "legendFormat": "ledger"
    },
    {
     "expr": "index_stable_memory_bytes{token=\"icp\"} or stable_memory_bytes{token=\"icp\", job=~\"icp-index\"}",
     "legendFormat": "index"
    },
    {
     "expr": "archive_node_stable_memory_bytes{token=\"icp\"} or stable_memory_bytes{token=\"icp\", job=~\"ledger-archive.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap memory bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ledger_total_memory_bytes{token=\"icp\"} or heap_memory_bytes{token=\"icp\", job=~\"ledger-canister\"}",
     "legendFormat": "ledger"
    },
    {
     "expr": "index_total_memory_bytes{token=\"icp\"} or heap_memory_bytes{token=\"icp\", job=~\"icp-index\"}",
     "legendFormat": "index"
    },
    {
     "expr": "archive_node_total_memory_bytes{token=\"icp\"} or heap_memory_bytes{token=\"icp\", job=~\"ledger-archive.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of allowances in the ledger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ledger_num_approvals{token=\"icp\"}",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Total number of accounts in the ledger balance store",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ledger_balance_store_entries{token=\"icp\"}",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Index block sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ledger_total_blocks{token=\"icp\"}",
     "legendFormat": "ledger blocks"
    },
    {
     "expr": "index_number_of_blocks{token=\"icp\"}",
     "legendFormat": "index blocks"
    }
   ]
  },
  {
   "title": "Ledger notify method calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ledger_notify_method_calls{token=\"icp\"}",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Tokens in pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ledger_balances_token_pool{token=\"icp\"}",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Index last wait time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "index_last_wait_time{token=\"icp\"}",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Age of most recent ledger block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(time() - ledger_most_recent_block_time_seconds{token=\"icp\"}) / 60",
     "legendFormat": "Age: {{token}}"
    }
   ]
  },
  {
   "title": "Ledger archived blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ledger_archived_blocks{token=\"icp\"}",
     "legendFormat": "archived blocks: {{token}}"
    }
   ]
  },
  {
   "title": "Ledger stored blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ledger_blocks{token=\"icp\"}",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Archive stored blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "archive_node_blocks{token=\"icp\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ck ledgers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ledger transactions rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ledger_transactions_by_hash_cache_entries{token =~ \"${ck_token}\"}",
       "legendFormat": "by_hash_cache_size: {{token}}"
      },
      {
       "expr": "ledger_transactions_by_height_entries{token =~ \"${ck_token}\"}",
       "legendFormat": "by_height_size: {{token}}"
      }
     ]
    },
    {
     "title": "Ledger block rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ledger_total_transactions{ic=\"mercury\",token=~\"${ck_token}\"}[$__rate_interval])",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Instruction usage in most recent upgrade",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3210 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ledger_total_upgrade_instructions_consumed{token=~\"${ck_token}\"} < 1000000000000",
       "legendFormat": "total ({{token}})"
      },
      {
       "expr": "ledger_post_upgrade_instructions_consumed{token=~\"${ck_token}\"} < 1000000000000",
       "legendFormat": "post-upgrade ({{token}})"
      },
      {
       "expr": "ledger_pre_upgrade_instructions_consumed{token=~\"${ck_token}\"} < 1000000000000",
       "legendFormat": "pre-upgrade ({{token}})"
      }
     ]
    },
    {
     "title": "(Ledger and Archive 20s ago) vs Index",
     "type": "timeseries",
     "description": "The total number of blocks in the ledger + archives 20 seconds ago, minus the current number of blocks in the index. If this value is >0, it means the index has had 20s to process all the blocks but has not managed - it may be stuck.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3210 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (value, token) (ledger_total_transactions{token=~\"${ck_token}\"} offset 20s) - sum by (value, token)(index_number_of_blocks{token=~\"${ck_token}\"})",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Stable memory bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3218 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ledger_stable_memory_bytes{token=~\"${ck_token}\"} or stable_memory_bytes{token=~\"${ck_token}\", job=~\".*-ledger\"}",
       "legendFormat": "ledger ({{token}})"
      },
      {
       "expr": "index_stable_memory_bytes{token=~\"${ck_token}\"} or stable_memory_bytes{token=~\"${ck_token}\", job=~\".*-index\"}",
       "legendFormat": "index ({{token}})"
      },
      {
       "expr": "archive_stable_memory_bytes{token=~\"${ck_token}\"} or stable_memory_bytes{token=~\"${ck_token}\", job=~\".*-archive\"}",
       "legendFormat": "archive ({{token}})"
      }
     ]
    },
    {
     "title": "Heap memory bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3218 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ledger_total_memory_bytes{token=~\"${ck_token}\"} or heap_memory_bytes{token=~\"${ck_token}\", job=~\".*-ledger\"}",
       "legendFormat": "ledger ({{token}})"
      },
      {
       "expr": "index_total_memory_bytes{token=~\"${ck_token}\"} or heap_memory_bytes{token=~\"${ck_token}\", job=~\".*-index\"}",
       "legendFormat": "index ({{token}})"
      },
      {
       "expr": "archive_total_memory_bytes{token=~\"${ck_token}\"} or heap_memory_bytes{token=~\"${ck_token}\", job=~\".*-archive\"}",
       "legendFormat": "archive ({{token}})"
      }
     ]
    },
    {
     "title": "Total number of allowances in the ledger",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3226 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ledger_num_approvals{token=~\"${ck_token}\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Total number of accounts in the ledger balance store",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3226 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ledger_balance_store_entries{token=~\"${ck_token}\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Index block sync",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3234 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ledger_total_transactions{token=~\"${ck_token}\"}",
       "legendFormat": "ledger blocks ({{token}})"
      },
      {
       "expr": "index_number_of_blocks{token=~\"${ck_token}\"}",
       "legendFormat": "index blocks ({{token}})"
      }
     ]
    },
    {
     "title": "Age of most recent ledger block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3234 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(time() - ledger_most_recent_block_time_seconds{token=~\"${ck_token}\"}) / 60",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Tokens in pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3242 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ledger_balances_token_pool{token=~\"${ck_token}\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Ledger archived blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3242 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ledger_archived_transactions{token=~\"${ck_token}\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Ledger stored blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3250 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ledger_transactions{token=~\"${ck_token}\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Archive stored blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3250 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "archive_stored_blocks{token=~\"${ck_token}\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Index last wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3258 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "index_last_wait_time{token=~\"${ck_token}\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Cycle Balance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3258 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cycle_balance{token=~\"${ck_token}\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cycle Burn Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3266 },
     "fieldConfig": { "defaults": { "unit": "BC/h" } },
     "targets": [
      {
       "expr": "-delta(cycle_balance{token=~\"${ck_token}\"}[1h])/1e9",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Index profile instructions, avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3266 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "quantile by (token) (\n  0.5,\n  rate(index_ng_profile_instructions_sum{token=~\"${ck_token}\"}[$__rate_interval])\n/\n  (rate(index_ng_profile_instructions_count{token=~\"${ck_token}\"}[$__rate_interval]) != 0)\n)",
       "legendFormat": "{{token}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SNS ledgers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ledger transactions rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6339 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(ledger_transactions_by_hash_cache_entries{token =~ \"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "by_hash_cache_size: {{token}}"
      },
      {
       "expr": "label_replace(ledger_transactions_by_height_entries{token =~ \"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "by_height_size: {{token}}"
      }
     ]
    },
    {
     "title": "Ledger block rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6339 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(rate(ledger_total_transactions{ic=\"mercury\",token=~\"sns-${sns_token}\"}[$__rate_interval]), \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Instruction usage in most recent upgrade",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6347 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(ledger_total_upgrade_instructions_consumed{token=~\"sns-${sns_token}\"} < 1000000000000, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "total ({{token}})"
      },
      {
       "expr": "label_replace(ledger_post_upgrade_instructions_consumed{token=~\"sns-${sns_token}\"} < 1000000000000, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "post-upgrade ({{token}})"
      },
      {
       "expr": "label_replace(ledger_pre_upgrade_instructions_consumed{token=~\"sns-${sns_token}\"} < 1000000000000, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "pre-upgrade ({{token}})"
      }
     ]
    },
    {
     "title": "(Ledger and Archive 20s ago) vs Index",
     "type": "timeseries",
     "description": "The total number of blocks in the ledger + archives 20 seconds ago, minus the current number of blocks in the index. If this value is >0, it means the index has had 20s to process all the blocks but has not managed - it may be stuck.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6347 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(sum by (value, token) (ledger_total_transactions{token=~\"sns-${sns_token}\"} offset 20s) - sum by (value, token)(index_number_of_blocks{token=~\"sns-${sns_token}\"}), \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Stable memory bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6355 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(ledger_stable_memory_bytes{token=~\"sns-${sns_token}\"} or stable_memory_bytes{token=~\"sns-${sns_token}\", job=~\".*-ledger\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "ledger ({{token}})"
      },
      {
       "expr": "label_replace(index_stable_memory_bytes{token=~\"sns-${sns_token}\"} or stable_memory_bytes{token=~\"sns-${sns_token}\", job=~\".*-index\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "index ({{token}})"
      },
      {
       "expr": "label_replace(archive_stable_memory_bytes{token=~\"sns-${sns_token}\"} or stable_memory_bytes{token=~\"sns-${sns_token}\", job=~\".*-archive\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "archive ({{token}})"
      }
     ]
    },
    {
     "title": "Heap memory bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6355 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(ledger_total_memory_bytes{token=~\"sns-${sns_token}\"} or heap_memory_bytes{token=~\"sns-${sns_token}\", job=~\".*-ledger\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "ledger ({{token}})"
      },
      {
       "expr": "label_replace(index_total_memory_bytes{token=~\"sns-${sns_token}\"} or heap_memory_bytes{token=~\"sns-${sns_token}\", job=~\".*-index\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "index ({{token}})"
      },
      {
       "expr": "label_replace(archive_total_memory_bytes{token=~\"sns-${sns_token}\"} or heap_memory_bytes{token=~\"sns-${sns_token}\", job=~\".*-archive\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "archive ({{token}})"
      }
     ]
    },
    {
     "title": "Total number of allowances in the ledger",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6363 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(ledger_num_approvals{token=~\"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Total number of accounts in the ledger balance store",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6363 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(ledger_balance_store_entries{token=~\"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Index block sync",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6371 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(ledger_total_transactions{token=~\"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "ledger blocks ({{token}})"
      },
      {
       "expr": "label_replace(index_number_of_blocks{token=~\"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "index blocks ({{token}})"
      }
     ]
    },
    {
     "title": "Age of most recent ledger block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6371 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace((time() - ledger_most_recent_block_time_seconds{token=~\"sns-${sns_token}\"}) / 60, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Tokens in pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6379 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(ledger_balances_token_pool{token=~\"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Ledger archived blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6379 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(ledger_archived_transactions{token=~\"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Ledger stored blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6387 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(ledger_transactions{token=~\"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Cycle Balance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6387 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(cycle_balance{token=~\"sns-${sns_token}\"}, \"job\", \"$1\", \"job\", \"^sns-(.*)\")",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cycle Burn Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6395 },
     "fieldConfig": { "defaults": { "unit": "BC/h" } },
     "targets": [
      {
       "expr": "label_replace(-delta(cycle_balance{token=~\"sns-${sns_token}\"}[1h])/1e9, \"job\", \"$1\", \"job\", \"^sns-(.*)\")",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Index profile instructions, avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6395 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(quantile by (token) (\n  0.5,\n  rate(index_ng_profile_instructions_sum{token=~\"sns-${sns_token}\"}[$__rate_interval])\n/\n  (rate(index_ng_profile_instructions_count{token=~\"sns-${sns_token}\"}[$__rate_interval]) != 0)\n), \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Index last wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6403 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "label_replace(index_last_wait_time{token=~\"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Archive stored blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6403 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(archive_stored_blocks{token=~\"sns-${sns_token}\"}, \"token\", \"$1\", \"token\", \"^sns-(.*)\")",
       "legendFormat": "{{token}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Test Ledgers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ledger transactions rate",
     "type": "timeseries",
     "description": "Note: This only includes transactions where create_at_time was explicitly set by the user",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ledger_transactions_by_hash_cache_entries{token=~\"testicp|ticrc1\"}",
       "legendFormat": "by_hash_cache_size: {{token}}"
      },
      {
       "expr": "ledger_transactions_by_height_entries{token=~\"testicp|ticrc1\"}",
       "legendFormat": "by_height_size: {{token}}"
      }
     ]
    },
    {
     "title": "Ledger block rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ledger_total_transactions{ic=\"mercury\",token=~\"ticrc1\"}[$__rate_interval])",
       "legendFormat": "{{token}}"
      },
      {
       "expr": "rate(ledger_total_blocks{ic=\"mercury\",token=~\"testicp\"}[$__rate_interval])",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Instruction usage in most recent upgrade",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ledger_total_upgrade_instructions_consumed{token=~\"testicp|ticrc1\"} < 1000000000000",
       "legendFormat": "total ({{token}})"
      },
      {
       "expr": "ledger_post_upgrade_instructions_consumed{token=~\"testicp|ticrc1\"} < 1000000000000",
       "legendFormat": "post-upgrade ({{token}})"
      },
      {
       "expr": "ledger_pre_upgrade_instructions_consumed{token=~\"testicp|ticrc1\"} < 1000000000000",
       "legendFormat": "pre-upgrade ({{token}})"
      }
     ]
    },
    {
     "title": "(Ledger and Archive 20s ago) vs Index",
     "type": "timeseries",
     "description": "The total number of blocks in the ledger + archives 20 seconds ago, minus the current number of blocks in the index. If this value is >0, it means the index has had 20s to process all the blocks but has not managed - it may be stuck.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (value, token) (ledger_total_transactions{token=~\"ticrc1\"} offset 20s) - sum by (value, token)(index_number_of_blocks{token=~\"ticrc1\"})",
       "legendFormat": "{{token}}"
      },
      {
       "expr": "sum by (value, token) (ledger_total_blocks{token=~\"testicp\"} offset 20s) - sum by (value, token)(index_number_of_blocks{token=~\"testicp\"})",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Stable memory bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ledger_stable_memory_bytes{token=~\"testicp|ticrc1\"} or stable_memory_bytes{token=~\"testicp|ticrc1\", job=~\".*-ledger\"}",
       "legendFormat": "ledger ({{token}})"
      },
      {
       "expr": "index_stable_memory_bytes{token=~\"testicp|ticrc1\"} or stable_memory_bytes{token=~\"testicp|ticrc1\", job=~\".*-index\"}",
       "legendFormat": "index ({{token}})"
      },
      {
       "expr": "archive_stable_memory_bytes{token=~\"testicp|ticrc1\"} or stable_memory_bytes{token=~\"testicp|ticrc1\", job=~\".*-archive\"}",
       "legendFormat": "archive ({{token}})"
      }
     ]
    },
    {
     "title": "Heap memory bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ledger_total_memory_bytes{token=~\"testicp|ticrc1\"} or heap_memory_bytes{token=~\"testicp|ticrc1\", job=~\".*-ledger\"}",
       "legendFormat": "ledger ({{token}})"
      },
      {
       "expr": "index_total_memory_bytes{token=~\"testicp|ticrc1\"} or heap_memory_bytes{token=~\"testicp|ticrc1\", job=~\".*-index\"}",
       "legendFormat": "index ({{token}})"
      },
      {
       "expr": "archive_total_memory_bytes{token=~\"testicp|ticrc1\"} or heap_memory_bytes{token=~\"testicp|ticrc1\", job=~\".*-archive\"}",
       "legendFormat": "archive ({{token}})"
      }
     ]
    },
    {
     "title": "Total number of allowances in the ledger",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ledger_num_approvals{token=~\"testicp|ticrc1\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Total number of accounts in the ledger balance store",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ledger_balance_store_entries{token=~\"testicp|ticrc1\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Index block sync",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ledger_total_transactions{token=~\"ticrc1\"}",
       "legendFormat": "ledger blocks ({{token}})"
      },
      {
       "expr": "ledger_total_blocks{token=~\"testicp\"}",
       "legendFormat": "ledger blocks ({{token}})"
      },
      {
       "expr": "index_number_of_blocks{token=~\"testicp|ticrc1\"}",
       "legendFormat": "index blocks ({{token}})"
      }
     ]
    },
    {
     "title": "Age of most recent ledger block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(time() - ledger_most_recent_block_time_seconds{token=~\"testicp|ticrc1\"}) / 60",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Tokens in pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ledger_balances_token_pool{token=~\"testicp|ticrc1\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Ledger archived blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ledger_archived_transactions{token=~\"ticrc1\"}",
       "legendFormat": "{{token}}"
      },
      {
       "expr": "ledger_archived_blocks{token=~\"testicp\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Ledger stored blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ledger_transactions{token=~\"ticrc1\"}",
       "legendFormat": "{{token}}"
      },
      {
       "expr": "ledger_blocks{token=~\"testicp\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Archive stored blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "archive_stored_blocks{token=~\"ticrc1\"}",
       "legendFormat": "{{token}}"
      },
      {
       "expr": "archive_node_blocks{token=~\"testicp\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Index last wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "index_last_wait_time{token=~\"testicp|ticrc1\"}",
       "legendFormat": "{{token}}"
      }
     ]
    },
    {
     "title": "Cycle Balance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cycle_balance{token=~\"testicp|ticrc1\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cycle Burn Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "BC/h" } },
     "targets": [
      {
       "expr": "-delta(cycle_balance{token=~\"testicp|ticrc1\"}[1h])/1e9",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Index profile instructions, avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "quantile by (token) (\n  0.5,\n  rate(index_ng_profile_instructions_sum{token=~\"ticrc1\"}[$__rate_interval])\n/\n  (rate(index_ng_profile_instructions_count{token=~\"ticrc1\"}[$__rate_interval]) != 0)\n)",
       "legendFormat": "{{token}}"
      }
     ]
    }
   ]
  }
 ]
}