{
 "title": "Replica Details",
 "tags": [ "production" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "query": { "query": "label_values(up, ic)" } },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\"}, ic_subnet)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$ic_subnet: # Running replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "repeat": "ic_subnet",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job_ic_icsubnet:up:count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}",
     "legendFormat": "Expected"
    },
    {
     "expr": "job_ic_icsubnet:up:sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum (ic_icsubnet:min_replicas_to_make_progress:limit{ic=\"$ic\",ic_subnet=~\"$ic_subnet\"})",
     "legendFormat": "Min. required"
    }
   ]
  },
  {
   "title": "# replicas",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job, ic_subnet) (up{ic=\"$ic\",job=\"replica\"})",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "count by (job, ic_subnet) (up{ic=\"$ic\",job=\"replica\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Missing replicas",
   "type": "table-old",
   "description": "Replicas that are expected to be running but are missing",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "up{ic=\"$ic\",job=\"replica\"} == 0",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Registry versions",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 14 },
   "targets": [
    {
     "expr": "count_values(\"registry_version\", consensus_membership_registry_version{ic=\"$ic\",job=\"replica\"})"
    }
   ]
  },
  {
   "title": "$ic_subnet: Rate of Ingress Messages transitioning Received -> Success",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "repeat": "ic_subnet",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ic_subnet) (rate(message_state_transition_completed_ic_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}[$__rate_interval]))",
     "legendFormat": "{{ic_subnet}}: Received -> Success"
    }
   ]
  },
  {
   "title": "IC: 1m mean successful state transition times (wall clock, per subnet)",
   "type": "graph",
   "description": "This helps identify if any particular replica (or replicas) is transitioning messages particularly slowly.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (ic, ic_subnet, job) (\n  rate(message_state_transition_completed_wallclock_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}[$__rate_interval]))\n/\nsum by (ic, ic_subnet, job) (\n  rate(message_state_transition_completed_wallclock_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}[$__rate_interval]))",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  },
  {
   "title": "$ic_subnet: 1m mean successful state transition times (wall clock, per replica)",
   "type": "graph",
   "description": "This helps identify if any particular replica (or replicas) is transitioning messages particularly slowly.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "repeat": "ic_subnet",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (ic, ic_subnet, instance) (\nrate(message_state_transition_completed_wallclock_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}[$__rate_interval]))\n/\nsum by (ic, ic_subnet, instance) (\nrate(message_state_transition_completed_wallclock_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IC: %ile latencies for transition Received -> Success",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (job, ic) (job_ic_icsubnet:message_state_transition_completed_wallclock_duration_seconds:histogram_quantile50_rate1m{ic=\"$ic\",job=\"replica\"} >= 0)",
     "legendFormat": "p50"
    },
    {
     "expr": "avg by (ic, job) (job_ic_icsubnet:message_state_transition_completed_wallclock_duration_seconds:histogram_quantile95_rate1m{ic=\"$ic\",job=\"replica\"} >= 0)",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by (ic, job) (job_ic_icsubnet:message_state_transition_completed_wallclock_duration_seconds:histogram_quantile99_rate1m{ic=\"$ic\",job=\"replica\"} >= 0)",
     "legendFormat": "p99"
    },
    {
     "expr": "avg by (ic, job) (job_ic_icsubnet:message_state_transition_completed_wallclock_duration_seconds:histogram_quantile100_rate1m{ic=\"$ic\",job=\"replica\"} >= 0)",
     "legendFormat": "p100"
    },
    {
     "expr": "job_ic_quantile:message_state_transition_completed_wallclock_duration_seconds:slo_limit{ic=\"$ic\",job=\"replica\",quantile=\"50\"  }",
     "legendFormat": "SLO: 50%ile lower than this"
    }
   ]
  },
  {
   "title": "$ic_subnet: %ile latencies for transition Received -> Success",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "repeat": "ic_subnet",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job_ic_icsubnet:message_state_transition_completed_wallclock_duration_seconds:histogram_quantile50_rate1m{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "job_ic_icsubnet:message_state_transition_completed_wallclock_duration_seconds:histogram_quantile95_rate1m{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "job_ic_icsubnet:message_state_transition_completed_wallclock_duration_seconds:histogram_quantile99_rate1m{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "job_ic_icsubnet:message_state_transition_completed_wallclock_duration_seconds:histogram_quantile100_rate1m{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",job=\"replica\"}",
     "legendFormat": "p100"
    },
    {
     "expr": "job_ic_quantile:message_state_transition_completed_wallclock_duration_seconds:slo_limit{ic=\"$ic\",job=\"replica\",quantile=\"50\"  }",
     "legendFormat": "SLO: 50%ile lower than this"
    }
   ]
  }
 ]
}