{
 "title": "Key counts",
 "description": "The number of current keys per node. At time of writing, this should be 5.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "label": "IC", "query": { "query": "label_values(ic)" } },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{ic=\"$ic\",job=\"replica\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "crypto_key_counts public_local per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(crypto_key_counts{key_type=\"public_local\",result=\"ok\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"})/count(crypto_key_counts{key_type=\"public_local\",result=\"ok\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"})",
     "legendFormat": "Keys per node"
    }
   ]
  },
  {
   "title": "crypto_key_counts public_registry per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(crypto_key_counts{key_type=\"public_registry\",result=\"ok\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"})/count(crypto_key_counts{key_type=\"public_registry\",result=\"ok\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"})",
     "legendFormat": "Keys per node"
    }
   ]
  },
  {
   "title": "crypto_key_counts secret_sks per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(crypto_key_counts{key_type=\"secret_sks\",result=\"ok\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"})/count(crypto_key_counts{key_type=\"secret_sks\",result=\"ok\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"})",
     "legendFormat": "Keys per node"
    }
   ]
  }
 ]
}