#!/bin/sh

set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/veritysetup
copy_exec /bin/tail
copy_exec /bin/xargs
copy_exec /sbin/fsck
copy_exec /sbin/fsck.ext4 /sbin
copy_exec /sbin/logsave

manual_add_modules dm_verity
