#!/bin/sh

# Set up rootfs as readonly and integrity protected

set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /scripts/functions

# Mount /boot
TMP_BOOT=/mnt/tmp_boot
mkdir -p ${TMP_BOOT}
mount /dev/vda4 ${TMP_BOOT}

checkfs ${ROOT} root ext4

if [[ ! -f "${TMP_BOOT}/ver_hash.img" ]]; then
    # In case we didn't create the verity metadata during the build process, generate them now
    root_hash=$(veritysetup format ${ROOT} ${TMP_BOOT}/ver_hash.img | tail -n 1 | cut -d' ' -f3- | xargs)
else
    root_hash=$(cat ${TMP_BOOT}/root_hash)
    veritysetup verify ${ROOT} ${TMP_BOOT}/ver_hash.img ${root_hash} -v
fi
salt=$(veritysetup dump ${TMP_BOOT}/ver_hash.img | tail -n 1 | cut -d' ' -f2- | xargs)
veritysetup create vroot ${ROOT} ${TMP_BOOT}/ver_hash.img ${root_hash} ${salt}

exit 0
