{
 "title": "iDKG dealing encryption key rotation",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "label": "IC", "query": { "query": "label_values(ic)" } },
   {
    "name": "ic_subnet",
    "label": "IC Subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\"}, instance)"
    }
   },
   {
    "name": "instance_host",
    "label": "Instance Host",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=~\"$instance\"}, instance)"
    }
   },
   {
    "name": "dc",
    "label": "DC",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Successful key rotations by subnet",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n        sum by (ic_subnet) (crypto_key_rotation_results{result=\"key_rotated\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",ic_subnet=~\".+\",instance=~\"\\\\[?$dc:.*\",instance=~\"($instance_host):[0-9]+\"}),\n          \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Key rotations status TooRecent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n    orchestrator_key_rotation_status{job=~\"orchestrator.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",ic_subnet=~\".+\",instance=~\"($instance_host):[0-9]+\",status=~\"TooRecent\"} > 0,\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n  )",
     "legendFormat": "{{instance}}: {{status}}"
    }
   ]
  },
  {
   "title": "Key rotations by orchestrator status != TooRecent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n    orchestrator_key_rotation_status{job=~\"orchestrator.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",ic_subnet=~\".+\",instance=~\"($instance_host):[0-9]+\",status=~\"Registered|Registering|Rotating\"} > 0,\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n  )",
     "legendFormat": "{{instance}}: {{status}}"
    }
   ]
  },
  {
   "title": "Non-successful key rotations by instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n        crypto_key_rotation_results{result!=\"key_rotated\",ic=\"$ic\",ic_subnet=~\".+\",instance=~\"\\\\[?$dc:.*\",instance=~\"($instance_host):[0-9]+\"} > 0,\n          \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\")",
     "legendFormat": "{{ic_subnet}} {{instance}} {{result}}"
    }
   ]
  },
  {
   "title": "Registry version of oldest retained iDKG dealing encryption public key",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n    crypto_minimum_registry_version_in_active_idkg_transcripts{job=~\"replica.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~\"($instance_host):[0-9]+\"} > 0,\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n  )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Key in registry but missing locally",
   "type": "timeseries",
   "description": "Observations where one or more node keys in the registry do not exist locally.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\ncrypto_boolean_results{operation=\"key_in_registry_missing_locally\",result=\"true\",job=~\"orchestrator.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",ic_subnet=~\".+\",instance=~\"($instance_host):[0-9]+\"} > 0,\n\"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n  )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Key rotation errors by orchestrator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n    orchestrator_key_rotation_status{job=~\"orchestrator.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~\"($instance_host):[0-9]+\",status=\"Error\"} > 0,\n    \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n  )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latest local key exists in registry",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\ncrypto_boolean_histogram_bucket{name=\"latest_key_exists_in_registry\",job=~\"orchestrator.*\",ic=\"$ic\",ic_subnet=~\".+\",instance=~\"\\\\[?$dc:.*\",instance=~\"($instance_host):[0-9]+\"} - (crypto_boolean_histogram_bucket{name=\"latest_key_exists_in_registry\",job=~\"orchestrator.*\",ic=\"$ic\",ic_subnet=~\".+\",instance=~\"\\\\[?$dc:.*\",instance=~\"($instance_host):[0-9]+\"} offset $__interval),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n  )",
     "legendFormat": "{{instance}} {{le}}"
    }
   ]
  },
  {
   "title": "Successful rotations by instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful key rotations by instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "label_replace(\n    label_replace(\n        crypto_key_rotation_results{result=\"key_rotated\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",ic_subnet=~\".+\",instance=~\"\\\\[?$dc:.*\",instance=~\"($instance_host):[0-9]+\"},\n          \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\")",
       "legendFormat": "{{ic_subnet}} {{instance}} {{result}}"
      }
     ]
    },
    {
     "title": "Successful key rotations for all instances in subnet",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (increase(crypto_key_rotation_results{result=\"key_rotated\",job=~\"orchestrator.*\",ic=\"$ic\",ic_subnet=~\".+\",instance=~\"\\\\[?$dc:.*\"}[$__interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}