{
 "title": "Bitcoin",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "heatmap_period",
    "label": "Heatmap aggregation period",
    "query": "30s,1m,2m,5m,10m,30m,1h,3h,6h,12h,1d"
   },
   { "name": "network", "query": "mainnet,testnet" },
   { "name": "ic", "query": { "query": "label_values(up,ic)" } },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Main Chain Height (Tip)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "main_chain_height{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Main Chain Height - Stable Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "main_chain_height{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n-\nstable_height{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
     "legendFormat": "main_chain_height - stable_height"
    },
    {
     "expr": "normalized_stability_threshold{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n/\nanchor_difficulty{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
     "legendFormat": "stability_threshold"
    },
    {
     "expr": "testnet_unstable_max_depth_difference{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
     "legendFormat": "testnet_unstable_max_depth_difference"
    }
   ]
  },
  {
   "title": "UTXOs Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "utxos_length{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Address UTXOs Count",
   "type": "timeseries",
   "description": "Number of UTXOs owned by address types we support.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "address_utxos_length{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Unstable State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unstable Block Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "unstable_blocks_total{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "unstable_blocks_depth{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "rate(unstable_blocks_tip_depths_sum{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])\n/\nrate(unstable_blocks_tip_depths_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "unstable_blocks_depth_avg"
      }
     ]
    },
    {
     "title": "Anchor Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "sci" } },
     "targets": [
      {
       "expr": "anchor_difficulty{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Unstable Tip Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "unstable_blocks_num_tips{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Difficulty-Based Stability",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "sci" } },
     "targets": [
      {
       "expr": "unstable_blocks_difficulty_based_depth{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "unstable_blocks"
      },
      {
       "expr": "normalized_stability_threshold{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "stability_threshold"
      }
     ]
    },
    {
     "title": "Unstable Tip Depths",
     "type": "heatmap",
     "description": "Aggregated over **$heatmap_period**",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n        increase(\n          unstable_blocks_tip_depths_bucket{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n          [$heatmap_period]\n        )\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Depth-Based Stability",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "clamp_max(\n    unstable_blocks_difficulty_based_depth{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n    /\n    anchor_difficulty{ic=\"$ic\", job=\"bitcoin-$network-canister\"},\n    1000\n)",
       "legendFormat": "unstable_blocks"
      },
      {
       "expr": "normalized_stability_threshold{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n/\nanchor_difficulty{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "stability_threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "Watchdog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Access",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum (\n    0.99 * api_access_target{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\", flag=\"enabled\"},\n    0.5 * api_access_target{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\", flag=\"disabled\"},\n    0.01 * api_access_target{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\", flag=\"undefined\"},\n)",
       "legendFormat": "target {{flag}}"
      },
      {
       "expr": "sum (\n    0.99 * api_access{ic=\"$ic\", job=\"bitcoin-$network-canister\", flag=\"enabled\"},\n    0.5 * api_access{ic=\"$ic\", job=\"bitcoin-$network-canister\", flag=\"disabled\"},\n    0.01 * api_access{ic=\"$ic\", job=\"bitcoin-$network-canister\", flag=\"undefined\"},\n)",
       "legendFormat": "actual {{flag}}"
      }
     ]
    },
    {
     "title": "Bitcoin Canister Height",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "height_target{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "bitcoin_canister_height{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Bitcoin Canister Height Diff",
     "type": "timeseries",
     "description": "Note: Using a magic number `8181818181` in the query turns `NaN` values from zeros to chart gaps.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "# Using a magic number `8181818181` in the query turns `NaN` values from zeros to chart gaps.\n((height_diff{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\"} +8181818181) > 0) -8181818181",
       "legendFormat": "height_diff"
      },
      {
       "expr": "blocks_behind_threshold{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "blocks_ahead_threshold{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Bitcoin Canister Height Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "height_status{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\"}",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Explorer Height",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "explorer_height{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\"}",
       "legendFormat": "{{explorer}}"
      }
     ]
    },
    {
     "title": "Explorers Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "expr": "available_explorers{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "min_explorers{ic=\"$ic\", job=\"bitcoin-watchdog-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Call Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "calls/sec" } },
     "targets": [
      {
       "expr": "rate(ins_get_utxos_total_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "get_utxos"
      },
      {
       "expr": "rate(ins_get_current_fee_percentiles_total_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "get_current_fee_percentiles"
      },
      {
       "expr": "rate(ins_get_balance_total_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "get_balance"
      }
     ]
    },
    {
     "title": "Send Bitcoin Transaction Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(send_transaction_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "send_transaction"
      }
     ]
    },
    {
     "title": "get_utxos Instruction Cost",
     "type": "heatmap",
     "description": "Aggregated over **$heatmap_period**",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      # Multiply bucket ranges by 1M to compensate for modifications on the Bitcoin canister side\n      label_replace(\n        increase(\n          ins_get_utxos_total_bucket{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n          [$heatmap_period]\n        ),\n        \"le\", \"${1}000000\", \"le\", \"^([0-9]+)$\"\n      )\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "get_utxos Instruction Cost, Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "1e6\n*\nrate(ins_get_utxos_total_sum{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])\n/\nrate(ins_get_utxos_total_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "ins_get_utxos"
      }
     ]
    },
    {
     "title": "get_current_fee_percentiles Instruction Cost",
     "type": "heatmap",
     "description": "Aggregated over **$heatmap_period**",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      # Multiply bucket ranges by 1M to compensate for modifications on the Bitcoin canister side\n      label_replace(\n        increase(\n          ins_get_current_fee_percentiles_total_bucket{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n          [$heatmap_period]\n        ),\n        \"le\", \"${1}000000\", \"le\", \"^([0-9]+)$\"\n      )\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "get_current_fee_percentiles Instruction Cost, Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "1e6\n*\nrate(ins_get_current_fee_percentiles_total_sum{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])\n/\nrate(ins_get_current_fee_percentiles_total_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "ins_get_current_fee_percentiles"
      }
     ]
    },
    {
     "title": "get_balance Instruction Cost",
     "type": "heatmap",
     "description": "Aggregated over **$heatmap_period**",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      # Multiply bucket ranges by 1M to compensate for modifications on the Bitcoin canister side\n      label_replace(\n        increase(\n          ins_get_balance_total_bucket{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n          [$heatmap_period]\n        ),\n        \"le\", \"${1}000000\", \"le\", \"^([0-9]+)$\"\n      )\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "get_balance Instruction Cost, Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "1e6\n*\nrate(ins_get_balance_total_sum{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])\n/\nrate(ins_get_balance_total_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "ins_get_balance"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap size in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "heap_size_in_bytes{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      },
      { "expr": "2 * 1024 * 1024 * 1024", "legendFormat": "wasm_memory_limit" }
     ]
    },
    {
     "title": "Stable memory size in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "stable_memory_size_in_bytes{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Adapter Request / Response",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Request Interval",
     "type": "heatmap",
     "description": "Aggregated over **$heatmap_period**",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le) (\n      increase(\n        get_successors_request_interval_bucket{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n        [$heatmap_period]\n      )\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Rejects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(num_get_successors_rejects{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "num_get_successors_rejects"
      }
     ]
    },
    {
     "title": "Request Interval, Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "rate(\n  get_successors_request_interval_sum{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n  [$__rate_interval]\n)\n/\nrate(\n  get_successors_request_interval_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n  [$__rate_interval]\n)",
       "legendFormat": "get_successors_request_interval"
      }
     ]
    },
    {
     "title": "Response Block Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "blocks/sec" } },
     "targets": [
      {
       "expr": "rate(get_successors_response_block_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(get_successors_request_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Response Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(get_successors_response_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request Data Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(get_successors_request_size{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Response Data Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(get_successors_response_size{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request Size per Packet",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(get_successors_request_size{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])\n/\nrate(get_successors_request_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Response Size per Packet",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(get_successors_response_size{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])\n/\nrate(get_successors_response_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Response Blocks per Packet",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "blocks" } },
     "targets": [
      {
       "expr": "rate(get_successors_response_block_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])\n/\nrate(get_successors_response_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Response Size per Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(get_successors_response_size{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])\n/\nrate(get_successors_response_block_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unstable Block Insertion Cost",
     "type": "heatmap",
     "description": "Aggregated over **$heatmap_period**",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "round(\n  sum by (le) (\n    avg by(le, ic_subnet) (\n      # Multiply bucket ranges by 1M to compensate for modifications on the Bitcoin canister side\n      label_replace(\n        increase(\n          ins_block_insertion_bucket{ic=\"$ic\", job=\"bitcoin-$network-canister\"}\n          [$heatmap_period]\n        ),\n        \"le\", \"${1}000000\", \"le\", \"^([0-9]+)$\"\n      )\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Unstable Block Insertion Cost, Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "1e6\n*\nrate(ins_block_insertion_sum{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])\n/\nrate(ins_block_insertion_count{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "instructions"
      }
     ]
    },
    {
     "title": "Stable Block Ingestion Cost",
     "type": "timeseries",
     "description": "The number of instructions required to insert a block into the stable UTXO set",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "block_ingestion_stats{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "{{instruction_count}}"
      }
     ]
    },
    {
     "title": "Stable Block Ingestion Duration, Rounds",
     "type": "timeseries",
     "description": "The number of rounds required to insert a block into the stable UTXO set",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "block_ingestion_num_rounds{ic=\"$ic\", job=\"bitcoin-$network-canister\"}",
       "legendFormat": "rounds"
      }
     ]
    },
    {
     "title": "Insertion Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "rate(main_chain_height{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "main_chain_height"
      },
      {
       "expr": "rate(stable_height{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "stable_height"
      },
      {
       "expr": "rate(unstable_blocks_depth{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "unstable_blocks_depth"
      },
      {
       "expr": "rate(unstable_blocks_total{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "unstable_blocks_total"
      }
     ]
    },
    {
     "title": "Internal canister errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "rate(num_get_successors_rejects{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "get_successor rejects"
      },
      {
       "expr": "rate(num_block_deserialize_errors{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "block_deserialize errors"
      },
      {
       "expr": "rate(num_insert_block_errors{ic=\"$ic\", job=\"bitcoin-$network-canister\"}[$__rate_interval])",
       "legendFormat": "insert_block errors"
      }
     ]
    }
   ]
  }
 ]
}