{
 "title": "Replicas SxS",
 "description": "IC / Testnet health overview, with filtering drill-down links to detail dashboards",
 "tags": [ "production" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ic",
    "label": "IC",
    "query": {
     "query": "label_values(up{job=\"replica\"}, ic)"
    }
   },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\"}, ic_subnet)"
    }
   },
   {
    "name": "dc",
    "label": "DC",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\"}, instance)"
    }
   },
   { "name": "period", "label": "Aggregation period", "query": "20s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "instance",
    "label": "Instances",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\"}, instance)"
    }
   },
   {
    "name": "instance_host",
    "label": "Instance Host",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=~`${instance:regex}`}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State Range",
   "type": "timeseries",
   "description": "Finalized, max resident, certified and min resident heights, per replica.\n\nPlus finalization rate (blocks / second) per instance, averaged over **$period**.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"}[$period])",
     "legendFormat": "Finalization rate {{instance}}"
    },
    {
     "expr": "rate(state_manager_max_resident_height{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period])",
     "legendFormat": "Execution rate {{instance}}"
    },
    {
     "expr": "certification_last_certified_height{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"} != 0",
     "legendFormat": "Certified height {{instance}}"
    },
    {
     "expr": "artifact_pool_consensus_height_stat{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\",type=\"finalization\",pool_type=\"validated\",stat=\"max\"} != 0",
     "legendFormat": "Finalized height {{instance}}"
    },
    {
     "expr": "state_manager_min_resident_height{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"} != 0",
     "legendFormat": "Min resident height {{instance}}"
    },
    {
     "expr": "state_manager_max_resident_height{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"} != 0",
     "legendFormat": "Max resident height {{instance}}"
    }
   ]
  },
  {
   "title": "Message Induction Rate",
   "type": "timeseries",
   "description": "Subnet messages inducted per second by  status, averaged over **$period**.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status, type) (\n  quantile by(ic, status, ic_subnet, type) (\n    0.5,\n    rate(mr_inducted_xnet_message_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period])\n  )\n)",
     "legendFormat": "Canister {{type}} {{status}}"
    },
    {
     "expr": "sum by(status, type) (\n  quantile by(ic, status, ic_subnet) (\n    0.5,\n    rate(mr_inducted_ingress_message_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period])\n  )\n)",
     "legendFormat": "Ingress {{status}}"
    }
   ]
  },
  {
   "title": "Enqueued Messages",
   "type": "timeseries",
   "description": "Sum of per-subnet median messages enqueued in incoming queues (above zero) and outgoing streams (below).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(kind) (\n  quantile by (ic, ic_subnet, kind) (\n    0.5,\n    execution_input_queue_messages{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}\n  )\n)",
     "legendFormat": "Messages in {{kind}} queue"
    },
    {
     "expr": "sum(\n  quantile by (ic, ic_subnet) (\n    0.5,\n    sum without(remote, destination) (mr_stream_messages{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"})\n  )\n)",
     "legendFormat": "Messages in streams"
    }
   ]
  },
  {
   "title": "Message Execution Rate, by Type",
   "type": "timeseries",
   "description": "Median messages executed per second by message type, averaged over **$period**",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(api_type) (\n  quantile by (ic_subnet, api_type, status) (\n    0.5,\n    rate(sandboxed_execution_executed_message_slices_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\",api_type!~\"non[ -]replicated.*|inspect message\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{api_type}}"
    },
    {
     "expr": "sum by(api_type) (\n  quantile by (ic_subnet, api_type, status) (\n    0.5,\n    rate(sandboxed_execution_executed_message_slices_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\",api_type=~\"non[ -]replicated.*|inspect message\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{api_type}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate, by Type and Status",
   "type": "timeseries",
   "description": "HTTP requests per second across all instances, by type and status, averaged over **$period**",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by (request_type, type, status) (rate(replica_http_request_duration_seconds_count{ic=~\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period])),\n  \"request_type\", \"\", \"request_type\", \"unknown\"\n)",
     "legendFormat": "{{request_type}} {{type}} {{status}}"
    }
   ]
  },
  {
   "title": "Gossip Received",
   "type": "timeseries",
   "description": "Gossip median received unvalidated bytes (above zero, left Y axis) and artifacts (below, right Y axis) across instances by pool, averaged over **$period**",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "quantile by (pool, pool_type) (\n  0.5,\n  rate(artifact_pool_received_artifact_bytes_sum{ic=~\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\", pool_type=\"unvalidated\"}[$period]))",
     "legendFormat": "{{pool}} bytes"
    },
    {
     "expr": "quantile by (pool, pool_type) (\n  0.5,\n  rate(artifact_pool_received_artifact_bytes_count{ic=~\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\", pool_type=\"unvalidated\"}[$period]))",
     "legendFormat": "{{pool}} artifacts"
    }
   ]
  },
  {
   "title": "Consensus CPU Usage",
   "type": "timeseries",
   "description": "CPU time spent in `on_state_change()` by subcomponent, averaged over **$period**.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(\n  consensus_on_state_change_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period]\n)",
     "legendFormat": "{{ sub_component }} {{instance}}"
    }
   ]
  },
  {
   "title": "Replica Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  process_resident_memory_bytes{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"},\n\"instance\", \"$1:...:$2\", \"instance\", \"\\\\[(\\\\w+):.+:(\\\\w+)\\\\].*\"),\n\"ic_subnet\", \"$1\", \"ic_subnet\", \"(\\\\w+)-.+\")",
     "legendFormat": "{{instance}} {{ic_subnet}}"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(process_cpu_seconds_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period]),\n\"instance\", \"$1:...:$2\", \"instance\", \"\\\\[(\\\\w+):.+:(\\\\w+)\\\\].*\"),\n\"ic_subnet\", \"$1\", \"ic_subnet\", \"(\\\\w+)-.+\")",
     "legendFormat": "{{instance}} {{ic_subnet}}"
    }
   ]
  },
  {
   "title": "Transport Flows, by State",
   "type": "timeseries",
   "description": "Total P2P transport flows across instances, by state. In steady state, all transport flows should be in state *Connected*.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(quic_transport_active_connections{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}) or on() vector(0)",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(quic_transport_connecting_connections{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}) or on() vector(0)",
     "legendFormat": "Connecting"
    },
    {
     "expr": "sum(quic_transport_delay_queue_size{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}) or on() vector(0)",
     "legendFormat": "Enqueued"
    },
    {
     "expr": "  quic_transport_toplogy_size{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"} - 1\n-\n  quic_transport_active_connections{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}\n-\n  quic_transport_connecting_connections{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}\n-\n  quic_transport_delay_queue_size{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}",
     "legendFormat": "Disconnected"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Mean Node Network Traffic",
   "type": "timeseries",
   "description": "Mean RX/TX packets and bytes, across nodes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "repeat": "instance_host",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg(\n  sum without(device) (\n    rate(node_network_transmit_packets_total{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}[$period])\n  )\n)",
     "legendFormat": "TX Packets"
    },
    {
     "expr": "avg(\n  sum without(device) (\n    rate(node_network_transmit_bytes_total{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}[$period])\n  )\n)",
     "legendFormat": "TX Bytes"
    },
    {
     "expr": "avg(\n  sum without(device) (\n    rate(node_network_receive_packets_total{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}[$period])\n  )\n)",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "avg(\n  sum without(device) (\n    rate(node_network_receive_bytes_total{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}[$period])\n  )\n)",
     "legendFormat": "RX Bytes"
    }
   ]
  },
  {
   "title": "Mean Node CPU Mode",
   "type": "timeseries",
   "description": "Mean node CPU mode (all processes), across all instances.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "repeat": "instance_host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(mode) (\n  rate(node_cpu_seconds_total{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}[$period])\n)\n/\nscalar(count(up{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Node CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "repeat": "instance_host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  clamp_max(\n    sum by(instance, cpu) (\n      rate(node_cpu_seconds_total{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`,mode!=\"idle\"}[$period])),\n    1)\n!= 0",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 },
   "repeat": "instance_host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}",
     "legendFormat": "Total"
    },
    {
     "expr": "  node_memory_MemTotal_bytes{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}\n-\n  node_memory_MemFree_bytes{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}\n-\n  node_memory_Cached_bytes{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}\n-\n  node_memory_Buffers_bytes{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}",
     "legendFormat": "Used"
    },
    {
     "expr": "  node_memory_Cached_bytes{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}\n+\n  node_memory_Buffers_bytes{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}",
     "legendFormat": "Free"
    },
    {
     "expr": "  node_memory_SwapTotal_bytes{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}\n-\n  node_memory_SwapFree_bytes{job=~\"node_exporter.*\",ic=\"$ic\",instance=~\"\\\\[?$dc:.*\",instance=~`(${instance_host:regex}):[0-9]+`}",
     "legendFormat": "Swap"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Mean Validation Duration, by Artifact Type - $instance",
   "type": "timeseries",
   "description": "Mean validation duration by artifact type on $instance, averaged over **$period**.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  rate(consensus_validation_duration_seconds_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period])\n/\n  rate(consensus_validation_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Non-Empty Change Sets",
   "type": "timeseries",
   "description": "Rate of non-empty change sets returned by `on_state_change()` by subcomponent, averaged over **$period**.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "  rate(consensus_on_state_change_change_set_size_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\",le=\"+Inf\"}[$period])\n- ignoring(le)\n  rate(consensus_on_state_change_change_set_size_bucket{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\",le=\"0\"}[$period])",
     "legendFormat": "{{ sub_component }} {{ instance }}"
    }
   ]
  },
  {
   "title": "`on_state_change()` Sub-Component Invocations",
   "type": "timeseries",
   "description": "Rate of `on_state_change()` invocations on $instance, averaged over **$period**.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 130 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(\n  consensus_on_state_change_duration_seconds_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period]\n)",
     "legendFormat": "{{sub_component}} {{instance}}"
    }
   ]
  },
  {
   "title": "Mean Change Set Size, by Sub-Component",
   "type": "timeseries",
   "description": "Mean change set size returned by each sub-component on $instance, averaged over **$period**.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 138 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "  rate(consensus_on_state_change_change_set_size_sum{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period])\n/\n  rate(consensus_on_state_change_change_set_size_count{ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"\\\\[?$dc:.*\",instance=\"$instance\"}[$period])",
     "legendFormat": "{{sub_component}} {{instance}}"
    }
   ]
  }
 ]
}