{
 "title": "State Sync",
 "tags": [ "production" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ic",
    "label": "IC",
    "query": {
     "query": "label_values(up{job=\"replica\"}, ic)"
    }
   },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{job=\"replica\",ic=\"$ic\"}, ic_subnet)"
    }
   },
   {
    "name": "period",
    "label": "Aggregation period",
    "query": "10s,20s,30s,1m,2m,5m,10m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "State Sync Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  sum by (ic, ic_subnet, instance, op) (\n    (\n      max_over_time(state_sync_size_bytes_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}[$period])\n    -\n      (\n          state_sync_size_bytes_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"} offset $period\n        or\n          min_over_time(state_sync_size_bytes_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}[$period])\n      )\n    )\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"),\n  \"instance\", \"$1...$2\", \"instance\", \"\\\\[((?:[^:]+[.:]){4}).*(:[^:\\\\]]+)\\\\]?:[0-9]+\")\n> 0",
     "legendFormat": "{{op}} {{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "State Sync Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  sum by (ic, ic_subnet, instance, status) (\n    (\n      max_over_time(state_sync_duration_seconds_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}[$period])\n    -\n      (\n          state_sync_duration_seconds_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"} offset $period\n        or\n          min_over_time(state_sync_duration_seconds_count{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}[$period])\n      )\n    )\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"),\n  \"instance\", \"$1...$2\", \"instance\", \"\\\\[((?:[^:]+[.:]){4}).*(:[^:\\\\]]+)\\\\]?:[0-9]+\")\n> 0",
     "legendFormat": "{{ic_subnet}} {{instance}} {{status}}"
    }
   ]
  },
  {
   "title": "Total State Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\n  quantile by (ic_subnet) (\n    0.5,\n    state_manager_state_size_bytes{ic=\"$ic\",ic_subnet=~\"$ic_subnet\"}\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  },
  {
   "title": "State Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  (\n      max_over_time(state_sync_duration_seconds_sum{ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}[$period])\n    -\n      (\n          state_sync_duration_seconds_sum{ic=\"$ic\", ic_subnet=~\"$ic_subnet\"} offset $period\n        or\n          min_over_time(state_sync_duration_seconds_sum{ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}[$period])\n      )\n  ) > 0,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"),\n  \"instance\", \"$1...$2\", \"instance\", \"\\\\[((?:[^:]+[.:]){4}).*(:[^:\\\\]]+)\\\\]?:[0-9]+\")",
     "legendFormat": "{{ic_subnet}} {{instance}} {{status}}"
    }
   ]
  },
  {
   "title": "Remaining Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\nstate_sync_remaining_chunks{ic=\"$ic\",ic_subnet=~\"$ic_subnet\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"),\n  \"instance\", \"$1...$2\", \"instance\", \"\\\\[((?:[^:]+[.:]){4}).*(:[^:\\\\]]+)\\\\]?:[0-9]+\")",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "State Sync Steps Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  (\n      max_over_time(state_sync_step_duration_seconds_sum{ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}[$period])\n    -\n      (\n          state_sync_step_duration_seconds_sum{ic=\"$ic\", ic_subnet=~\"$ic_subnet\"} offset $period\n        or\n          min_over_time(state_sync_step_duration_seconds_sum{ic=\"$ic\", ic_subnet=~\"$ic_subnet\"}[$period])\n      )\n  ) > 0,\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([0-9a-z]+)-.*\"),\n  \"instance\", \"$1...$2\", \"instance\", \"\\\\[((?:[^:]+[.:]){4}).*(:[^:\\\\]]+)\\\\]?:[0-9]+\")",
     "legendFormat": "{{ic_subnet}} {{instance}} {{step}}"
    }
   ]
  }
 ]
}