FROM dfinity/ic-build@sha256:6fe9cb0a0e7cf604eff178efc321830112d6e62d829d50740cd78cbb52aeafed

ENV CARGO_TARGET_DIR=/workspaces/ic/rs/target
ENV RUSTUP_HOME=/home/ubuntu/.rustup CARGO_HOME=/home/ubuntu/.cargo

ENTRYPOINT []
