{
 "title": "Clickhouse Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Job", "query": "boundary-clickhouse" },
   { "name": "ExportedJob", "query": "clickhouse-server" },
   {
    "name": "Node",
    "query": {
     "query": "label_values(ClickHouseMetrics_ReadonlyReplica{job=\"${Job}\", exported_job=\"${ExportedJob}\"}, node)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_TotalRowsOfMergeTreeTables{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_Jitter{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Parts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Merges",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_Merge{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Detached Parts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_NumberOfDetachedParts{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Active Parts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsActive{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Merges/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_Merge{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}[5m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Max Part Count per Partition",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_MaxPartCountForPartition{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Inserts/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_InsertQuery{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}[5m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Selects/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_SelectQuery{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}[5m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Selected rows/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_SelectedRows{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}[5m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Queries Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_Query{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Failed Inserts/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_FailedInsertQuery{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}[5m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Inserted rows/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_InsertedRows{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}[5m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Delayed Inserts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_DelayedInserts{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Replica: Read-Only",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ReadonlyReplica{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Replica: Merges Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasSumMergesInQueue{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Replica: Max Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxAbsoluteDelay{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Replica: Data Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_ReplicatedDataLoss{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}[5m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Replica: Parts Fetch Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_ReplicatedPartFailedFetches{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}[5m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Replica: Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxQueueSize{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Replica: Parts Check Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_ReplicatedPartChecksFailed{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}[5m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Inter-Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_InterserverConnection{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "HTTP Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_HTTPConnection{job=\"${Job}\", exported_job=\"${ExportedJob}\", node=~\"${Node}\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}