{
 "title": "Boundary Health Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "boundary_node_node_exporter" },
   { "name": "env", "query": "prod" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Overall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time((avg(1 - rate(node_cpu_seconds_total{mode='idle',env=\"${env}\",job=\"${job}\",ic=\"mercury\"}[$__rate_interval])) * 100)[10m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Free Memory % Overall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg ((node_memory_MemFree_bytes{env=\"${env}\",job=\"${job}\",ic=\"mercury\"} + node_memory_Cached_bytes{env=\"${env}\",job=\"${job}\",ic=\"mercury\"} + node_memory_Buffers_bytes{env=\"${env}\",job=\"${job}\",ic=\"mercury\"} + node_memory_SReclaimable_bytes{env=\"${env}\",job=\"${job}\",ic=\"mercury\"}) / node_memory_MemTotal_bytes{env=\"${env}\",job=\"${job}\",ic=\"mercury\"} * 100)",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Requests Per Second By Status Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  toInt16(status/100)*100 as status,\n  count() /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND status > 0\nGROUP BY\n  t,\n  status\nORDER BY t\n",
     "rawQuery": "SELECT\n  (intDiv(toUInt32(date), 60) * 60) * 1000 as t,\n  toInt16(status/100)*100 as status,\n  count() /(60000 / 1000)\nFROM\n  default.http_access\nWHERE\n  date >= toDateTime(1727927116) AND date <= toDateTime(1727948716)\n  AND env = 'prod'\n  AND status > 0\nGROUP BY\n  t,\n  status\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Load Average (5m) Overall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(avg(node_load5{env=\"${env}\",job=\"${job}\",ic=\"mercury\"})[10m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Crowdsec Active Decisions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "cs_active_decisions{env=\"prod\",exported_job=\"crowdsec\"}",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "All Subnets Health Overview",
   "type": "state-timeline",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "count by(subnet_id) (ic_boundary_check_status{api_boundary_node=\"1\"} == 1) / count by(subnet_id) (ic_boundary_check_status{api_boundary_node=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP10 Worst Nodes by Availability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(bottomk_avg(10, min(ic_boundary_check_status{api_boundary_node=\"1\"}) by (node_id))[20m])",
     "legendFormat": "{{ node_id }} {{ addr }}"
    }
   ]
  },
  {
   "title": "GuestOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage By BN",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg_over_time((avg by (ansible_host)(1 - rate(node_cpu_seconds_total{mode='idle',env=\"${env}\",job=\"${job}\",ic=\"mercury\"}[$__rate_interval])) * 100)[10m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free Memory % By BN",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (ansible_host)((node_memory_MemFree_bytes{env=\"${env}\",job=\"${job}\",ic=\"mercury\"} + node_memory_Cached_bytes{env=\"${env}\",job=\"${job}\",ic=\"mercury\"} + node_memory_Buffers_bytes{env=\"${env}\",job=\"${job}\",ic=\"mercury\"} + node_memory_SReclaimable_bytes{env=\"${env}\",job=\"${job}\",ic=\"mercury\"}) / node_memory_MemTotal_bytes{env=\"${env}\",job=\"${job}\",ic=\"mercury\"} * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Load Average (5m) By BN",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(avg by(ansible_host) (node_load5{env=\"${env}\",job=\"${job}\",ic=\"mercury\"})[10m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Per Second By BN",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  $timeSeries as t,\n  hostname,\n  count() /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND ic_request_type != ''\nGROUP BY\n  t,\n  hostname\nORDER BY t\n",
       "rawQuery": "SELECT\n  (intDiv(toUInt32(date), 30) * 30) * 1000 as t,\n  hostname,\n  count() /(30000 / 1000)\nFROM\n  default.http_access\nWHERE\n  date >= toDateTime(1710149700) AND date <= toDateTime(1710160500)\n  AND env = 'prod'\n  AND ic_request_type != ''\nGROUP BY\n  t,\n  hostname\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    },
    {
     "title": "Requests Per Second By Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  $timeSeries as t,\n  status,\n  count() /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND status > 0\nGROUP BY\n  t,\n  status\nORDER BY t\n",
       "rawQuery": "SELECT\n  (intDiv(toUInt32(date), 60) * 60) * 1000 as t,\n  status,\n  count() /(60000 / 1000)\nFROM\n  default.http_access\nWHERE\n  date >= toDateTime(1726802985) AND date <= toDateTime(1726824585)\n  AND env = 'prod'\n  AND status > 0\nGROUP BY\n  t,\n  status\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    },
    {
     "title": "Requests Per Second By Canister ID (top10 over last 30min)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "WITH busy_canisters AS (\n  SELECT\n    ic_canister_id\n  FROM\n    $table\n  WHERE\n    date >= ($__to - ($__to - $__from)/2)/1000 - 900\n    AND date <= ($__to + ($__to - $__from)/2)/1000 + 900\n    AND env = '${env}'\n    AND ic_canister_id != ''\n  GROUP BY\n    ic_canister_id\n  ORDER BY\n    countMerge(request_count) DESC\n  LIMIT 10\n)\nSELECT\n  $timeSeries as t,\n  ic_canister_id,\n  countMerge(request_count) /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND ic_canister_id GLOBAL IN (SELECT ic_canister_id FROM busy_canisters)\nGROUP BY\n  t,\n  ic_canister_id\nORDER BY t\n",
       "rawQuery": "WITH busy_canisters AS (\n  SELECT\n    ic_canister_id\n  FROM\n    default.http_access_by_canister\n  WHERE\n    date >= (1710168304544 - (1710168304544 - 1710157504544)/2)/1000 - 900\n    AND date <= (1710168304544 + (1710168304544 - 1710157504544)/2)/1000 + 900\n    AND env = 'prod'\n    AND ic_canister_id != ''\n  GROUP BY\n    ic_canister_id\n  ORDER BY\n    countMerge(request_count) DESC\n  LIMIT 10\n)\nSELECT\n  (intDiv(toUInt32(date), 30) * 30) * 1000 as t,\n  ic_canister_id,\n  countMerge(request_count) /(30000 / 1000)\nFROM\n  default.http_access_by_canister\nWHERE\n  date >= toDateTime(1710158005) AND date <= toDateTime(1710168805)\n  AND env = 'prod'\n  AND ic_canister_id GLOBAL IN (SELECT ic_canister_id FROM busy_canisters)\nGROUP BY\n  t,\n  ic_canister_id\nORDER BY t",
       "round": "0s",
       "table": "http_access_by_canister"
      }
     ]
    },
    {
     "title": "Requests Per Second By CacheStatus",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  $timeSeries as t,\n  if(cache_status == '', 'UNKNOWN', cache_status) as cache_status,\n  count() / ($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND status > 0\nGROUP BY\n  t,\n  cache_status\nORDER BY t\n",
       "rawQuery": "SELECT\n  (intDiv(toUInt32(date), 60) * 60) * 1000 as t,\n  if(cache_status == '', 'UNKNOWN', cache_status) as cache_status,\n  count() / (60000 / 1000)\nFROM\n  default.http_access\nWHERE\n  date >= toDateTime(1726803002) AND date <= toDateTime(1726824602)\n  AND env = 'prod'\n  AND status > 0\nGROUP BY\n  t,\n  cache_status\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    },
    {
     "title": "Requests Per Second By Subnet",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  $timeSeries as t,\n  ic_subnet_id,\n  count() /($__interval_ms / 1000)\nFROM\n  $table\nWHERE\n  $timeFilter\n  AND env = '${env}'\n  AND ic_subnet_id != ''\nGROUP BY\n  t,\n  ic_subnet_id\nORDER BY t\n",
       "rawQuery": "SELECT\n  (intDiv(toUInt32(date), 60) * 60) * 1000 as t,\n  ic_subnet_id,\n  count() /(60000 / 1000)\nFROM\n  default.http_access\nWHERE\n  date >= toDateTime(1726803017) AND date <= toDateTime(1726824617)\n  AND env = 'prod'\n  AND ic_subnet_id != ''\nGROUP BY\n  t,\n  ic_subnet_id\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total traffic (In+Out)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "avg_over_time((avg by (ansible_host)((rate(node_network_receive_bytes_total{env=\"${env}\",job=\"${job}\"}[$__rate_interval])+rate(node_network_transmit_bytes_total{env=\"${env}\",job=\"${job}\"}[$__rate_interval]))*8))[10m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total packets (In+Out)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "avg_over_time((avg by (ansible_host)((rate(node_network_receive_packets_total{env=\"${env}\",job=\"${job}\"}[$__rate_interval])+rate(node_network_transmit_packets_total{env=\"${env}\",job=\"${job}\"}[$__rate_interval]))*8))[10m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (ansible_host)(node_netstat_Tcp_CurrEstab{env=\"${env}\",job=\"${job}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP SynCookies Sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (ansible_host)(rate(node_netstat_TcpExt_SyncookiesSent{env=\"${env}\",job=\"${job}\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP SynCookies Received",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (ansible_host)(rate(node_netstat_TcpExt_SyncookiesRecv{env=\"${env}\",job=\"${job}\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP SynCookies Failed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (ansible_host)(rate(node_netstat_TcpExt_SyncookiesFailed{env=\"${env}\",job=\"${job}\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (ansible_host)(rate(node_netstat_TcpExt_TCPTimeouts{env=\"${env}\",job=\"${job}\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Crowdsec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Crowdsec Processed Events Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(cs_parser_hits_total{env=\"prod\",exported_job=\"crowdsec\"})",
       "legendFormat": "events/s"
      }
     ]
    }
   ]
  }
 ]
}