{
 "title": "HTTP Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "vertamedia-clickhouse-datasource"
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "SELECT\n    v.1 AS __text,\n    v.2 AS __value\nFROM (\n    SELECT  arrayJoin([\n        ('Development', 'dev'),\n        ('Production', 'prod')\n    ]) AS v\n)"
   },
   {
    "name": "hostname",
    "label": "Boundary Name",
    "query": "SELECT DISTINCT hostname\nFROM http_access\nWHERE\n    $timeFilterByColumn(date)\n    $conditionalTest(AND env == $env,  $env)"
   },
   {
    "name": "subnet_id",
    "label": "Subnet ID",
    "query": "SELECT DISTINCT ic_subnet_id\nFROM http_access\nWHERE \n    $timeFilterByColumn(date)\n    AND ic_subnet_id != ''"
   },
   {
    "name": "replica_id",
    "label": "Replica ID",
    "query": "SELECT DISTINCT ic_node_id\nFROM http_access\nWHERE \n    $timeFilterByColumn(date)\n    AND ic_node_id != ''"
   },
   { "name": "canister_id", "label": "Canister ID" },
   {
    "name": "client_country_code",
    "label": "Client Country",
    "query": "SELECT DISTINCT geo_country_code\nFROM http_access\nWHERE $timeFilterByColumn(date)"
   },
   {
    "name": "status_code",
    "label": "HTTP Status Code",
    "query": "SELECT DISTINCT status\nFROM http_access\nWHERE \n    $timeFilterByColumn(date)"
   },
   {
    "name": "is_bot",
    "label": "Client Type",
    "query": "SELECT\n    v.1 AS __text,\n    v.2 AS __value\nFROM (\n    SELECT  arrayJoin([\n        ('Regular', '0'),\n        ('Bot', '1')\n    ]) AS v\n)"
   },
   { "name": "show_deployments", "label": "Show Deployments", "query": "Yes : 1, No : 0" }
  ]
 },
 "panels": [
  { "title": "By Status Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests by HTTP Status Code (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    status,\n    count() / ($__interval_ms / 1000)\nFROM $table\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, status\nORDER BY t",
     "rawQuery": "/* grafana dashboard=HTTP Metrics, user=0 */\nSELECT\n    (intDiv(toUInt32(date), 30) * 30) * 1000 as t,\n    status,\n    count() / (30000 / 1000)\nFROM default.http_access\nWHERE\n  date >= toDateTime(1740989023) AND date <= toDateTime(1740999823)\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, status\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Requests by HTTP Status Code (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    status,\n    median(0.50)(request_time_ms) AS p50\nFROM $table\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, status\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 2) * 2) * 1000 as t,\n    status,\n    median(0.50)(request_time_ms) AS p50\nFROM default.http_access\nWHERE\n  date >= toDateTime(1707210083) AND date <= toDateTime(1707210704)\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, status\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "By Cache Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by Cache Status (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    cache_status,\n    count() / ($__interval_ms / 1000)\nFROM $table\nWHERE\n  $timeFilter\n  AND cache_status != ''\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, cache_status\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 1) * 1) * 1000 as t,\n    cache_status,\n    count() / (1000 / 1000)\nFROM default.http_access\nWHERE\n  date >= toDateTime(1707210344) AND date <= toDateTime(1707210363)\n  AND cache_status != ''\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, cache_status\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    },
    {
     "title": "Requests by Cache Status (Latency)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    cache_status,\n    median(0.50)(request_time_ms) AS p50\nFROM $table\nWHERE\n  $timeFilter\n  AND cache_status != ''\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, cache_status\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 1) * 1) * 1000 as t,\n    cache_status,\n    median(0.50)(request_time_ms) AS p50\nFROM default.http_access\nWHERE\n  date >= toDateTime(1707210344) AND date <= toDateTime(1707210363)\n  AND cache_status != ''\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, cache_status\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    },
    {
     "title": "Requests by Cache Bypass Reason (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    cache_bypass_reason,\n    count() / ($__interval_ms / 1000)\nFROM $table\nWHERE\n  $timeFilter\n  AND cache_bypass_reason != ''\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, cache_bypass_reason\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 1) * 1) * 1000 as t,\n    cache_bypass_reason,\n    count() / (1000 / 1000)\nFROM default.http_access\nWHERE\n  date >= toDateTime(1707210344) AND date <= toDateTime(1707210363)\n  AND cache_bypass_reason != ''\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, cache_bypass_reason\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    }
   ]
  },
  {
   "title": "By Error Cause",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by Error Cause (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    error_cause,\n    count() / ($__interval_ms / 1000)\nFROM $table\nWHERE\n  $timeFilter\n  AND error_cause NOT IN ('', 'none')\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, error_cause\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 30) * 30) * 1000 as t,\n    error_cause,\n    count() / (30000 / 1000)\nFROM default.http_access\nWHERE\n  date >= toDateTime(1707206882) AND date <= toDateTime(1707217682)\n  AND error_cause NOT IN ('', 'none')\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, error_cause\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    }
   ]
  },
  {
   "title": "By Boundary Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by Boundary Node (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    hostname,\n    count() / ($__interval_ms / 1000)\nFROM $table\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, hostname\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 1) * 1) * 1000 as t,\n    hostname,\n    count() / (1000 / 1000)\nFROM default.http_access\nWHERE\n  date >= toDateTime(1707210344) AND date <= toDateTime(1707210363)\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, hostname\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    },
    {
     "title": "Requests by Boundary Node (Latency)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    hostname,\n    median(0.50)(request_time_ms) AS p50\nFROM $table\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, hostname\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 1) * 1) * 1000 as t,\n    hostname,\n    median(0.50)(request_time_ms) AS p50\nFROM default.http_access\nWHERE\n  date >= toDateTime(1707210344) AND date <= toDateTime(1707210363)\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, hostname\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    }
   ]
  },
  {
   "title": "By Subnet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by Subnet (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    ic_subnet_id,\n    count() / ($__interval_ms / 1000)\nFROM $table\nWHERE\n  $timeFilter\n  AND ic_subnet_id != ''\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, ic_subnet_id\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 1) * 1) * 1000 as t,\n    ic_subnet_id,\n    count() / (1000 / 1000)\nFROM default.http_access\nWHERE\n  date >= toDateTime(1707210344) AND date <= toDateTime(1707210363)\n  AND ic_subnet_id != ''\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, ic_subnet_id\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    },
    {
     "title": "Requests by Subnet ID (Latency)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    ic_subnet_id,\n    median(0.50)(request_time_ms) AS p50\nFROM $table\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, ic_subnet_id\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 1) * 1) * 1000 as t,\n    ic_subnet_id,\n    median(0.50)(request_time_ms) AS p50\nFROM default.http_access\nWHERE\n  date >= toDateTime(1707210344) AND date <= toDateTime(1707210363)\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, ic_subnet_id\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    }
   ]
  },
  {
   "title": "By Replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by Replica ID (Latency)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    ic_node_id,\n    median(0.50)(request_time_ms) AS p50\nFROM $table\nWHERE\n  $timeFilter\n  AND ic_node_id != ''\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, ic_node_id\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 1) * 1) * 1000 as t,\n    ic_node_id,\n    median(0.50)(request_time_ms) AS p50\nFROM default.http_access\nWHERE\n  date >= toDateTime(1707210344) AND date <= toDateTime(1707210363)\n  AND ic_node_id != ''\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   \n   \nGROUP BY t, ic_node_id\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    }
   ]
  },
  {
   "title": "By Country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by Country (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    geo_country_code,\n    count() / ($__interval_ms / 1000)\nFROM $table\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, geo_country_code\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 30) * 30) * 1000 as t,\n    geo_country_code,\n    count() / (30000 / 1000)\nFROM default.http_access\nWHERE\n  date >= toDateTime(1724659051) AND date <= toDateTime(1724669851)\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   AND status                IN (451) \n   \nGROUP BY t, geo_country_code\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    },
    {
     "title": "Requests by Country (Latency)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "database": "default",
       "dateTimeColDataType": "date",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    geo_country_code,\n    median(0.50)(request_time_ms) AS p50\nFROM $table\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                   == $env,                  $env)\n  $conditionalTest(AND hostname              == $hostname,             $hostname)\n  $conditionalTest(AND ic_subnet_id          == $subnet_id,            $subnet_id)\n  $conditionalTest(AND ic_node_id            == $replica_id,           $replica_id)\n  $conditionalTest(AND ic_canister_id        == '$canister_id',        $canister_id)\n  $conditionalTest(AND geo_country_code      == $client_country_code,  $client_country_code)\n  $conditionalTest(AND status                IN ($status_code),        $status_code)\n  $conditionalTest(AND is_bot                == $is_bot,               $is_bot)\nGROUP BY t, geo_country_code\nORDER BY t",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 30) * 30) * 1000 as t,\n    geo_country_code,\n    median(0.50)(request_time_ms) AS p50\nFROM default.http_access\nWHERE\n  date >= toDateTime(1724659067) AND date <= toDateTime(1724669867)\n   AND env                   == 'prod' \n   \n   \n   \n   \n   \n   AND status                IN (451) \n   \nGROUP BY t, geo_country_code\nORDER BY t",
       "round": "0s",
       "table": "http_access"
      }
     ]
    }
   ]
  }
 ]
}