{
 "title": "Subnets",
 "tags": [
  "Boundary Node",
  "Clickhouse"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "Production : prod, Development : dev"
   },
   {
    "name": "subnet_id",
    "label": "Subnet ID",
    "query": "SELECT\n DISTINCT ic_subnet_id\nFROM\n $table_subnets\nWHERE\n date >= ${__from:date:seconds}\n AND\n date <= ${__to:date:seconds}\n AND\n ic_request_type != ''\n AND\n ic_subnet_id != ''\n"
   },
   { "name": "table_subnets", "query": "http_access_by_subnet" },
   { "name": "table_canisters", "query": "http_access_by_canister" },
   {
    "name": "request_type",
    "label": "Request Type",
    "query": "SELECT\n DISTINCT ic_request_type\nFROM\n $table_subnets\nWHERE\n date >= ${__from:date:seconds}\n AND\n date <= ${__to:date:seconds}\n AND\n ic_subnet_id = '${subnet_id}'\n AND\n ic_request_type != ''\n"
   },
   {
    "name": "datasource",
    "query": "vertamedia-clickhouse-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  uniq(ic_node_id)\nFROM $table_subnets\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_subnet_id    =  '$subnet_id',       $subnet_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\n",
     "rawQuery": "SELECT\n  uniq(ic_node_id)\nFROM http_access_by_subnet\nWHERE\n  date >= toDateTime(1683994111) AND date <= toDateTime(1684080511)\n   AND env             =  'prod' \n   AND ic_subnet_id    =  'tdb26-jop6k-aogll-7ltgs-eruif-6kk7m-qpktf-gdiqx-mxtrf-vb5e6-eqe' \n   \n  AND ic_request_type != ''",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Unique Clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT uniqCombinedMerge(unique_ips) AS \"By IP\", uniqCombinedMerge(unique_senders) AS \"By SenderID\"\nFROM $table_subnets\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_subnet_id    =  '$subnet_id',       $subnet_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''",
     "rawQuery": "SELECT uniqCombinedMerge(unique_ips) AS \"By IP\", uniqCombinedMerge(unique_senders) AS \"By SenderID\"\nFROM http_access_by_subnet\nWHERE\n  date >= toDateTime(1683993267) AND date <= toDateTime(1684079667)\n   AND env             =  'prod' \n   AND ic_subnet_id    =  'tdb26-jop6k-aogll-7ltgs-eruif-6kk7m-qpktf-gdiqx-mxtrf-vb5e6-eqe' \n   \n  AND ic_request_type != ''",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  sum(request_size_sum) / (${__to:date:seconds} - ${__from:date:seconds}) * 8 AS In,\n  sum(response_size_sum) / (${__to:date:seconds} - ${__from:date:seconds}) * 8 AS Out\nFROM $table_subnets\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_subnet_id    =  '$subnet_id',       $subnet_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\n",
     "rawQuery": "SELECT\n  sum(request_size_sum) / (1684080224 - 1683993824) * 8 AS In,\n  sum(response_size_sum) / (1684080224 - 1683993824) * 8 AS Out\nFROM http_access_by_subnet\nWHERE\n  date >= toDateTime(1683993973) AND date <= toDateTime(1684080373)\n   AND env             =  'prod' \n   AND ic_subnet_id    =  'tdb26-jop6k-aogll-7ltgs-eruif-6kk7m-qpktf-gdiqx-mxtrf-vb5e6-eqe' \n   \n  AND ic_request_type != ''",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Canisters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  uniq(ic_canister_id)\nFROM $table_canisters\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_subnet_id    =  '$subnet_id',       $subnet_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\n",
     "rawQuery": "SELECT\n  uniq(ic_canister_id)\nFROM http_access_by_canister\nWHERE\n  date >= toDateTime(1683994299) AND date <= toDateTime(1684080699)\n   AND env             =  'prod' \n   AND ic_subnet_id    =  'tdb26-jop6k-aogll-7ltgs-eruif-6kk7m-qpktf-gdiqx-mxtrf-vb5e6-eqe' \n   \n  AND ic_request_type != ''",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Data Transferred",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  sum(request_size_sum) AS In,\n  sum(response_size_sum) AS Out\nFROM $table_subnets\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_subnet_id    =  '$subnet_id',       $subnet_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\n",
     "rawQuery": "SELECT\n  sum(request_size_sum) AS In,\n  sum(response_size_sum) AS Out\nFROM http_access_by_subnet\nWHERE\n  date >= toDateTime(1683993802) AND date <= toDateTime(1684080202)\n   AND env             =  'prod' \n   AND ic_subnet_id    =  'ryjl3-tyaaa-aaaaa-aaaba-cai' \n   \n  AND ic_request_type != ''",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests by Type (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ic_request_type,\n    countMerge(request_count) / ($__interval_ms / 1000)\nFROM $table_subnets\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_subnet_id    =  '$subnet_id',       $subnet_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\nGROUP BY t, ic_request_type\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n    ic_request_type,\n    countMerge(request_count) / (300000 / 1000)\nFROM http_access_by_subnet\nWHERE\n  date >= toDateTime(1706537121) AND date <= toDateTime(1706623521)\n   AND env             =  'prod' \n   AND ic_subnet_id    =  'tdb26-jop6k-aogll-7ltgs-eruif-6kk7m-qpktf-gdiqx-mxtrf-vb5e6-eqe' \n   \n  AND ic_request_type != ''\nGROUP BY t, ic_request_type\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "-- Calculating all quantiles in one go is much faster\nSELECT\n  t,\n  q[1] AS p50,\n  q[2] AS p95,\n  q[3] AS p99\nFROM (\n SELECT\n     $timeSeries as t,\n     quantilesMerge(0.50, 0.95, 0.99)(request_time_ms) AS q\n FROM $table_subnets\n WHERE\n   $timeFilter\n   $conditionalTest(AND env             =  '$env',             $env)\n   $conditionalTest(AND ic_subnet_id    =  '$subnet_id',       $subnet_id)\n   $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n   AND ic_request_type != ''\n GROUP BY t\n ORDER BY t\n)",
     "rawQuery": "\nSELECT\n  t,\n  q[1] AS p50,\n  q[2] AS p95,\n  q[3] AS p99\nFROM (\n SELECT\n     (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n     quantilesMerge(0.50, 0.95, 0.99)(request_time_ms) AS q\n FROM http_access_by_subnet\n WHERE\n   date >= toDateTime(1684058254) AND date <= toDateTime(1684144654)\n    AND env             =  'prod' \n    AND ic_subnet_id    =  'tdb26-jop6k-aogll-7ltgs-eruif-6kk7m-qpktf-gdiqx-mxtrf-vb5e6-eqe' \n    \n   AND ic_request_type != ''\n GROUP BY t\n ORDER BY t\n)",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Requests by Type (p95 Latency)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ic_request_type,\n    quantileMerge(0.95)(request_time_ms)\nFROM $table_subnets\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_subnet_id    =  '$subnet_id',       $subnet_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\nGROUP BY t, ic_request_type\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n    ic_request_type,\n    quantileMerge(0.95)(request_time_ms)\nFROM http_access_by_subnet\nWHERE\n  date >= toDateTime(1683993397) AND date <= toDateTime(1684079797)\n   AND env             =  'prod' \n   AND ic_subnet_id    =  'tdb26-jop6k-aogll-7ltgs-eruif-6kk7m-qpktf-gdiqx-mxtrf-vb5e6-eqe' \n   \n  AND ic_request_type != ''\nGROUP BY t, ic_request_type\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Request Origins",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    geo_country_code AS Country,\n    countMerge(request_count) AS TotalRequests\nFROM $table_subnets\nWHERE\n  $timeFilter\n  $conditionalTest(AND env             =  '$env',             $env)\n  $conditionalTest(AND ic_subnet_id    =  '$subnet_id',       $subnet_id)\n  $conditionalTest(AND ic_request_type IN ($request_type),    $request_type)\n  AND ic_request_type != ''\nGROUP BY Country",
     "rawQuery": "SELECT\n    geo_country_code AS Country,\n    countMerge(request_count) AS TotalRequests\nFROM http_access_by_subnet\nWHERE\n  date >= toDateTime(1709724372) AND date <= toDateTime(1709810772)\n   AND env             =  'prod' \n   AND ic_subnet_id    =  'tdb26-jop6k-aogll-7ltgs-eruif-6kk7m-qpktf-gdiqx-mxtrf-vb5e6-eqe' \n   \n  AND ic_request_type != ''\nGROUP BY Country",
     "round": "0s",
     "table": "http_access"
    }
   ]
  }
 ]
}