[package]
name = "ic-crypto-test-utils-csp"
description = "Test utilities for crypto service provider"
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
ic-crypto-internal-csp = { path = "../../internal/crypto_service_provider" }
ic-crypto-internal-threshold-sig-bls12381 = { path = "../../internal/crypto_lib/threshold_sig/bls12_381" }
ic-crypto-internal-types = { path = "../../internal/crypto_lib/types" }
ic-types = { path = "../../../types/types" }
mockall = { workspace = true }