= ckERC20 +

The ckETH minter canister is extended to convert a selected subset of Ethereum ERC-20  tokens to ckERC20 and back, where each ckERC20 is a token issued on the Internet Computer that is backed 1:1 by the corresponding ERC-20 token. For each ckERC20 token, the minter works with a dedicated link:../../../rosetta-api/icrc1/README.md[Ledger Canister], handling the ckERC20 token transfers and with https://internetcomputer.org/https-outcalls[HTTP outcalls], to query multiple JSON-RPC providers to interact with the Ethereum blockchain.

NOTE: An ERC-20 token denotes a fungible token on the Ethereum blockchain that follows the https://eips.ethereum.org/EIPS/eip-20[ERC-20 token standard].

== Supported ERC-20 tokens


|===
|Ethereum Chain | ERC-20 token symbol | ERC-20 smart contract address

|link:https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-1.json[Ethereum Mainnet]
|USDC
|https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48[0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48]
|===

== Architecture

The ckERC20 implementation consists of a suite of canisters:

. The existing ckETH minter is responsible for handling ERC-20 deposits and withdrawal requests. Each ERC-20 deposit and ckERC-20 withdrawal will result in a transaction on the ledger associated with that ERC-20 token. We reuse the ckETH minter to deal with ckERC-20 because a ckERC-20 withdrawal involves issuing an Ethereum transaction where the transaction fee is paid by the sender in ETH: ETH is needed to pay for ERC-20 transfers! Another canister would have another Ethereum address (because it would have another threshold ECDSA public key) and so that address would first need some ETH (which involves some costly Ethereum transfers) from the ckETH minter before being able to issue any ERC-20 transactions.
. One ICRC1 ledger suite (ledger, index-ng, archive(s)) per ERC-20 token:
.. ckERC20 ledger is the canister tracking movements of the ckETH token and handling token transfer requests.
.. ckERC20 archive is the canister storing archived ckERC20 transactions. ckERC20 ledger creates this canister on demand.
.. ckERC20 index is the canister indexing ckERC20 transactions by account.
. Ledger suite orchestrator that controls each ICRC1 ledger suite to manage them in a scalable way. This canister will be controlled by the NNS and will be responsible for
.. Spawning a new ICRC ledger suite when adding a new ERC-20 token (via NNS proposal)
.. Upgrading all managed canisters (ledgers, indexes, archives) to some given version (via NNS proposal)
.. Cycles top-up of all managed canisters.


== Deposit: ERC20 to ckERC20

The ERC-20 deposit flow is similar to the ckETH deposit flow in that deposits will transit via a helper smart contract to be able to bind an Ethereum transaction with an IC principal.

The ERC-20 -> ckERC-20 flow involves the following steps:

. The user submits an Ethereum transaction calling the `approve` function of the ERC-20 smart contract to allow the helper smart contract address to use some of the user’s funds. Depending on the amount specified, additional deposits may not need to be approved beforehand. The `approve` function can be invoked directly on the the contrat's Etherscan page after connecting any of Web3-capable wallets.
. The user calls the `deposit` method of the helper smart contract (just as `approve` this method can be called from contrat's Ethersacn page) specifying
.. The ERC-20 smart contract address. This identifies the ERC-20 token being deposited.
.. The amount of ERC-20 tokens being deposited.
.. The IC principal to which the amount of ckERC-20 should be minted (the simplest way to convert your IC principal to the smart contract argument is to use the link:https://sv3dd-oaaaa-aaaar-qacoa-cai.raw.icp0.io/dashboard[minter dashboard]).
. The helper smart contract does the following steps within the *same* Ethereum transaction
.. Ensure that the ERC-20 token is allowed
.. Call `transferFrom` on the ERC-20 smart contract to transfer the given amount of ERC-20 tokens from the user’s address to the minter’s address. (This requires that the smart contract’s address was previously approved as in step 2).
.. Emits the `ReceiveErc20(address,address,uint,bytes32)` event
... The first `address` argument is the ERC-20 smart contract Ethereum address.
... The second `address` argument is the source Ethereum address.
... The `uint` argument is the deposit value.
... The `bytes32` argument encodes the receiver of ckERC20 on the IC.
. The scrapping of the logs will be done as in ckETH, meaning that ckETH minter executes the following steps on a timer:
.. Query the latest finalized block number using the eth_getBlockByNumber RPC endpoint. If the finalized block number hasn't changed since the last timer execution, skip the rest of the timer logic.
.. Use the `eth_getLogs` RPC endpoint to fetch the helper smart contract logs from the previous finalized block number to the block number obtained at the previous step. The response is an array of events, where each event includes in particular the transaction hash `transactionHash` and the log entry index `logIndex`. Parse `ReceiveEth` events contained in the logs.
.. For each new event, if the `transactionHash` was not seen before (minter keeps track of minted transactions), check that the sender of the transaction is not on the blocklist and mint ckERC20 and include the transaction hash and the log entry index in the ckERC-20 mint transaction memo (ICRC-1 ledger feature). Add the `transactionHash` to the list of seen transactions kept by the minter. If the sender of the transaction was a blocked address, then the minter does not mint ckERC20, but still marks the transaction hash as seen.

.Deposit on Sepolia BSE -> ckBSE
====
To make things more concrete, we consider a fictive ERC-20 smart contract with the symbol `BSE` installed at https://sepolia.etherscan.io/address/0xb6bc16189ec3d33041c893b44511c594b1736b8a[0xB6bC16189EC3d33041C893B44511C594B1736B8A]. This is a standard https://github.com/OpenZeppelin/openzeppelin-contracts/blob/61117c4db8497ba489d5e1e127565a011ed6907a/contracts/token/ERC20/ERC20.sol[OpenZeppelin ERC-20 smart contract] where a `mint` function was added to be able to add some supply for testing purposes. For this example, we use the helper smart contract installed at https://sepolia.etherscan.io/address/0xb9b002e70adf0f544cd0f6b80bf12d4925b0695f[0xb9b002e70adf0f544cd0f6b80bf12d4925b0695f]. Converting 10 BSE to 10 ckBSE involves the following steps:

. The user approves the helper smart contract to use some of their BSE tokens. Depending on the approved amount and the afterward deposited amount, this could be a one-time transaction per deposit or, if the approved amount is high enough, the same approval could be re-used for several deposits from that user and ERC-20 token.
.. Transaction https://sepolia.etherscan.io/tx/0x8a80edf9b95c42bdc2467df850616e7fb4544f5868c1398b95a49e4f8c9832c3[0x8a80edf9b95c42bdc2467df850616e7fb4544f5868c1398b95a49e4f8c9832c3] to approve 10 BSE tokens to be used by the helper smart contract.
.. Gas: 46_930
. The user calls the `deposit` method of the helper smart contract to transfer the BSE tokens to the minter's address. This is a one-time transaction per deposit.
.. Transaction https://sepolia.etherscan.io/tx/0xa4fdbaa81b22827bbe08586607c6f13aa41303eb11f88fc514daca8ff785314c[0xa4fdbaa81b22827bbe08586607c6f13aa41303eb11f88fc514daca8ff785314c] to deposit 10 BSE tokens to the minter's address.
.. Gas: 42_141

Assuming a gas price of 25 gwei/gas and 2200 USD/ETH, a deposit costs a bit less than 5 USD that breaks as follows

. 2.6 USD for the approval transaction
. 2.3 USD for the deposit transaction

The exact cost will depend on the gas cost of the involved ERC-20 operations (`approve`, `transferFrom`) and will vary between each ERC-20 smart contract.

====

== Withdrawal: ckERC20 to ERC20

The ckERC-20 → ERC-20 conversion flow involves the following steps:

. The user calls the ckETH ledger to approve the minimum withdrawal amount to the primary Minter account (needed to pay transaction fees).
[source,shell]
----
dfx canister --network ic call ledger icrc2_approve "(record { spender = record { owner = principal \"$(dfx canister id minter --network ic)\" }; amount = 1_000_000_000_000_000_000:nat })"
----
. The user calls the ckERC20 ledger to approve the desired amount to the primary Minter account. Note that the ledger id of the corresponding ckERC20 token is returned by the `get_minter_info` query on the minter and the `LARGE_AMOUNT_CK_TOKEN` should take the amount of decimals corresponding to the ERC20 contract being used.
[source,shell]
----
dfx canister --network ic call CKERC20_LEDGER icrc2_approve "(record { spender = record { owner = principal \"$(dfx canister id minter --network ic)\" }; amount = LARGE_AMOUNT_CK_TOKEN:nat })"
----
. The user calls the `withdraw_erc20` endpoint on the ckETH minter that specifies
.. ERC-20 token: e.g., USDC,
.. the desired withdrawal amount
.. the destination address.
[source,shell]
----
dfx canister --network ic call minter withdraw_erc20 "(record {ckerc20_ledger_id = principal \"CKERC20_LEDGER\"; amount = AMOUNT_CK_TOKEN:nat; recipient = \"ETH_ADDRESS\"})"
----
. The minter checks the desired destination address against the blocklist, and rejects the request if the destination is blocked.
. The ckETH minter attempts to burn the minimum withdrawal amount of ckETH (currently set to `30_000_000_000_000_000` wei corresponding to roughly 75 USD). We need some ETH to pay for the transaction fee and since the transaction has 0 ETH value we need some amount of ckETH up-front. The amount chosen is to allow the same behavior as with the  ckETH → ETH conversion and avoid stuck transactions as much as possible. Any error at this point (e.g., insufficient funds) terminates the withdrawal flow.
. The ckETH minter attempts to burn the specified token amount from the user account on the ckERC20 ledger. If the burn succeeds, the minter schedules a withdrawal task and uses the burn transaction index as the request identifier. If the burn fails (e.g., insufficient funds), the minter schedules the reimbursement of the burnt ckETH amount from the previous step.
. The ckETH minter estimates the gas needed for this transaction. Contrary to the ckETH withdrawal flow, where the gas consumed is fixed at `21_000`, this transaction involves interacting with the ERC-20 smart contract by calling the `transfer` method. To simplify things, we currently favor the approach of taking a crude upper bound per ERC-20 tokens for all withdrawals for that token. The minter will reimburse any unused transaction fee once the transaction is finalized.
. Estimate current gas price (as done currently by the ckETH minter)
. The transaction fee estimate is then (gas limit estimate * gas price estimate). The transaction fee must be less than the ckETH amount burned before, otherwise the transaction needs to be put back in the queue (if it was not sent before) or the minter is stuck (in case of a resubmission)
. The ckETH minter constructs a 0-ETH amount transaction containing the ERC-20 withdrawal (in `data` field) to the Ethereum network.
. The user can query the withdrawal status using the identifier from the erc20_withdraw response.
. Once the transaction gets enough confirmations, the minter considers the transaction finalized.
. The minter retrieves the receipt of the finalized transaction (as done currently by the ckETH minter) and reimburses the overpaid ckETH transaction fee.
