= Ledger Suite Orchestrator

The ledger suite orchestrator manages ledger suites of all ckERC20 tokens.
Each ledger suite, one for each ckERC20 token, consists of multiple canisters:
one ledger; one index; and zero, one or multiple archives.

The ledger suite orchestrator has the following 3 main responsibilities:

. Create a new ledger suite for a new ckERC20 token with a single NNS proposal.
. Upgrade managed canisters with a single NNS proposal.
. Top up the managed canisters with cycles.

== Architecture

* The ledger suite orchestrator is controlled by the NNS.
* Any state change (adding a new ERC-20 token/upgrade) is controlled by the NNS.
* The NNS also controls all created children canisters to allow for emergency upgrades targeting specific canisters.
* The ledger suite orchestrator (LSO) embeds the following wasms:
** The ledger wasm (using the `U256` variant).
** The index-ng wasm (using the `U256` variant).
** The archive wasm (using the `U256` variant).
* For simplicity, the ledger suite orchestrator does not differentiate between the ckERC20 tokens it manages. In particular the `U256` variant is used for all wasms.

[TIP]
.Who controls who?
====

....
                                                      ┌───────────┐
                                                      │           │
┌──────────────────────────┬──────────────────────────┤    NNS    ├──────────────┐
│                          │                          │           │              │
│                          │                          └─────┬─────┘              │
│                          │                                │                    │
│      ┌─────────┐         │   ┌─────────┐                  │                    │
│      │ ckUSDC  │         │   │ ckUSDT  │                  │                    │
├─────►│         │◄───┐    ├──►│         │◄───┐             │                    │
│      │ ledger  │    │    │   │ ledger  │    │             │                    │
│      └─────────┘    │    │   └─────────┘    │             │                    │
│                     │    │                  │             │                    │
│                     │    │                  │             ▼                    ▼
│      ┌─────────┐    │    │   ┌─────────┐    │       ┌───────────┐        ┌───────────┐
│      │ ckUSDC  │    │    │   │ ckUSDT  │    │       │           │        │           │
├─────►│         │◄───┤    ├──►│         │◄───┼───────┤    LSO    ├─xxxxx─►│   minter  │
│      │ index   │    │    │   │ index   │    │       │           │        │           │
│      └─────────┘    │    │   └─────────┘    │       └─────┬─────┘        └───────────┘
│                     │    │                  │             │
│                     │    │                  │             │
│      ┌─────────┐    │    │   ┌─────────┐    │             │
│      │ ckUSDC  │    │    │   │ ckUSDT  │    │             │
└─────►│         │◄───┤    └──►│         │◄───┘             │
       │ archive │    │        │ archive │                  │
       └─────────┘    │        └─────────┘                  │
                      │                                     │
                      └─────────────────────────────────────┘
....

Legend:

. A -> B: canister A controls canister B
. LSO ─xxx─► minter: LSO notifies minter of a new ckERC20 token
====

[TIP]
.Lifecycle of a ledger suite
====
To understand how ckERC20 tokens are managed, it's essential to understand the lifecycle of a ledger suite, which is as follows:

. The index canister periodically pulls transactions from the ledger and from the archive canister(s). The ledger and the archive(s) don't know anything about the index canister.
. Once a certain number of transactions on the ledger is reached, specified by `trigger_threshold` in the `archive_options` of the ledger initialization arguments, the ledger will create a new archive canister and hand over control of that newly created canister to the `controller_id` specified in the `archive_options`.
. At that point, once a certain number of transactions on the ledger is reached, specified by `num_blocks_to_archive` in the `archive_options`, the ledger pushes past transactions to the archive canister.
. If the size of the archive canister exceeds a certain threshold, specified by `node_max_memory_size_bytes` in the `archive_options`, the ledger will create a new archive canister as in step 2.

Remarks:

* Upgrading the ledger won't upgrade any spawned archive canisters.
* The initial version (Git hash `4472b0064d347a88649beb526214fde204f906fb`) of the ledger used doesn't use stable memory.
* Both the index canister and archive canisters used in ckERC20 use stable memory. It's therefore possible to configure the `archive_options` in such a way that it will be very unlikely that a second archive canister is ever needed.
====


== Adding a new ckERC20 token

Adding a new ERC-20 token involves an NNS upgrade proposal for the ledger suite orchestrator (like https://dashboard.internetcomputer.org/proposal/129750[129750]) specifying the following:

* Identifier for the new ERC-20 token: this is the pair Ethereum chain ID (`1` for Ethereum mainnet or `11155111` for Ethereum Testnet Sepolia) and the ERC-20 smart contract Ethereum address.
* Initialization args for the ICRC ledger
* Wasm hash of the ledger
* Wasm hash of the index

The orchestrator verifies that the wasm hashes are known and then tries to do the following on a timer:

. Create a new canister for the ledger, which is controlled by the ledger suite orchestrator itself and by all principals specified in `more_controller_ids` in the initialization arguments.
. Install wasm module for the ledger with the given initialization arguments. In particular, the `archive_options` are decided by the orchestrator and are not part of the NNS proposal.
. Create a new canister for the index, which is controlled by the ledger suite orchestrator itself and by all principals specified in `more_controller_ids` in the initialization arguments.
. Install wasm module for the index canister. The init args only need to contain the canister ID of the ledger.
. Notify the minter, identified through the field `minter_id` in the ledger suite orchestrator initialization arguments, of the newly created ledger ID together with the identifier for the ERC-20 token (so that the minter can adapt its scraping logic to additionally retrieve the logs for the added ERC-20 token). This update endpoint on the minter is restricted to the ledger suite orchestrator ID.

In case any operation fails, retry on the next timer starting from the previously failing step.

[TIP]
.Which ckERC20 tokens are supported?
====
Once the proposal to add a new ckERC20 token is executed, the canister IDs of the created ledger and index will be added to the list of `managed_canisters`, which can be retrieved by querying the
`get_orchestrator_info` endpoint.

[source,shell]
----
dfx canister --network ic call orchestrator get_orchestrator_info
----
====

== Upgrading managed ledger suites

Upgrading all existing ledger suites managed by the orchestrator involves an NNS upgrade proposal for the ledger suite orchestrator specifying the following:

. Optional wasm hash of the ledger
. Optional wasm hash of the index
. Optional wasm hash of the archive

The orchestrator verifies that the wasm hashes when present are known and then tries to do the following for every managed ERC-20 token on a timer:

. stop/upgrade/start index canister if a wasm hash was specified;
. stop/upgrade/start ledger if a wasm hash was specified;
. stop/upgrade/start archive canister if a wasm hash was specified. This also involves contacting the ledger to see if any archive canisters were created.

In case any operation fails, a retry will be initiated on the next timer, starting from the previously failing step.

Note that the orchestrator does not even check whether the current installed version is already the one given in the proposal, since it's expected that this will not be the case most of the time.


== Cycles top-up of managed ledger suites

On a timer, the ledger suite orchestrator tops up all managed canisters using a simple threshold strategy. The exact threshold and the top-up amount is specified in the ledger suite orchestrator initialization argument `CyclesManagement`. The topping-up strategy is as follows:

. The ledger suite orchestrator is monitored by the cycles monitor canister. The orchestrator will need a fairly big chunk of cycles and an alert will be fired when it does not have enough cycles.
. On a timer, it ensures that each managed canister has a cycles amount above the hard-coded threshold. This involves also contacting the ledger to see if any archive canisters were created, which is done on a separate timer.
. The threshold is set high enough so that the ledger always has sufficiently many cycles to be able to spawn a new archive canister and that all canisters have sufficiently many cycles to be able to be upgraded at any time.
