= SetupOS

== Introduction

SetupOS is an operating system designed for installing both the HostOS (hypervisor) and GuestOS (virtual machine). It enables node providers/operators to independently install their nodes.

== SetupOS Installation

To install SetupOS, node operators follow these steps:

1. Obtain a SetupOS image and download it onto a bootable USB drive.
2. Add the necessary configurations to the image.
3. Plug the USB drive into the node machine and boot from the USB.

SetupOS will then perform validation tasks, prepare the hardware components, and install the HostOS and GuestOS. Once completed, the machine will reboot into the HostOS.

For more information on the onboarding and installation process, as well as the hardware and networking requirements, https://wiki.internetcomputer.org/wiki/Node_Provider_Onboarding#[visit the Node Provider Onboarding Wiki].

== Building SetupOS

To build a SetupOS image, refer to the link:../README.adoc[IC-OS README]

== Under the hood: Installation

The SetupOS installation is initiated by the systemd service unit file `setupos.service`. This service is of type idle, which means the installation is triggered only after every other unit has either completed or started.

The installation process consists of multiple Shell and Python scripts, which can be found in the following directory:

  ic-os/setupos/rootfs/opt/ic/bin

The sequence of the scripts is defined in the main installation script, `setupos.sh`. The order of execution is as follows:

  hardware.sh  # Verifies the system's hardware components
  network.sh   # Tests network connectivity and reachability of the NNS
  disk.sh      # Purges existing LVM configurations and partitions
  hostos.sh    # Installs and configures the HostOS operating system
  guestos.sh   # Installs and configures the GuestOS operating system
  devices.sh   # Handles the HSM
