#!/usr/bin/env bash

set -exuo pipefail

ROOT_DIR=$(git rev-parse --show-toplevel)
cd "$ROOT_DIR/rs" || exit 1

DFX_BINS=(
    replica
    ic-starter
    ic-btc-adapter
    canister_sandbox
    sandbox_launcher
)

function bins() {
    for c in "${DFX_BINS[@]}"; do
        echo -n " --bin $c"
    done
}

cargo build --release $(bins)
