#!/usr/bin/env bash

set -exuo pipefail

# Remove ~/.nix-profile/bin from the PATH to use native cargo
PATH=$(
    p=$(echo "$PATH" | tr ":" "\n" | grep -v "/.nix-profile/" | tr "\n" ":")
    echo "${p%:}"
)
export PATH=/opt/cargo/bin:$PATH
ROOT_DIR=$(git rev-parse --show-toplevel)
CI_PROJECT_DIR=${CI_PROJECT_DIR:-$ROOT_DIR}

rm -rf "$ROOT_DIR/artifacts/canisters"
mkdir -p "$ROOT_DIR/artifacts/canisters"
cd "$ROOT_DIR/rs" || exit 1

wasm_canister_build_list=(
    registry-canister
    governance-canister
    root-canister
    genesis-token-canister
    ledger-canister
    cycles-minting-canister
    identity-canister
    nns-ui-canister
    xnet-test-canister
    statesync-test-canister
    memory-test-canister
)
declare -A wasm_canister_copy_list=(
    ["cow_safety.wasm"]="rs/tests/src"
    ["counter.wat"]="rs/workload_generator/src"
)

function wasm_canisters_cargo_args() {
    # returns a list of wasm_canisters prefixed with "--bin"
    for c in "${wasm_canister_build_list[@]}"; do
        echo -n " --bin $c"
    done
}

# shellcheck disable=SC2046  # Intended splitting of $(wasm_canisters_cargo_args)
cargo build --target wasm32-unknown-unknown --release $(wasm_canisters_cargo_args)

# Lifeline canister needs special handling:
cd "$ROOT_DIR/rs/nns/handlers/lifeline" || exit 1
cargo build --target wasm32-unknown-unknown
ic-cdk-optimizer -o "$ROOT_DIR/artifacts/canisters/lifeline.wasm" gen/lifeline.wasm

echo "Building of Wasm canisters finished"

cd "$ROOT_DIR" || exit 1

for wasm in "${wasm_canister_build_list[@]}"; do
    src_filename="$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/$wasm.wasm"
    if [[ -r "$src_filename" ]]; then
        ic-cdk-optimizer -o "artifacts/canisters/$wasm.wasm" "$src_filename"
    else
        echo "ERROR: target canister Wasm binary does not exist: ${src_filename}"
        exit 1
    fi
done

# Copy/optimize prebuilt canisters
for can in "${!wasm_canister_copy_list[@]}"; do
    src_filename="${wasm_canister_copy_list[$can]}/$can"
    if [[ $can == *.wasm ]]; then
        ic-cdk-optimizer -o "$ROOT_DIR/artifacts/canisters/$can" "$ROOT_DIR/$src_filename"
    elif [[ $can == *.wat ]]; then
        cp "$ROOT_DIR/$src_filename" "$ROOT_DIR/artifacts/canisters/$can"
    else
        echo "ERROR: unknown (not .wat or .wasm) canister type: ${src_filename}"
        exit 1
    fi
done

sha256sum artifacts/canisters/*

gzip -f --no-name artifacts/canisters/*
