#!/usr/bin/env bash

set -exuo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
TAG=$(openssl rand -hex 4)

"$REPO_ROOT"/gitlab-ci/docker/docker-build-local-image.sh

cd "$REPO_ROOT"
docker image build -t ic-build-src:$TAG -f- . <<EOF
FROM dfinity/ic-build:latest
COPY --chown=ubuntu:ubuntu . /ic
EOF

export IMAGE=ic-build-src:$TAG
"$REPO_ROOT"/gitlab-ci/tools/docker-run /ic/gitlab-ci/tools/build-ic "${1:--a=b,c,i}"

if docker volume inspect "ic-artifacts${CI_JOB_ID:-}" 2>/dev/null; then
    mkdir -p artifacts
    cd artifacts

    # docker doesn't seem to provide means of getting data from the volume directly
    # we need to run a container with that volume and copy the data from the container
    DID=$(docker run --rm -it -d -v "ic-artifacts${CI_JOB_ID:-}":/artifacts $IMAGE sleep 300)
    docker cp $DID:/artifacts docker-build-ic
    docker rm -f $DID
    docker volume rm -f "ic-artifacts${CI_JOB_ID:-}"
fi

echo "See artifacts in artifacts directory"
