#!/usr/bin/env bash

set -euo pipefail

print_usage() {
    cat >&2 <<-USAGE
	usage: $0 [-h] [-c <git revision>] [-u <base url>] files...
		Download files from https://download.dfinity.systems
		Options:
			-h  - print this help message
			-c <git revision> - git revision to use, default to autodetect from \$CI_COMMIT_SHA or from the current working tree
			-u <url> - base url to download from. Default is to autodetect.
			files... - list of files to download.
USAGE
}

download_file() {
    if curl --fail --retry 5 --retry-delay 10 "${BASE_URL}/ic/${GIT_COMMIT}/$1"; then
        return
    fi
    echo "Can't download $1" >&2
    exit 1
}

GIT_COMMIT="${CI_COMMIT_SHA:-$(git rev-parse HEAD)}"

while getopts 'hc:u:' flag; do
    case "${flag}" in
        c)
            GIT_COMMIT="${OPTARG}"
            ;;
        u)
            BASE_URL="${OPTARG}"
            ;;
        h | *)
            print_usage
            exit 1
            ;;
    esac
done
shift $(($OPTIND - 1))

if [ -z "${GIT_COMMIT:-}" ]; then
    echo "Can't detect git revision" >&2
    print_usage
    exit 1
fi

if [ -z "${BASE_URL:-}" ]; then
    BASE_URL="https://download.dfinity.systems"
    PROXY_URL="http://download.proxy-global.dfinity.network:8080"
    if curl --connect-timeout 5 --head "${PROXY_URL}" >&2; then
        BASE_URL="${PROXY_URL}"
    fi
fi

for F in $@; do
    download_file "${F}"
done
