#!/usr/bin/env bash

set -euo pipefail

print_usage() {
    cat >&2 <<-USAGE
	usage: $0 [-h] [-c <git revision>] [-u <base url>] files...
		Download files from https://download.dfinity.systems
		Options:
			-h  - print this help message
			-c <git revision> - git revision to use, default to autodetect from \$CI_COMMIT_SHA or from the current working tree
			-u <url> - base url to download from. Default is ${BASE_URL}
			files... - list of files to download.
USAGE
}

download_file() {
    for P in blessed/ic ic; do
        if curl --fail --retry 5 --retry-delay 10 "${BASE_URL}/${P}/${GIT_COMMIT}/$1"; then
            return
        fi
    done
    echo "Can't download $1" >&2
    exit 1
}

BASE_URL="http://download.proxy.dfinity.systems:8080"
GIT_COMMIT="${CI_COMMIT_SHA:-$(git rev-parse HEAD)}"

while getopts 'hc:u:' flag; do
    case "${flag}" in
        c)
            GIT_COMMIT="${OPTARG}"
            ;;
        u)
            BASE_URL="${OPTARG}"
            ;;
        h | *)
            print_usage
            exit 1
            ;;
    esac
done
shift $(($OPTIND - 1))

if [ -z "${GIT_COMMIT:-}" ]; then
    echo "Can't detect git revision" >&2
    print_usage
    exit 1
fi

for F in $@; do
    download_file "${F}"
done
