= CLI to Generate Upgrade Proposals for NNS-controlled canisters

== About

This is a command-line tool for to automatically generate upgrade proposals for NNS-controlled canisters, like ckBTC or ckETH.

IMPORTANT: The part about the motivation of the proposal is not automated and must be filled out manually.

== Usage

.Generate a proposal to upgrade the ckETH ledger like in link:https://dashboard.internetcomputer.org/proposal/126397[126397]
====
[source,shell]
----
mkdir ~/proposal
bazel run //rs/cross-chain/proposal-cli:make_proposal -- upgrade cketh-ledger --from 5ecbd59c6c9f9f874d4340f9fbbd96af07aa2576 --to 6a8e5fca2c6b4e12966638c444e994e204b42989 --args "(variant {Upgrade})" --output-dir ~/proposal
----
====

=== What it does

. Blobless clone of the IC repo in a temporary directory and checkout the commit specified in `to`.
. Retrieves the mainnet canister ID corresponding to the given canister (`ss2fx-dyaaa-aaaar-qacoq-cai` in the above example)
. Generates the release notes as the output of `git log` between the commits specified in `from` and `to` for the relevant directory (`rs/rosetta-api/icrc1/ledger` in the above example)
. Generates the canister artifacts and computes the hash of the generated compressed wasm.
. Candid encoding of the given uprade arguments or use default empty ones.
. Generates a proposal summary based on the previous information, where only the Motivation section remains to be (manually) filled out.

=== What it doesn't do (yet)

. Retrieve last proposal that was executed for the given canister.
. Generates `ic-admin` command to run.
