# Modified from https://hub.docker.com/_/rust
FROM rust:1.71.0-buster as builder
RUN apt-get update && apt-get install -y protobuf-compiler
WORKDIR /src
COPY . .
WORKDIR /src/rs/observability/prometheus_config_updater
RUN cargo build --target-dir ./target --release
RUN sha256sum target/release/prometheus_config_updater

FROM debian:buster
# https://github.com/docker-library/docs/pull/1710/files/e57957756b61481bbd586d08c2fbe565753518c0
# For why this line is commented
RUN apt-get update && apt-get install -y libssl1.1 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /src/rs/observability/prometheus_config_updater/target/release/prometheus_config_updater /usr/local/bin/prometheus_config_updater
CMD ["prometheus_config_updater"]
