#!/bin/sh

# Set up dm-verity for root filesystem

set -e

prereqs() {
    echo ""
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

# Without this, error exit codes are ignored and the boot continues
trap 'panic "fatal: verity-root failed"' ERR

. /scripts/functions

echo "Original root: ${ROOT}"

open_rootfs

echo "ROOT=/dev/mapper/vroot" >/conf/param.conf

exit 0
