= IC_BackupPod_Behind
:icons: font
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

== Triggered by

One of the backup pods syncing artifacts from the NNS and recovering the state reports restored heights which are too old.

== Impact

The corresponding backup pod is not contributing to NNS recovery anymore.
As long as it is only one pod there is no immediate danger, but it should still be investigating and fixed ASAP.
The safety buffer is reduced by this and if the issue is applicable to other pods soon it might affect them too.

If all backup pods report this simultaneously, we need to keep in mind that in 24h after the last successful backup (which will most probably not coincide with this alert but lie 8h in the past), the NNS nodes start deleting the backup artifacts, so we need to react quickly.

The immediate functionality of the IC is not affected. There will be no user facing effects.

== Possible causes (non-exhaustive)

- The backup pods are restoring the states slowes than NNS.

== Troubleshooting and remediation

There is not much an on call engineer can do except for immediately notifying the backup pod operators in channel #backup-ops and/or by phone.
Alert owners are members of @dfinity-lab/teams/consensus-owners.

If none of the operators were reachable and this alert is fired _all_ backup pod, the time starts to run out: the replicas delete all artifacts older than 24h.
In this case, please start regularly pulling (at least once every 12h) the content of the folder `/var/lib/ic/backup` from at least 5 NNS replicas, e.g. using `rsync`.
