= IC_DC_Outage
:url-release-dashboard: https://dashboard.mercury.dfinity.systems/network
:url-transport-flows: https://grafana.dfinity.systems/d/HEHymkfGz/ic-health?viewPanel=7&orgId=1

== Triggered by

Less than 50% of replicas in a data center are healthy.

== Impact

No immediate impact, unless multiple data centers are down.

Multiple subnets are missing replicas and, as a result, experiencing
(slightly) reduced block rate and redundancy.

== Possible causes (non-exhaustive)

- Data center outage.

- Network misconfiguration: e.g. data center firewall blocks incoming traffic.

- Peering issue: there may be a peering issue between the data center hosting
  Prometheus and the respective IC DC specifically, meaning that the replicas
  may well be healthy and participating in Consensus.
+
You can check e.g. {url-transport-flows}[this transport flow state chart] for
one of the affected subnets: if the proportion of unhealthy flows is lower than
the proportion of down nodes, then the nodes are likely still healthy, just not
accessible to Prometheus.

== Troubleshooting and remediation

Look up the data center name and details on the {url-release-dashboard}[release
dashboard].

Contact Platform Ops (@doc-ops on Slack) and ask them to investigate.

If this is a data center specific issue, contact the node provider and direct
them to get in touch with the data center operator.
