= IC_Subnet_TooManyInvalidXNetPayloads
:icons: font
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

== Triggered by

The ratio of failed XNet payload validations on the subnet indicated in
the alert was at a level > the equivalent of one replica on the subnet
only sending invalid payloads - some epsilon.

== Impact

Depending on the error rate we see, XNet throughput may be reduced or
even go down to 0 if we have no successful requests.

If the error rate is > 1/3 this could also lead to a safety issue in
case the replicas producing the payloads are acting maliciously.

== Possible causes (non-exhaustive)

- Bug in a recent binary or configuration update

- Dishonest replicas in subnet

== Troubleshooting and remediation

- Check whether there is only one subnet affected, or multiple ones. If
there are multiple subnets affected and those have recently been upgraded
to a new version it may be a bug.

- If this is the only subnet affected, or if there was no upgrade for some
time before the issue started occurring it could be that we have some
malicious replicas in the subnet. Possible checks to confirm such a suspicion
are whether the replicas producing the payloads are all from the same node
provider, or checking whether there is some other weird behavior of the
nodes in question. Possible actions to fix the situation would be replacing
the nodes in the respective subnets.
