= IC_Subnet_LessThanTwoSpares

== Triggered by

The number of running replicas in a subnet is less than 2*f+3 (i.e. 2 replicas
above the 2*f+1 threshold required for the subnet to make progress).

== Impact

If there are still at least 2*f+1 healthy replicas, only finalization rate is
affected (as the number of running replicas drops, the finalization rate goes
down).

If fewer than 2*f+1 replicas are healthy, the subnet is *halted* and can make
no further progress. Canisters on the subnet are no longer processing updates
(but are likely still able to process queries).

== Possible causes (non-exhaustive)

- Is there a rollout that has coincided with another outage, taking too many
  replicas down?

- Have one or more datacenters lost connectivity, power, or another resource
  that affects too many replicas?

- Has planned maintenance work taken out more machines than expected?

- Have a collection of replicas just crashed simultaneously because of a bug
  processing a given input?

- Has there been a recent subnet membership change in the registry that has
  not yet been applied by the subnet?

== Troubleshooting and remediation

If this appears to be a hardware issue you may be able to start additional
replicas on other machines and have them join the same subnet.

If this is a software issue (i.e., replicas are crashing and not restarting,
or crash-looping) you will need to understand the problem.

If it is a bug introduced in the most recent release of the replica you may be
able to roll back to the previous release. Consider whether this will be a
destructive operation or not.

If it is a latent bug that has only just been triggered (i.e., it is present
in past releases) then a fix will need to be developed and deployed.

If this is due to a recent membership change, than it could be the case that
we have already stopped collecting metrics from nodes that were supposed to
be dropped even though subnet membership has not yet changed. This might be
a transient state.
