#!/usr/bin/env bash

set +x

bazel build //rs/... --@rules_rust//:output_diagnostics=true --output_groups=rust_lib_rustc_output,rust_metadata_rustc_output >>.vscode/ra.logs 2>&1 || true

find -print0 -L $PWD/bazel-bin/rs -name '*.rustc-output' | xargs -0 cat
