#!/usr/bin/env python3
#
# Build an IC-OS container filesystem (rootfs-tree.tar) by running the steps of
# its Dockerfile in a KVM microVM, instead of `podman build`.
#
# This needs no root, no user namespaces and no network, only read/write access
# to /dev/kvm (it falls back to QEMU's much slower TCG emulation without it), so
# it can run in the Bazel sandbox and on remote executors:
#
# 1. The base image's root filesystem (flattened by oci_rootfs.py from the image
#    Bazel pulled by digest) is unpacked under fakeroot, together with the build
#    context and the generated steps, and turned into an ext4 disk with
#    `mke2fs -d`, which keeps the owners recorded by fakeroot.
# 2. QEMU boots a kernel (from the GuestOS base image) with that disk as its
#    read-write root and the generated init script as PID 1. The script mounts
#    /proc, /sys, /dev and /run like a container engine would, runs the COPY and
#    RUN steps (planned by dockerfile.py) as root, and writes the resulting
#    filesystem as a tar to a second, raw disk, and its exit status to a third.
# 3. The tar is read back and normalized exactly like the podman export that
#    this replaces (no /run, mtime 0, no user/group names).
#
# For the IC-OS Dockerfiles the result is byte-identical to `podman build`'s. Differences
# that they don't depend on: the steps have no network; /etc/hosts, hostname
# and resolv.conf are regular files (podman bind-mounts the host's during RUN,
# so writes to them don't persist there); `uname -r`, the CPU count and the
# hostname are the VM's; processes a step leaves running are only stopped at the
# end of the build, not after each step.
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tarfile
import tempfile
import threading
from pathlib import Path
from typing import Dict, List, Optional

from toolchains.sysimage.container_context import arrange_context, resolve_file_args
from toolchains.sysimage.dockerfile import Copy, Plan, Run, plan

# Inside the VM's root filesystem.
BUILD_DIR = ".icos-build"
RESULT_MARKER = "ICOS-BUILD-RESULT:"
RESULT_PATTERN = re.compile(re.escape(RESULT_MARKER) + r" (\d+)\n")

ROOT_DISK_SIZE = "32G"  # sparse; only the used blocks are written
OUTPUT_DISK_SIZE = "32G"  # sparse
# The init script writes its result to this disk rather than (only) to the
# serial console, where kernel messages (like sysrq's "Power Off") can land in
# the middle of it.
STATUS_DISK_SIZE = 1 << 20

INIT_SCRIPT = """#!/bin/sh
# PID 1 of the IC-OS container build VM: run the build steps, write the
# resulting filesystem to the output disk and power off.
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
mount -t proc proc /proc
mount -t sysfs sysfs /sys
# The kernel mounts devtmpfs on /dev itself if it is built with DEVTMPFS_MOUNT.
grep -q " /dev " /proc/mounts || mount -t devtmpfs devtmpfs /dev
# Like a container build, the steps get no input (instead of the console).
exec < /dev/null
mkdir -p /dev/pts /dev/shm
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /dev/shm
mount -t tmpfs tmpfs /run

# kvm-clock under KVM, something else (e.g. tsc) under TCG emulation.
echo "clocksource: $(cat /sys/devices/system/clocksource/clocksource0/current_clocksource)"
status=0
/bin/sh -e /{build_dir}/steps.sh || status=$?

cd /
# Stop what the steps left running, like a container engine at the end of each
# step, so that nothing keeps the mounts busy.
kill -KILL -1 2> /dev/null
sleep 1
# Keep the output and status disks' device nodes, then unmount everything so
# that only the image's own files (and mount point directories) remain.
cp -a /dev/vdb /{build_dir}/output || status=$?
cp -a /dev/vdc /{build_dir}/status || status=$?
# Release /dev/null, which would keep /dev busy (a closed stdin makes some tools abort).
exec < /
umount /run /dev/shm /dev/pts /dev /sys /proc || status=$?
{remove_lost_found}
if [ "$status" -eq 0 ]; then
    # Like a container image, without the build files. Only names, owners, modes
    # and contents are kept downstream.
    tar --create --file=/{build_dir}/output --format=gnu --numeric-owner --sort=name \\
        --one-file-system --exclude=./{build_dir} . || status=$?
fi
echo "{marker} $status" > /{build_dir}/status
sync
echo "{marker} $status"
mount -t proc proc /proc
echo o > /proc/sysrq-trigger
sleep 60
"""


def generate_steps(build_plan: Plan, env: List[str], build_dir: Path) -> str:
    """Write the RUN commands to build_dir/run/ and return the steps script that executes the plan."""
    run_dir = build_dir / "run"
    run_dir.mkdir()
    lines = ["# Generated by build_container_filesystem_vm.py", "set -e", ""]
    for number, step in enumerate(build_plan.steps, start=1):
        if isinstance(step, Run):
            description = "RUN " + step.command
        else:
            description = "COPY " + " ".join(step.sources + [step.destination])
        lines.append(f"echo {shlex.quote(f'>>> step {number}/{len(build_plan.steps)}: {description[:120]}')}")
        if isinstance(step, Run):
            command_file = run_dir / f"{number:04d}"
            command_file.write_text(step.command)
            step_env = list(env) + [f"{name}={value}" for name, value in step.args.items()]
            lines.append(
                "cd / && env -i "
                + " ".join(shlex.quote(e) for e in step_env)
                + f' /bin/sh -c "$(cat /{BUILD_DIR}/run/{number:04d})"'
            )
        else:
            lines.extend(copy_commands(step))
        lines.append("")
    return "\n".join(lines)


def copy_commands(step: Copy, context: str = f"/{BUILD_DIR}/ctx", root: str = "") -> List[str]:
    """
    Shell commands implementing a COPY step: files owned by root, modes from the context.

    context is where the build context is, and root is prepended to the destination (for tests).
    """
    destination = root + step.destination
    into_directory = destination.endswith("/") or len(step.sources) > 1
    dest = shlex.quote(destination)
    cp = "cp -dR --preserve=mode,ownership,links --remove-destination"
    commands = []
    for source in step.sources:
        src = shlex.quote(f"{context}/{source.rstrip('/')}")
        commands.append(f"if [ -d {src} ]; then")
        # A directory's contents are merged into the destination directory.
        commands.append(f"  mkdir -p {dest}")
        commands.append(f"  {cp} {src}/. {dest}/")
        if step.chmod:
            commands.append(
                f"  (cd {src} && find . -mindepth 1 -exec sh -c "
                + shlex.quote(f'chmod {step.chmod} "$0"/"$1"')
                + f" {dest} {{}} \\;)"
            )
        commands.append("else")
        # A file goes into the destination if that is (or must be) a directory,
        # and to the destination path otherwise.
        name = shlex.quote(os.path.basename(source))
        if into_directory:
            commands.append(f"  mkdir -p {dest}")
            commands.append(f"  target={dest}/{name}")
        else:
            commands.append(f"  mkdir -p {shlex.quote(os.path.dirname(destination) or '/')}")
            commands.append(f"  if [ -d {dest} ]; then target={dest}/{name}; else target={dest}; fi")
        commands.append(f'  {cp} {src} "$target"')
        if step.chmod:
            commands.append(f'  chmod {step.chmod} "$target"')
        commands.append("fi")
    return commands


def build_root_disk(
    base_rootfs: Path, context_dir: Path, staging: Path, init: str, steps: str, mke2fs: str, disk: Path
):
    """Create the VM's root disk: the base filesystem plus the build files, all owned by root."""
    script = f"""
set -euo pipefail
root={shlex.quote(str(staging))}
mkdir -m 0755 "$root"
tar --extract --numeric-owner --same-permissions --file={shlex.quote(str(base_rootfs))} --directory="$root"
mkdir "$root/{BUILD_DIR}"
cp -dR --preserve=mode,links {shlex.quote(str(context_dir))} "$root/{BUILD_DIR}/ctx"
cp -dR --preserve=mode {shlex.quote(str(context_dir.parent / "run"))} "$root/{BUILD_DIR}/run"
cat > "$root/{BUILD_DIR}/init" <<'ICOS_INIT_EOF'
{init}
ICOS_INIT_EOF
cat > "$root/{BUILD_DIR}/steps.sh" <<'ICOS_STEPS_EOF'
{steps}
ICOS_STEPS_EOF
chmod 0755 "$root/{BUILD_DIR}/init"
{shlex.quote(mke2fs)} -q -t ext4 -d "$root" -F {shlex.quote(str(disk))} {ROOT_DISK_SIZE}
"""
    # Under fakeroot, the extracted files keep the image's owners and the build
    # files appear owned by root, and mke2fs records exactly that.
    subprocess.run(["fakeroot", "--", "bash", "-c", script], check=True)


def read_result(status_disk: Path) -> Optional[int]:
    """The exit status the init script wrote to the status disk, if any."""
    with open(status_disk, "rb") as f:
        match = RESULT_PATTERN.match(f.read(256).decode(errors="replace"))
    return int(match.group(1)) if match else None


def run_vm(
    qemu: str,
    qemu_data: str,
    kernel: Path,
    root_disk: Path,
    output_disk: Path,
    status_disk: Path,
    memory: str,
    cpus: int,
    timeout: int,
):
    """Boot the build VM and return whether the build steps succeeded."""
    if not os.access("/dev/kvm", os.R_OK | os.W_OK):
        print(
            "WARNING: /dev/kvm is not accessible, falling back to QEMU's TCG emulation, which is much slower",
            file=sys.stderr,
            flush=True,
        )
    command = [
        qemu,
        "-L",
        qemu_data,
        "-machine",
        "q35",
        "-accel",
        "kvm",
        "-accel",
        "tcg",
        "-cpu",
        "max",
        "-m",
        memory,
        "-smp",
        str(cpus),
        "-nodefaults",
        "-display",
        "none",
        "-no-reboot",
        "-serial",
        "stdio",
        "-kernel",
        str(kernel),
        "-append",
        # loglevel=1: only emergencies, so that kernel messages don't interleave with the steps' output.
        f"root=/dev/vda rw rootfstype=ext4 init=/{BUILD_DIR}/init console=ttyS0 panic=-1 loglevel=1",
        "-drive",
        f"file={root_disk},format=raw,if=virtio,cache=unsafe",
        "-drive",
        f"file={output_disk},format=raw,if=virtio,cache=unsafe",
        "-drive",
        f"file={status_disk},format=raw,if=virtio,cache=unsafe",
    ]
    print(" ".join(shlex.quote(c) for c in command), file=sys.stderr, flush=True)
    with subprocess.Popen(command, stdout=subprocess.PIPE, stdin=subprocess.DEVNULL, text=True, errors="replace") as vm:
        # A step waiting for something that never comes would otherwise hang the build.
        timed_out = threading.Event()

        def kill():
            timed_out.set()
            vm.kill()

        watchdog = threading.Timer(timeout, kill)
        watchdog.start()
        try:
            for line in vm.stdout:
                sys.stderr.write(line)
        finally:
            watchdog.cancel()
    if vm.returncode != 0:
        if timed_out.is_set():
            raise RuntimeError(f"the build VM didn't finish within {timeout}s")
        raise RuntimeError(f"qemu exited with {vm.returncode}")
    result = read_result(status_disk)
    if result is None:
        raise RuntimeError("the build VM stopped without reporting a result")
    return result == 0


def normalize(name: str) -> str:
    """A tar member name without leading `./` (or `/`) and trailing `/`."""
    name = name.lstrip("/")
    while name.startswith("./"):
        name = name[2:]
    return name.rstrip("/")


def export_filesystem(output_disk: Path, destination_tar_filename: str):
    """Normalize the VM's tar like the podman export did: no /run contents, mtime 0, no user/group names."""
    with tarfile.open(output_disk, "r:") as source, tarfile.open(
        destination_tar_filename, "w", format=tarfile.GNU_FORMAT
    ) as destination:
        for member in source:
            name = member.name
            while name.startswith("./"):
                name = name[2:]
            if name in ("", "."):
                continue
            member = member.replace(name=name, deep=False)
            if member.islnk():
                linkname = member.linkname
                while linkname.startswith("./"):
                    linkname = linkname[2:]
                member = member.replace(linkname=linkname, deep=False)

            if member.name.startswith("run/"):
                continue

            if member.islnk() and member.linkname.startswith("run/"):
                raise RuntimeError(f"{member.name} is a hard link to `/run`, which is stripped out of the image")

            data = source.extractfile(member) if member.isfile() else None
            destination.addfile(member.replace(mtime=0, uname="", gname="", deep=False), data)


def has_entry(rootfs: Path, name: str) -> bool:
    with tarfile.open(rootfs) as tar:
        return any(normalize(member.name) == name for member in tar)


def get_args():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-d", "--dockerfile", required=True, help="The Dockerfile to build.")
    parser.add_argument("-o", "--output", required=True, help="Target (tar) file to write to")
    parser.add_argument("--build-arg", dest="build_args", action="append", default=[], help="NAME=value")
    parser.add_argument(
        "--file-build-arg",
        dest="file_build_args",
        action="append",
        default=[],
        help="NAME=path: the build arg is the first line of the file at path in the context.",
    )
    parser.add_argument("--context-file", dest="context_files", action="append", required=True)
    parser.add_argument(
        "--component-file",
        dest="component_files",
        action="append",
        default=[],
        help="Files to include in the context; expects sourcefile:targetfile",
    )
    parser.add_argument("--base-rootfs", required=True, type=Path, help="Flattened base image (oci_rootfs.py)")
    parser.add_argument("--base-env", required=True, type=Path, help="The base image's environment (oci_rootfs.py)")
    parser.add_argument(
        "--base-image-ref",
        required=True,
        type=Path,
        help="File with the reference of the base image that --base-rootfs was pulled from",
    )
    parser.add_argument("--kernel", required=True, type=Path, help="Kernel to boot the build VM with")
    parser.add_argument("--qemu", required=True, help="qemu-system-x86_64")
    parser.add_argument("--qemu-data", required=True, help="Directory with QEMU's firmware files")
    parser.add_argument("--mke2fs", required=True)
    parser.add_argument("--memory", default="4G", help="The VM's memory")
    parser.add_argument("--cpus", type=int, default=4, help="The VM's CPUs")
    parser.add_argument("--timeout", type=int, default=3600, help="Seconds before the VM is killed")
    return parser.parse_args()


def main():
    args = get_args()

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        context_dir = tmp / "build" / "ctx"
        context_dir.mkdir(parents=True)
        arrange_context(str(context_dir), args.context_files, args.component_files)

        build_args: Dict[str, str] = {}
        for arg in args.build_args + resolve_file_args(str(context_dir), args.file_build_args):
            name, _, value = arg.partition("=")
            build_args[name] = value

        build_plan = plan(Path(args.dockerfile).read_text(), build_args)
        expected_base = args.base_image_ref.read_text().strip()
        if build_plan.base_image != expected_base:
            raise RuntimeError(
                f"the Dockerfile builds on {build_plan.base_image!r}, but --base-rootfs is {expected_base!r}"
            )

        env = json.loads(args.base_env.read_text())
        if not any(e.startswith("PATH=") for e in env):
            env.append("PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")
        if not any(e.startswith("HOME=") for e in env):
            env.append("HOME=/root")
        steps = generate_steps(build_plan, env, tmp / "build")
        # mke2fs creates /lost+found, which isn't part of the image unless the base has one.
        init = INIT_SCRIPT.format(
            build_dir=BUILD_DIR,
            marker=RESULT_MARKER,
            remove_lost_found="" if has_entry(args.base_rootfs, "lost+found") else "rmdir /lost+found || status=$?",
        )

        root_disk = tmp / "root.img"
        output_disk = tmp / "output.img"
        status_disk = tmp / "status.img"
        build_root_disk(args.base_rootfs, context_dir, tmp / "root", init, steps, args.mke2fs, root_disk)
        shutil.rmtree(tmp / "root", ignore_errors=True)
        with open(output_disk, "wb") as f:
            f.truncate(int(OUTPUT_DISK_SIZE[:-1]) << 30)
        with open(status_disk, "wb") as f:
            f.truncate(STATUS_DISK_SIZE)

        if not run_vm(
            args.qemu,
            args.qemu_data,
            args.kernel,
            root_disk,
            output_disk,
            status_disk,
            args.memory,
            args.cpus,
            args.timeout,
        ):
            raise RuntimeError("a build step failed in the build VM (see the log above)")
        root_disk.unlink()
        export_filesystem(output_disk, args.output)


if __name__ == "__main__":
    main()
