load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = [
    "//rs/sns/cli:__pkg__",
    "//rs/sns/testing:__pkg__",
])

# See rs/nervous_system/feature_test.md
DEPENDENCIES = [
    # Keep sorted.
    "@crate_index//:aes-gcm",
    "@crate_index//:argon2",
    "@crate_index//:candid",
    "@crate_index//:dialoguer",
    "@crate_index//:directories-next",
    "@crate_index//:hex",
    "@crate_index//:ic-agent",
    "@crate_index//:ic-identity-hsm",
    "@crate_index//:keyring",
    "@crate_index//:lazy_static",
    "@crate_index//:reqwest",
    "@crate_index//:serde",
    "@crate_index//:serde_json",
    "@crate_index//:slog",
    "@crate_index//:thiserror",
    "@crate_index//:url",
] + select({
    "@platforms//os:osx": [
        "@crate_index//:security-framework",
    ],
    "//conditions:default": [],
})

# Only needed by tests.
DEV_DEPENDENCIES = [
    "@crate_index//:tempfile",
]

rust_library(
    name = "dfx-core-vendored",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["**/*tests.rs"],
    ),
    crate_name = "dfx_core_vendored",
    version = "0.4.0",
    deps = DEPENDENCIES,
)

rust_test(
    name = "dfx-core-vendored_test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = DEPENDENCIES + DEV_DEPENDENCIES,
)
