name: 'GitHub Authentication with netrc'
description: Set up authentication in netrc using github token. Picked up by tools like Bazel.

runs:
  using: "composite"
  steps:
    # write netrc to $HOME
    - shell: bash
      run: |
        # Set up .netrc so that tools can authenticate with GitHub to have higher rate limits for fetching dependencies.
        touch  ~/.netrc
        chmod 600 ~/.netrc
        echo "machine github.com login x-access-token password ${{ github.token }}" > ~/.netrc
        echo "machine api.github.com login x-access-token password ${{ github.token }}" >> ~/.netrc
        echo "Current GitHub API rate limits:"

        # Show how close we are to the limits
        curl -s --netrc https://api.github.com/rate_limit | \
          jq -r '.resources.core | "Rate limit remaining: \(.remaining)/\(.limit) (resets at \(.reset | strftime("%Y-%m-%d %H:%M:%S %Z")))"'
