= Components development

== Adding/removing IC-OS files

* Adding files
** To add files to an IC-OS build, add your files to the components/ directory and then enumerate each file in the components/{guestos,hostos,setupos,boundary-guestos}.bzl file for your corresponding IC-OS target(s).
** Note: if necessary, be sure to add a service file to start and control your service.
* Removing files
** To remove files from an IC-OS build, remove your files from the components/ directory and then remove the enumeration for every file you deleted in ALL the {guestos,hostos,setupos,boundary-guestos}.bzl files that enumerated your deleted files.

[NOTE]
Certain binaries are also injected into the image later in the build process. These extra binaries are added after the rootfs has already been constructed, and can be found in the corresponding defs.bzl file for each OS.

== Under the hood: IC-OS development

The Ubuntu-based IC-OS is built by:

* creating a root filesystem image using docker -- this is based on the
  official Ubuntu docker image and then augmented with the OS kernel plus our required services.

* converting this root filesystem into filesystem images for +/+ and +/boot+
  via +mke2fs+
