[package]
name = "ic-subnet-merging"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
futures = { workspace = true }
ic-base-types = { path = "../../types/base_types/" }
reqwest = { workspace = true }
tokio = { workspace = true }
