{
 "title": "DKG",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ic",
    "label": "IC",
    "query": {
     "query": "label_values(up{job=\"replica\"},ic)"
    }
   },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instances",
    "query": {
     "query": "label_values(up{ic=\"$ic\",job=\"replica\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sum of DKG on_state_change duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (ic, instance, job) (rate(consensus_dkg_on_state_change_duration_seconds_sum{ic=\"$ic\",instance=~\"$instances\",job=\"replica\",ic_subnet=~\"$ic_subnet\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "DKG Id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "consensus_dkg_instance_id{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instances\"}"
    }
   ]
  },
  {
   "title": "Registry Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "consensus_membership_registry_version{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instances\"}"
    }
   ]
  },
  {
   "title": "Committee Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consensus_dkg_current_committee_size{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instances\"}"
    }
   ]
  },
  {
   "title": "DKG Validated Pool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "artifact_pool_artifacts{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instances\",pool=\"dkg\",pool_type=\"validated\"}"
    }
   ]
  },
  {
   "title": "DKG Unvalidated Pool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(artifact_pool_artifacts{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instances\",pool=\"dkg\",pool_type=\"unvalidated\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "DKG Intervals Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consensus_dkg_intervals_failed{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instances\"}"
    }
   ]
  }
 ]
}