{
 "title": "Hosts",
 "tags": [
  "Boundary Node",
  "Clickhouse"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "Production : prod, Development : dev"
   },
   { "name": "table_hostnames", "query": "http_access_by_hostname" },
   {
    "name": "hostname",
    "label": "Boundary Node",
    "query": "SELECT DISTINCT hostname FROM $table_hostnames WHERE date >= ${__from:date:seconds} AND date <= ${__to:date:seconds} AND env = '$env'"
   },
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT DISTINCT geo_country_code FROM $table_hostnames WHERE date >= ${__from:date:seconds} AND date <= ${__to:date:seconds}"
   },
   {
    "name": "status",
    "label": "HTTP Status Code",
    "query": "SELECT DISTINCT status FROM $table_hostnames WHERE date >= ${__from:date:seconds} AND date <= ${__to:date:seconds}"
   },
   { "name": "remote_addr_family", "label": "IP Address Family", "query": "IPv4 : 4, IPv6 : 6" },
   {
    "name": "datasource",
    "query": "vertamedia-clickhouse-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Unique Clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  uniqCombinedMerge(unique_ips)\nFROM\n  $table_hostnames\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                =  '$env',                $env)\n  $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n  $conditionalTest(AND status             IN ($status),             $status)\n  $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n  $conditionalTest(AND geo_country_code   IN ($country),            $country)\n",
     "rawQuery": "SELECT\n  uniqCombinedMerge(unique_ips)\nFROM\n  http_access_by_hostname\nWHERE\n  date >= toDateTime(1709722483) AND date <= toDateTime(1709808883)\n   AND env                =  'prod' \n   \n   \n   AND remote_addr_family IN (4,6) \n   ",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  sum(request_size_sum) / (${__to:date:seconds} - ${__from:date:seconds}) * 8 AS In,\n  sum(response_size_sum) / (${__to:date:seconds} - ${__from:date:seconds}) * 8 AS Out\nFROM\n  $table_hostnames\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                =  '$env',                $env)\n  $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n  $conditionalTest(AND status             IN ($status),             $status)\n  $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n  $conditionalTest(AND geo_country_code   IN ($country),            $country)\n",
     "rawQuery": "SELECT\n  sum(request_size_sum) / (1709808884 - 1709722484) * 8 AS In,\n  sum(response_size_sum) / (1709808884 - 1709722484) * 8 AS Out\nFROM\n  http_access_by_hostname\nWHERE\n  date >= toDateTime(1709722493) AND date <= toDateTime(1709808893)\n   AND env                =  'prod' \n   \n   \n   AND remote_addr_family IN (4,6) \n   ",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Data Transferred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  sum(request_size_sum) AS In,\n  sum(response_size_sum) AS Out\nFROM\n  $table_hostnames\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                =  '$env',                $env)\n  $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n  $conditionalTest(AND status             IN ($status),             $status)\n  $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n  $conditionalTest(AND geo_country_code   IN ($country),            $country)\n",
     "rawQuery": "SELECT\n  sum(request_size_sum) AS In,\n  sum(response_size_sum) AS Out\nFROM\n  http_access_by_hostname\nWHERE\n  date >= toDateTime(1709722510) AND date <= toDateTime(1709808910)\n   AND env                =  'prod' \n   \n   \n   AND remote_addr_family IN (4,6) \n   ",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  t,\n  groupArray((hostname, rate))\nFROM (\n  SELECT\n      $timeSeries AS t,\n      hostname,\n      countMerge(request_count) / ($__interval_ms / 1000) AS rate\n  FROM $table_hostnames\n  WHERE\n    $timeFilter\n    $conditionalTest(AND env                =  '$env',                $env)\n    $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n    $conditionalTest(AND status             IN ($status),             $status)\n    $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n    $conditionalTest(AND geo_country_code   IN ($country),            $country)\n  GROUP BY t, hostname\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n  t,\n  groupArray((hostname, rate))\nFROM (\n  SELECT\n      (intDiv(toUInt32(date), 300) * 300) * 1000 AS t,\n      hostname,\n      countMerge(request_count) / (300000 / 1000) AS rate\n  FROM http_access_by_hostname\n  WHERE\n    date >= toDateTime(1709722548) AND date <= toDateTime(1709808948)\n     AND env                =  'prod' \n     \n     \n     AND remote_addr_family IN (4,6) \n     \n  GROUP BY t, hostname\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "http_access_by_canister"
    }
   ]
  },
  {
   "title": "Request Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  t,\n  groupArray((hostname, p95))\nFROM (\n  SELECT\n      $timeSeries as t,\n      hostname,\n      quantileMerge(0.95)(request_time_ms) AS p95\n  FROM $table_hostnames\n  WHERE\n    $timeFilter\n    $conditionalTest(AND env                =  '$env',                $env)\n    $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n    $conditionalTest(AND status             IN ($status),             $status)\n    $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n    $conditionalTest(AND geo_country_code   IN ($country),            $country)\n  GROUP BY t, hostname\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n  t,\n  groupArray((hostname, p95))\nFROM (\n  SELECT\n      (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n      hostname,\n      quantileMerge(0.95)(request_time_ms) AS p95\n  FROM http_access_by_hostname\n  WHERE\n    date >= toDateTime(1709722558) AND date <= toDateTime(1709808958)\n     AND env                =  'prod' \n     \n     \n     AND remote_addr_family IN (4,6) \n     \n  GROUP BY t, hostname\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Request Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  t,\n  groupArray((hostname, bw))\nFROM (\n  SELECT\n      $timeSeries as t,\n      hostname,\n      sum(request_size_sum) / ($__interval_ms / 1000) AS bw\n  FROM $table_hostnames\n  WHERE\n    $timeFilter\n    $conditionalTest(AND env                =  '$env',                $env)\n    $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n    $conditionalTest(AND status             IN ($status),             $status)\n    $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n    $conditionalTest(AND geo_country_code   IN ($country),            $country)\n  GROUP BY t, hostname\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n  t,\n  groupArray((hostname, bw))\nFROM (\n  SELECT\n      (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n      hostname,\n      sum(request_size_sum) / (300000 / 1000) AS bw\n  FROM http_access_by_hostname\n  WHERE\n    date >= toDateTime(1709722569) AND date <= toDateTime(1709808969)\n     AND env                =  'prod' \n     \n     \n     AND remote_addr_family IN (4,6) \n     \n  GROUP BY t, hostname\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "http_access_by_canister"
    }
   ]
  },
  {
   "title": "Response Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "\nSELECT\n  t,\n  groupArray((hostname, bw))\nFROM (\n  SELECT\n      $timeSeries as t,\n      hostname,\n      sum(response_size_sum) / ($__interval_ms / 1000) AS bw\n  FROM $table_hostnames\n  WHERE\n    $timeFilter\n    $conditionalTest(AND env                =  '$env',                $env)\n    $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n    $conditionalTest(AND status             IN ($status),             $status)\n    $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n    $conditionalTest(AND geo_country_code   IN ($country),            $country)\n  GROUP BY t, hostname\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n  t,\n  groupArray((hostname, bw))\nFROM (\n  SELECT\n      (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n      hostname,\n      sum(response_size_sum) / (300000 / 1000) AS bw\n  FROM http_access_by_hostname\n  WHERE\n    date >= toDateTime(1709722581) AND date <= toDateTime(1709808981)\n     AND env                =  'prod' \n     \n     \n     AND remote_addr_family IN (4,6) \n     \n  GROUP BY t, hostname\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "http_access_by_canister"
    }
   ]
  },
  { "title": "Detailed View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Request Rate by HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  t,\n  groupArray((status, rate))\nFROM (\n  SELECT\n      $timeSeries as t,\n      status,\n      countMerge(request_count) / ($__interval_ms / 1000) AS rate\n  FROM $table_hostnames\n  WHERE\n    $timeFilter\n    $conditionalTest(AND env                =  '$env',                $env)\n    $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n    $conditionalTest(AND status             IN ($status),             $status)\n    $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n    $conditionalTest(AND geo_country_code   IN ($country),            $country)\n  GROUP BY t, status\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n  t,\n  groupArray((status, rate))\nFROM (\n  SELECT\n      (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n      status,\n      countMerge(request_count) / (300000 / 1000) AS rate\n  FROM http_access_by_hostname\n  WHERE\n    date >= toDateTime(1709722600) AND date <= toDateTime(1709809000)\n     AND env                =  'prod' \n     \n     \n     AND remote_addr_family IN (4,6) \n     \n  GROUP BY t, status\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Latency (p95) by HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  t,\n  groupArray((status, p95))\nFROM (\n  SELECT\n      $timeSeries as t,\n      status,\n      quantileMerge(0.95)(request_time_ms) as p95\n  FROM $table_hostnames\n  WHERE\n    $timeFilter\n    $conditionalTest(AND env                =  '$env',                $env)\n    $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n    $conditionalTest(AND status             IN ($status),             $status)\n    $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n    $conditionalTest(AND geo_country_code   IN ($country),            $country)\n  GROUP BY t, status\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n  t,\n  groupArray((status, p95))\nFROM (\n  SELECT\n      (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n      status,\n      quantileMerge(0.95)(request_time_ms) as p95\n  FROM http_access_by_hostname\n  WHERE\n    date >= toDateTime(1709722634) AND date <= toDateTime(1709809034)\n     AND env                =  'prod' \n     \n     \n     AND remote_addr_family IN (4,6) \n     \n  GROUP BY t, status\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Request Rate by IP Family",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  t,\n  groupArray((remote_addr_family, rate))\nFROM (\n  SELECT\n      $timeSeries as t,\n      remote_addr_family,\n      countMerge(request_count) / ($__interval_ms / 1000) AS rate\n  FROM $table_hostnames\n  WHERE\n    $timeFilter\n    $conditionalTest(AND env                =  '$env',                $env)\n    $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n    $conditionalTest(AND status             IN ($status),             $status)\n    $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n    $conditionalTest(AND geo_country_code   IN ($country),            $country)\n  GROUP BY t, remote_addr_family\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n  t,\n  groupArray((remote_addr_family, rate))\nFROM (\n  SELECT\n      (intDiv(toUInt32(date), 300) * 300) * 1000 as t,\n      remote_addr_family,\n      countMerge(request_count) / (300000 / 1000) AS rate\n  FROM http_access_by_hostname\n  WHERE\n    date >= toDateTime(1709722644) AND date <= toDateTime(1709809044)\n     AND env                =  'prod' \n     \n     \n     AND remote_addr_family IN (4,6) \n     \n  GROUP BY t, remote_addr_family\n  ORDER BY t\n)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "http_access"
    }
   ]
  },
  {
   "title": "Request Origins",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    geo_country_code AS Country,\n    countMerge(request_count) AS TotalRequests\nFROM $table_hostnames\nWHERE\n  $timeFilter\n  $conditionalTest(AND env                =  '$env',                $env)\n  $conditionalTest(AND hostname           IN ($hostname),           $hostname)\n  $conditionalTest(AND status             IN ($status),             $status)\n  $conditionalTest(AND remote_addr_family IN ($remote_addr_family), $remote_addr_family)\n  $conditionalTest(AND geo_country_code   IN ($country),            $country)\nGROUP BY Country",
     "rawQuery": "SELECT\n    geo_country_code AS Country,\n    countMerge(request_count) AS TotalRequests\nFROM http_access_by_hostname\nWHERE\n  date >= toDateTime(1709722654) AND date <= toDateTime(1709809054)\n   AND env                =  'prod' \n   \n   \n   AND remote_addr_family IN (4,6) \n   \nGROUP BY Country",
     "round": "0s",
     "table": "http_access"
    }
   ]
  }
 ]
}