{
 "title": "Overview",
 "tags": [
  "Boundary Node",
  "Clickhouse"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "vertamedia-clickhouse-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    countMerge(request_count) AS Total,\n    countMerge(request_count) / (${__to:date:seconds} - ${__from:date:seconds}) AS \"Per Second\"\nFROM $table\nWHERE $timeFilter AND env = 'prod'",
     "rawQuery": "SELECT\n    countMerge(request_count) AS Total,\n    countMerge(request_count) / (1684082079 - 1683995679) AS \"Per Second\"\nFROM default.http_access_by_hostname\nWHERE date >= toDateTime(1683995713) AND date <= toDateTime(1684082113) AND env = 'prod'",
     "round": "0s",
     "table": "http_access_by_hostname"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  uniqCombinedMerge(unique_hosts) AS \"Boundary\",\n  uniqCombinedMerge(unique_replicas) AS \"Replica\"\nFROM $table\nWHERE $timeFilter AND env = 'prod'",
     "rawQuery": "SELECT\n  uniqCombinedMerge(unique_hosts) AS \"Boundary\",\n  uniqCombinedMerge(unique_replicas) AS \"Replica\"\nFROM default.http_access_totals\nWHERE date >= toDateTime(1684175504) AND date <= toDateTime(1684261904) AND env = 'prod'",
     "round": "0s",
     "table": "http_access_totals"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  uniqCombinedMerge(unique_canisters) AS Canisters,\n  uniqCombinedMerge(unique_subnets) AS Subnets\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'\n",
     "rawQuery": "SELECT\n  uniqCombinedMerge(unique_canisters) AS Canisters,\n  uniqCombinedMerge(unique_subnets) AS Subnets\nFROM default.http_access_totals\nWHERE date >= toDateTime(1684175495) AND date <= toDateTime(1684261895)\nAND env = 'prod'",
     "round": "0s",
     "table": "http_access_totals"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  uniqCombinedMerge(unique_countries)\nFROM $table\nWHERE $timeFilter AND env = 'prod'",
     "rawQuery": "SELECT\n  uniqCombinedMerge(unique_countries)\nFROM default.http_access_totals\nWHERE date >= toDateTime(1709724797) AND date <= toDateTime(1709811197) AND env = 'prod'",
     "round": "0s",
     "table": "http_access_totals"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  sum(request_size_sum) / (${__to:date:seconds} - ${__from:date:seconds}) * 8 AS In,\n  sum(response_size_sum) / (${__to:date:seconds} - ${__from:date:seconds}) * 8 AS Out\nFROM $table\nWHERE $timeFilter AND env = 'prod'",
     "rawQuery": "SELECT\n  sum(request_size_sum) / (1684081261 - 1683994861) * 8 AS In,\n  sum(response_size_sum) / (1684081261 - 1683994861) * 8 AS Out\nFROM default.http_access_by_hostname\nWHERE date >= toDateTime(1683994932) AND date <= toDateTime(1684081332) AND env = 'prod'",
     "round": "0s",
     "table": "http_access_by_hostname"
    }
   ]
  },
  {
   "title": "Peak Bandwidth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n max(In) AS In,\n max(Out) AS Out\nFROM (\n SELECT\n   toStartOfMinute(date) AS t,\n   sum(request_size_sum) / 60 * 8 AS In,\n   sum(response_size_sum) / 60 * 8 AS Out\n FROM $table\n WHERE $timeFilter AND env = 'prod'\n GROUP BY t\n)",
     "rawQuery": "SELECT\n max(In) AS In,\n max(Out) AS Out\nFROM (\n SELECT\n   toStartOfMinute(date) AS t,\n   sum(request_size_sum) / 60 * 8 AS In,\n   sum(response_size_sum) / 60 * 8 AS Out\n FROM default.http_access_by_hostname\n WHERE date >= toDateTime(1683995670) AND date <= toDateTime(1684082070) AND env = 'prod'\n GROUP BY t\n)",
     "round": "0s",
     "table": "http_access_by_hostname"
    }
   ]
  },
  {
   "title": "Data Transferred",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  sum(request_size_sum) AS In,\n  sum(response_size_sum) AS Out\nFROM $table\nWHERE $timeFilter AND env = 'prod'",
     "round": "0s",
     "table": "http_access_totals"
    }
   ]
  },
  {
   "title": "Unique Clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    uniqCombinedMerge(unique_ips) AS \"By IP\",\n    uniqCombinedMerge(unique_senders) AS \"By SenderID\"\nFROM $table\nWHERE $timeFilter AND env = 'prod'",
     "rawQuery": "SELECT\n    uniqCombinedMerge(unique_ips) AS \"By IP\",\n    uniqCombinedMerge(unique_senders) AS \"By SenderID\"\nFROM default.http_access_totals\nWHERE date >= toDateTime(1684175527) AND date <= toDateTime(1684261927) AND env = 'prod'",
     "round": "0s",
     "table": "http_access_totals"
    }
   ]
  },
  {
   "title": "Request latency (95%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quantileMerge(0.95)(request_time_ms)\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'",
     "rawQuery": "SELECT\n    quantileMerge(0.95)(request_time_ms)\nFROM default.http_access_totals\nWHERE date >= toDateTime(1684175831) AND date <= toDateTime(1684262231)\nAND env = 'prod'",
     "round": "0s",
     "table": "http_access_totals"
    }
   ]
  },
  {
   "title": "Request size (95%)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quantileMerge(0.95)(request_size)\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'\n",
     "rawQuery": "SELECT\n    quantileMerge(0.95)(request_size)\nFROM default.http_access_totals\nWHERE date >= toDateTime(1684175859) AND date <= toDateTime(1684262259)\nAND env = 'prod'",
     "round": "0s",
     "table": "http_access_totals"
    }
   ]
  },
  {
   "title": "Response size (95%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quantileMerge(0.95)(response_size)\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'\n",
     "rawQuery": "SELECT\n    quantileMerge(0.95)(response_size)\nFROM default.http_access_totals\nWHERE date >= toDateTime(1684175885) AND date <= toDateTime(1684262285)\nAND env = 'prod'",
     "round": "0s",
     "table": "http_access_totals"
    }
   ]
  },
  {
   "title": "Request types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "WITH (\n  SELECT\n   countMerge(request_count)\n  FROM\n   $table\n  WHERE\n   $timeFilter\n   AND env = 'prod'\n   AND ic_request_type != ''\n) AS TotalRequests\nSELECT\n    ic_request_type,\n    countMerge(request_count) / TotalRequests * 100 AS cnt\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'\nAND ic_request_type != ''\nGROUP BY ic_request_type",
     "rawQuery": "WITH (\n  SELECT\n   countMerge(request_count)\n  FROM\n   default.http_access_by_replica\n  WHERE\n   date >= toDateTime(1684081159) AND date <= toDateTime(1684167559)\n   AND env = 'prod'\n   AND ic_request_type != ''\n) AS TotalRequests\nSELECT\n    ic_request_type,\n    countMerge(request_count) / TotalRequests * 100 AS cnt\nFROM default.http_access_by_replica\nWHERE date >= toDateTime(1684081159) AND date <= toDateTime(1684167559)\nAND env = 'prod'\nAND ic_request_type != ''\nGROUP BY ic_request_type",
     "round": "0s",
     "table": "http_access_by_replica"
    }
   ]
  },
  {
   "title": "Client IP Family",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    countMerge(requests_ipv6) / countMerge(request_count) * 100 AS IPv6,\n    100 - IPv6 AS IPv4\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'",
     "rawQuery": "SELECT\n    countMerge(requests_ipv6) / countMerge(request_count) * 100 AS IPv6,\n    100 - IPv6 AS IPv4\nFROM default.http_access_totals\nWHERE date >= toDateTime(1684174119) AND date <= toDateTime(1684260519)\nAND env = 'prod'",
     "round": "0s",
     "table": "http_access_totals"
    }
   ]
  },
  {
   "title": "Request Status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "WITH (\n  SELECT\n    countMerge(request_count)\n  FROM $table\n  WHERE $timeFilter\n  AND env = 'prod'\n) AS Total\nSELECT\n  '' AS foo, -- bar chart requires\n  countMerge(requests_1xx) / Total * 100 AS 1xx,\n  countMerge(requests_2xx) / Total * 100 AS 2xx,\n  countMerge(requests_3xx) / Total * 100 AS 3xx,\n  countMerge(requests_4xx) / Total * 100 AS 4xx,\n  countMerge(requests_5xx) / Total * 100 AS 5xx\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'",
     "rawQuery": "WITH (\n  SELECT\n    countMerge(request_count)\n  FROM default.http_access_totals\n  WHERE date >= toDateTime(1684229822) AND date <= toDateTime(1684316222)\n  AND env = 'prod'\n) AS Total\nSELECT\n  '' AS foo, \n  countMerge(requests_1xx) / Total * 100 AS 1xx,\n  countMerge(requests_2xx) / Total * 100 AS 2xx,\n  countMerge(requests_3xx) / Total * 100 AS 3xx,\n  countMerge(requests_4xx) / Total * 100 AS 4xx,\n  countMerge(requests_5xx) / Total * 100 AS 5xx\nFROM default.http_access_totals\nWHERE date >= toDateTime(1684229822) AND date <= toDateTime(1684316222)\nAND env = 'prod'",
     "round": "0s",
     "table": "http_access_totals"
    }
   ]
  },
  { "title": "Important Canisters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    canister_id AS CanisterID,\n    description AS Description\nFROM $table\nORDER BY description",
     "rawQuery": "SELECT\n    canister_id AS CanisterID,\n    description AS Description\nFROM default.important_canisters\nORDER BY description",
     "round": "0s",
     "table": "important_canisters"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Top 10 subnets by Request count",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    ic_subnet_id AS SubnetID,\n    countMerge(request_count) AS RequestCount\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'\nGROUP BY SubnetID\nORDER BY RequestCount DESC\nLIMIT 10",
     "rawQuery": "SELECT\n    ic_subnet_id AS SubnetID,\n    countMerge(request_count) AS RequestCount\nFROM default.http_access_by_subnet\nWHERE date >= toDateTime(1683842400) AND date <= toDateTime(1683928799)\nAND env = 'prod'\nGROUP BY SubnetID\nORDER BY RequestCount DESC\nLIMIT 10",
     "round": "0s",
     "table": "http_access_by_subnet"
    }
   ]
  },
  {
   "title": "Top 10 canisters by Request count",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    ic_canister_id AS CanisterID,\n    countMerge(request_count) AS RequestCount\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'\nAND ic_canister_id != ''\nGROUP BY CanisterID\nORDER BY RequestCount DESC\nLIMIT 10",
     "rawQuery": "SELECT\n    ic_canister_id AS CanisterID,\n    countMerge(request_count) AS RequestCount\nFROM default.http_access_by_canister\nWHERE date >= toDateTime(1683842400) AND date <= toDateTime(1683928799)\nAND env = 'prod'\nAND ic_canister_id != ''\nGROUP BY CanisterID\nORDER BY RequestCount DESC\nLIMIT 10",
     "round": "0s",
     "table": "http_access_by_canister"
    }
   ]
  },
  {
   "title": "Top 10 boundary nodes by Request count",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    hostname,\n    countMerge(request_count) AS RequestCount\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'\nGROUP BY hostname\nORDER BY RequestCount DESC\nLIMIT 10",
     "rawQuery": "SELECT\n    hostname,\n    countMerge(request_count) AS RequestCount\nFROM default.http_access_by_hostname\nWHERE date >= toDateTime(1683842400) AND date <= toDateTime(1683928799)\nAND env = 'prod'\nGROUP BY hostname\nORDER BY RequestCount DESC\nLIMIT 10",
     "round": "0s",
     "table": "http_access_by_hostname"
    }
   ]
  },
  {
   "title": "Request Origins",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    geo_country_code AS Country,\n    countMerge(request_count) AS TotalRequests\nFROM $table\nWHERE $timeFilter\nAND env = 'prod'\nAND geo_country_code != 'N/A'\nGROUP BY Country\n",
     "rawQuery": "SELECT\n    geo_country_code AS Country,\n    countMerge(request_count) AS TotalRequests\nFROM default.http_access_by_hostname\nWHERE date >= toDateTime(1709725186) AND date <= toDateTime(1709811586)\nAND env = 'prod'\nAND geo_country_code != 'N/A'\nGROUP BY Country",
     "round": "0s",
     "table": "http_access_by_hostname"
    }
   ]
  }
 ]
}