load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "test_utils",
    testonly = True,
    srcs = glob(
        ["src/**/*.rs"],
    ),
    crate_name = "ic_cketh_test_utils",
    proc_macro_deps = [
        # Keep sorted.
        "@crate_index//:strum_macros",
    ],
    version = "0.1.0",
    deps = [
        # Keep sorted.
        "//packages/ic-ethereum-types",
        "//packages/ic-http-types",
        "//packages/ic-metrics-assert:ic-metrics-assert_pocket_ic",
        "//packages/icrc-ledger-types:icrc_ledger_types_storable",
        "//packages/pocket-ic",
        "//rs/ethereum/cketh/minter",
        "//rs/ethereum/ledger-suite-orchestrator:ledger_suite_orchestrator",
        "//rs/ethereum/ledger-suite-orchestrator/test_utils",
        "//rs/ledger_suite/icrc1/ledger",
        "//rs/test_utilities/load_wasm",
        "//rs/types/base_types",
        "@crate_index//:alloy-consensus",
        "@crate_index//:alloy-primitives",
        "@crate_index//:alloy-rpc-types-eth",
        "@crate_index//:assert_matches",
        "@crate_index//:candid",
        "@crate_index//:ethers-core",
        "@crate_index//:evm_rpc_types",
        "@crate_index//:hex",
        "@crate_index//:ic-management-canister-types",
        "@crate_index//:num-traits",
        "@crate_index//:reqwest",
        "@crate_index//:serde",
        "@crate_index//:serde_bytes",
        "@crate_index//:serde_json",
        "@crate_index//:strum",
    ],
)

rust_test(
    name = "lib_tests",
    crate = ":test_utils",
    deps = [],
)
