[package]
name = "ic-cketh-test-utils"
description = "Integration test utilities for the ic-cketh minter"
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-sol-types = { workspace = true }
assert_matches = { workspace = true }
candid = { workspace = true }
evm_rpc_types = { workspace = true }
hex = { workspace = true }
ic-base-types = { path = "../../../types/base_types" }
ic-cketh-minter = { path = "../minter" }
ic-ethereum-types = { path = "../../../../packages/ic-ethereum-types" }
ic-http-types = { path = "../../../../packages/ic-http-types" }
ic-icrc1-ledger = { path = "../../../ledger_suite/icrc1/ledger" }
ic-ledger-suite-orchestrator = { path = "../../ledger-suite-orchestrator" }
ic-ledger-suite-orchestrator-test-utils = { path = "../../ledger-suite-orchestrator/test_utils" }
ic-management-canister-types = { workspace = true }
ic-metrics-assert = { path = "../../../../packages/ic-metrics-assert", features = ["pocket_ic"] }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
num-traits = { workspace = true }
pocket-ic = { path = "../../../../packages/pocket-ic" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

[features]
default = []
