from enum import IntEnum


class Team(IntEnum):
    NODE_TEAM = 1
    BOUNDARY_NODE_TEAM = 2
    TRUST_TEAM = 3
    GIX_TEAM = 4
    SDK_TEAM = 5
    FINANCIAL_INTEGRATIONS_TEAM = 6
    EXECUTION_TEAM = 7
    NNS_TEAM = 8
    CRYPTO_TEAM = 9
    IDENTITY_TEAM = 10
    INTEGRATIONS_TEAM = 11
    PRODUCT_ENABLEMENT_TEAM = 12
    UTOPIA_RND_TEAM = 13
