[package]
name = "ic-crypto-test-utils-crypto-returning-ok"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-crypto-interfaces-sig-verification = { path = "../../interfaces/sig_verification" }
ic-crypto-test-utils-canister-threshold-sigs = { path = "../../test_utils/canister_threshold_sigs" }
ic-crypto-test-utils-ni-dkg = { path = "../../test_utils/ni-dkg" }
ic-interfaces = { path = "../../../interfaces" }
ic-test-utilities-types = { path = "../../../test_utilities/types" }
ic-types = { path = "../../../types/types" }
ic-types-test-utils = { path = "../../../types/types_test_utils" }
