(module
  (import "foo" "bar" (func))
  (import "foo" "bar" (func (param f32)))
  (memory (data "hi"))
  (type (func (param i32) (result i32)))
  (start 0)
  (table 0 1 anyfunc)
  (func)
  (func (type 1) (drop (i32.const 42)))
  (export "e" (func 1)))
