generate:
  dfx generate testicp-backend

# Start development server with ICP token type
start-icp:
  cd src/frontend && VITE_TOKEN_SYMBOL=TESTICP npm run start

# Start development server with ICRC1 token type  
start-icrc1:
  cd src/frontend && VITE_TOKEN_SYMBOL=TICRC1 npm run start

# Build with ICP token type
build-icp:
  cd src/frontend && npm run build:icp

# Build with ICRC1 token type
build-icrc1:
  cd src/frontend && VITE_TOKEN_SYMBOL=TICRC1 npm run build

deploy-icp:
  dfx deploy testicp-ledger
  dfx deploy testicp-backend
  dfx deploy testicp-frontend

deploy-icrc1:
  dfx deploy ticrc1-ledger
  dfx deploy ticrc1-backend
  dfx deploy ticrc1-frontend

deploy-icrc1-mainnet:
  # NOTE: You need to manually set is_mint to false in the backend canister before deploying
  dfx deploy ticrc1-backend --network ic --mode=reinstall
  dfx deploy ticrc1-frontend --network ic

deploy-icp-mainnet:
  # NOTE: You need to manually set is_mint to false in the backend canister before deploying
  dfx deploy testicp-backend --network ic --mode=reinstall
  dfx deploy testicp-frontend --network ic

