# HTTP endpoint for fetching metrics
canister_query:http_request
# Transform function for HTTP outcalls
canister_query:transform
# Canister lifecycle
canister_init
canister_post_upgrade
# Exported by the `main()` function in `main.rs`; cannot be called
main
