{
 "title": "Quic transport",
 "description": "Consensus Finalization Height",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "label": "IC", "query": { "query": "label_values(ic)" } },
   {
    "name": "ic_subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{ic=\"$ic\",job=\"replica\",ic_subnet=~\"$ic_subnet\"}, instance)"
    }
   },
   { "name": "period", "label": "Aggregation period", "query": "20s,30s,1m,2m,5m,10m,30m,1h" },
   { "name": "handler", "query": { "query": "label_values(handler)" } }
  ]
 },
 "panels": [
  { "title": "connection manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "quic transport connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(quic_transport_active_connections{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"})",
     "legendFormat": "Connected"
    },
    {
     "expr": "label_replace(\n  sum by (ic_subnet) (quic_transport_toplogy_size{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} -1 - quic_transport_active_connections{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"(\\\\w+)-.*\"\n)",
     "legendFormat": "Disconnected in {{ic_subnet}}"
    },
    {
     "expr": "  sum(increase(quic_transport_closed_request_handler_total{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period]))\n/\n  increase(vector(time())[$period:10s]) * 10",
     "legendFormat": "Reconnections"
    }
   ]
  },
  {
   "title": "Transport connections (legacy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(transport_flow_state{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} == 3)",
     "legendFormat": "Connected"
    },
    {
     "expr": "label_replace(\n  count by (ic_subnet) (transport_flow_state{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"} != 3),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"(\\\\w+)-.*\"\n)",
     "legendFormat": "Disconnected in {{ic_subnet}}"
    },
    {
     "expr": "  sum(increase(transport_retry_connection{job=\"replica\",ic=\"$ic\",ic_subnet=~\"$ic_subnet\",instance=~\"$instance\"}[$period]))\n/\n  increase(vector(time())[$period:10s]) * 10",
     "legendFormat": "Reconnections"
    }
   ]
  },
  {
   "title": "active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_active_connections{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "topology size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_toplogy_size{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "peer map size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_peer_map_size{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "peers removed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_peers_removed_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "topology changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_topology_changes_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "outbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_outbound_connection_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "inbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_inbound_connection_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "outbound connection rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(quic_transport_outbound_connection_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$period]),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "inbound connection rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(quic_transport_inbound_connection_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$period]),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "connection setup failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_connection_results_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\",status=\"failed\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "connection setup success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_connection_results_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\",status=\"success\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "connect queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_delay_queue_size{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "currently connecting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_connecting_connections{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  {
   "title": "closed request handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_closed_request_handler_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}}"
    }
   ]
  },
  { "title": "connection handle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "push request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(quic_transport_connection_handle_duration_seconds_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", handler=~\"$handler\"}[$period]),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{handler}} "
    }
   ]
  },
  {
   "title": "median request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  histogram_quantile(0.5, sum by (instance, handler, le) (rate(quic_transport_connection_handle_duration_seconds_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", handler=~\"$handler\"}[$period]))),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{handler}} "
    }
   ]
  },
  {
   "title": "data flow out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(quic_transport_connection_handle_bytes_sent_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", handler=~\"$handler\"}[$period]),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{handler}} "
    }
   ]
  },
  {
   "title": "data flow in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(quic_transport_connection_handle_bytes_received_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", handler=~\"$handler\"}[$period]),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{handler}} "
    }
   ]
  },
  {
   "title": "push request errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(quic_transport_connection_handle_errors_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", request=\"push\"}[$period]),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{error}}"
    }
   ]
  },
  {
   "title": "rpc request errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_connection_handle_errors_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", request=\"rpc\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{error}}"
    }
   ]
  },
  { "title": "connection metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "rtt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_quinn_path_rtt_seconds{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_node\", \"$1\", \"ic_node\", \"(.*?)-.*-(.*?)\"),\n  \"peer\", \"$1\", \"peer\", \"(.*?)-.*-(.*?)\"\n)\n",
     "legendFormat": "{{ic_node}} <-> {{peer}}"
    }
   ]
  },
  {
   "title": "Bandwidth Estimate",
   "type": "timeseries",
   "description": "Estimate of available bandwidth between nodes. Calculated with `CWND`/`RTT`.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "label_replace(\n  (\n    label_replace(\n    (\n      quic_transport_quinn_path_congestion_window{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}\n      /\n      quic_transport_quinn_path_rtt_seconds{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}      \n    ),\n    \"ic_node\", \"$1\", \"ic_node\", \"(.*?)-.*-(.*?)\")\n  ),\n  \"peer\", \"$1\", \"peer\", \"(.*?)-.*-(.*?)\"\n)\n",
     "legendFormat": "{{ic_node}} <-> {{peer}}"
    }
   ]
  },
  {
   "title": "packet loss path",
   "type": "timeseries",
   "description": "Estimate of available bandwidth between nodes. Calculated with `CWND`/`RTT`.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  (\n    label_replace(\n    (\n      rate(quic_transport_quinn_path_lost_packets{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$period])/\n      rate(quic_transport_quinn_path_sent_packets{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$period])\n    ),\n    \"ic_node\", \"$1\", \"ic_node\", \"(.*?)-.*-(.*?)\")\n  ),\n  \"peer\", \"$1\", \"peer\", \"(.*?)-.*-(.*?)\"\n)\n",
     "legendFormat": "{{ic_node}} <-> {{peer}}"
    }
   ]
  },
  {
   "title": "packet send rate",
   "type": "timeseries",
   "description": "Estimate of available bandwidth between nodes. Calculated with `CWND`/`RTT`.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  sum by (peer,instance,ic_subnet) (rate(quic_transport_quinn_path_sent_packets{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$period])),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} {{instance}} "
    }
   ]
  },
  {
   "title": "packet loss rate",
   "type": "timeseries",
   "description": "Estimate of available bandwidth between nodes. Calculated with `CWND`/`RTT`.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  sum by (peer,instance,ic_subnet) (rate(quic_transport_quinn_path_lost_packets{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"}[$period])),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)",
     "legendFormat": "{{ic_subnet}} {{instance}} "
    }
   ]
  },
  { "title": "request handler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "bidi errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_request_handle_errors_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", stream=\"bidi\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{error}}"
    }
   ]
  },
  {
   "title": "uni errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_request_handle_errors_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", stream=\"uni\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{error}}"
    }
   ]
  },
  {
   "title": "request rate by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  sum(rate(quic_transport_request_handle_requests_duration_seconds_count{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", handler=~\"$handler\"}[$period])) without (),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{handler}} "
    }
   ]
  },
  {
   "title": "p95 request handler duration by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  histogram_quantile(0.95, sum(rate(quic_transport_request_handle_requests_duration_seconds_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", handler=~\"$handler\"}[$period])) without ()),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{handler}} "
    }
   ]
  },
  {
   "title": "median request handler duration by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  histogram_quantile(0.5, sum(rate(quic_transport_request_handle_requests_duration_seconds_bucket{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", handler=~\"$handler\"}[$period])) without ()),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{handler}} "
    }
   ]
  },
  {
   "title": "data flow out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(quic_transport_request_handle_bytes_sent_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", handler=~\"$handler\"}[$period]),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{handler}} "
    }
   ]
  },
  {
   "title": "data flow in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  rate(quic_transport_request_handle_bytes_received_total{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\", handler=~\"$handler\"}[$period]),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{handler}} "
    }
   ]
  },
  { "title": "tokio metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "tokio slow poll ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_request_handler_tokio_task_slow_poll_ratio{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{error}}"
    }
   ]
  },
  {
   "title": "tokio long delay ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_request_handler_tokio_task_long_delay_ratio{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{error}}"
    }
   ]
  },
  {
   "title": "tokio mean slow poll duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_request_handler_tokio_task_mean_slow_poll_duration{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{error}}"
    }
   ]
  },
  {
   "title": "tokio mean poll duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_request_handler_tokio_task_mean_poll_duration{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{error}}"
    }
   ]
  },
  {
   "title": "tokio mean scheduled poll duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_request_handler_tokio_task_mean_scheduled_duration{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{error}}"
    }
   ]
  },
  {
   "title": "tokio mean idle duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  quic_transport_request_handler_tokio_task_mean_idle_duration{job=\"replica\", ic=\"$ic\", ic_subnet=~\"$ic_subnet\", instance=~\"$instance\"},\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"),\n  \"instance\", \"$1:...:$2\", \"instance\", \"(\\\\[(?:[^:]+[.:]){4}).*(:[^:]+\\\\]?):[0-9]+\"\n)\n",
     "legendFormat": "{{ic_subnet}} {{instance}} {{error}}"
    }
   ]
  }
 ]
}