{
 "title": "Rosetta",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Rosetta API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Synched Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(app, token_display_name) (rosetta_synched_block_height{namespace=\"rosetta-api\"})",
     "legendFormat": "Synched ({{app}}-{{token_display_name}})"
    },
    {
     "expr": "max by(app, token_display_name) (rosetta_target_block_height{namespace=\"rosetta-api\"})",
     "legendFormat": "Target ({{app}}-{{token_display_name}})"
    },
    {
     "expr": "max by(app, token_display_name) (rosetta_verified_block_height{namespace=\"rosetta-api\"})",
     "legendFormat": "Verified ({{app}}-{{token_display_name}})"
    }
   ]
  },
  {
   "title": "Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ledger_sync_attempt_duration_seconds",
     "legendFormat": "{{app}}-{{token_display_name}}"
    }
   ]
  },
  {
   "title": "Total Sync Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "expr": "blockchain_sync_errors_total", "legendFormat": "{{app}}-{{token_display_name}}" }
   ]
  },
  {
   "title": "Total blocks fetched from ledger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time(ledger_sync_blocks_fetched_total[2m])",
     "legendFormat": "{{app}}-{{token_display_name}}"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Reads/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{namespace=\"rosetta-api\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reads Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{namespace=\"rosetta-api\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Writes/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(container_fs_writes_total{namespace=\"rosetta-api\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Writes Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{namespace=\"rosetta-api\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{namespace=~\"rosetta-api\"}",
     "legendFormat": "{{pod}}-rss"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"rosetta-api\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOMs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "container_oom_events_total{namespace=~\"rosetta-api\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"rosetta-api\"}",
     "legendFormat": "{{pod}}-rss"
    }
   ]
  },
  {
   "title": "Container Memory Working Set",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=~\"rosetta-api\"}",
     "legendFormat": "{{pod}}-rss"
    }
   ]
  },
  {
   "title": "Container Memory Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_cache{namespace=~\"rosetta-api\"}",
     "legendFormat": "{{pod}}-rss"
    }
   ]
  }
 ]
}