{
 "title": "Subnet Splitting Pre-Flight",
 "description": "Operational support for subnet splitting. Informs when it is safe to begin the subnet split.",
 "tags": [ "Subnet Splitting" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ic", "label": "IC", "query": { "query": "label_values(ic)" } },
   {
    "name": "ic_subnet",
    "label": "Subnet B",
    "query": {
     "query": "label_values(up{ic=\"$ic\"},ic_subnet)"
    }
   },
   {
    "name": "registry_version",
    "label": "`canister_migrations` registry version",
    "query": "35885"
   },
   { "name": "resolution", "label": "Resolution", "query": "1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Subnet Registry Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  floor(\n      quantile by(ic, ic_subnet) (\n        0.5,\n        mr_registry_version{job=\"replica\",ic=\"$ic\"}\n      )\n    and\n        sum by(ic, ic_subnet) (up{job=\"replica\",ic=\"$ic\"})\n      >\n        2 / 3 * count by(ic, ic_subnet) (up{job=\"replica\",ic=\"$ic\"})\n  ),\n  \"ic_subnet\", \"$1\", \"ic_subnet\", \"([^-]+)-.*\"\n)",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "## How to Use the Subnet Splitting Pre-Flight Dashboard\n\nThe aim  of the Subnet Splitting Pre-Flight dashboard is to inform whether it is safe\nto begin the subnet splitting.\n\nTwo conditions must hold for this:\n1. All subnets must have observed the `canister_migrations` entry for the subnet\n   split.\n2. There must be no shared state between _Subnet B_ (the subnet being created as a\n   result of the subnet split) and any other subnet. I.e. if any incoming or outgoing\n   streams exist, no messages must have been consumed from them.\n\nIn order to ensure both of the above, a third condition must hold: all subnets must\nhave had a `2f+1` quorum of live replicas exporting metrics for a significant part of\nthe selected time range (arbitrarily chosen as 50%).\n\n### Mechanics\n1. Select the IC instance.\n2. Select the subnet being created by the split (_Subnet B_).\n3. Input the registry version corresponding to the `canister_migrations` update (a\n   later registry version is also safe to use).\n4. Zoom out the dashboard time range (_Last N hours_ -> _Last N days_ -> _Last N\nweeks_) from the top right until the _Registry Version Changed_ annotation (marking the\npoint in time when the subnet switched to registry version selected at step (2) above)\nbecomes visible. It is a light blue dotted vertical line on the _Subnet Registry\nVersions_ chart.\n\nAt this point, the red/green stat panels below will show the number of subnets with old\nregistry versions; the number of _Subnet B_ streams with non-zero begin indices; and\nthe number of subnets without a live quorum. If all the stat panels show a value of `0`\nand have a green background, it is safe to proceed with subnet split.\n\nIf the value is non-zero and one or more stat panels have a red background, then the\ntable panels below will display the offending streams/subnets.\n\n### Limitations\n\nDue to Grafana / PromQL limitations, the dashboard will only look up registry versions\nfrom the selected dashboard time range. So ideally the selected range should end at\n\"Now\", rather than some fixed timestamp.\n\nIn order to make the dashboard load in reasonable time, an automatic resolution\n(resulting in around 30 data points across the time range) is used to compute the\nstream indices. This may mean e.g. that the registry versions are actually from a\ntimestamp resulting from rounding \"now\" to the resolution, rather than the most recent\navailable sample.\n\nFinally, zooming out to a longer time range will slow down the dashboard loading\ncorrespondingly. Consider zooming in to a fixed time range that covers the registry\nversion change.\n\nDo note that none of the above will cause false positives (i.e. claim that it is safe\nto proceed with the subnet split entry when it is in fact not safe). At worst, they\nmay cause false negatives (e.g. zooming in too close around the registry version change\nmay make it look like some subnets may not have observed the `canister_migrations`\nentry, when in fact they may have done so since)."
   }
  },
  {
   "title": "Old Registry Versions",
   "type": "stat",
   "description": "Subnets that have not yet observed the `canister_migrations` entry for the subnet split.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 71 }
   ]
  },
  {
   "title": "Shared State",
   "type": "stat",
   "description": "Number of streams to or from `${ic_subnet}` with a non-zero begin index.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 97 }
   ]
  },
  {
   "title": "No Quorum",
   "type": "stat",
   "description": "Subnets (other than `${ic_subnet}`) that did not have a `2f+1` quorum for at least half the selected time range.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 102 }
   ]
  },
  {
   "title": "Subnet `${ic_subnet}` Shared State",
   "type": "table",
   "description": "Shared state (incoming streams with non-zero stream begin indices or any outgoing streams) for subnet `${ic_subnet}`.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max_over_time(\n  (\n      (\n          # Outgoing streams (implying the existence of at least one message).\n          ceil(\n            quantile by(ic_subnet, remote) (\n              0.5,\n              mr_stream_begin{job=\"replica\",ic=\"$ic\",ic_subnet=\"$ic_subnet\"}\n            )\n          )\n        or\n          # Incoming streams with non-zero begin index.\n          ceil(\n              quantile by(ic_subnet, remote) (\n                0.5,\n                mr_stream_begin{job=\"replica\",ic=\"$ic\",ic_subnet!=\"$ic_subnet\",remote=\"$ic_subnet\"}\n              )\n            >\n              0\n          )\n      )\n    and on(ic_subnet)\n      # `2*f+1` quorum\n        sum by(ic_subnet) (up{job=\"replica\",ic=\"$ic\"})\n      >\n        count by(ic_subnet) (up{job=\"replica\",ic=\"$ic\"}) * 2 / 3\n  )[$__range:$resolution]\n)"
    }
   ]
  },
  {
   "title": "Subnets without a quorum",
   "type": "table",
   "description": "Subnets (other than `${ic_subnet}`) without a `2f+1` quorum for at least half of the selected time range.",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "  # Below quorum samples\n  count_over_time(\n    (\n      # `2f+1` quorum\n        sum by(ic_subnet) (up{job=\"replica\",ic=\"$ic\",ic_subnet!=\"$ic_subnet\"})\n      <\n        count by(ic_subnet) (up{job=\"replica\",ic=\"$ic\",ic_subnet!=\"$ic_subnet\"}) * 2 / 3\n    )[$__range:$resolution]\n  )\n>\n  # Expected samples\n  count_over_time(\n    (\n      count by(ic_subnet) (up{job=\"replica\",ic=\"$ic\",ic_subnet!=\"$ic_subnet\"})\n    )[$__range:$resolution]\n  )\n*\n  .5"
    }
   ]
  },
  {
   "title": "Subnets with Old Registry Versions",
   "type": "table",
   "description": "Subnets that have not yet observed the `canister_migrations` entry for the subnet split.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "  floor(\n      quantile by(ic, ic_subnet) (\n        0.5,\n        mr_registry_version{job=\"replica\",ic=\"$ic\",ic_subnet!=\"$ic_subnet\"}\n      )\n    and\n        sum by(ic, ic_subnet) (up{job=\"replica\",ic=\"$ic\",ic_subnet!=\"$ic_subnet\"})\n      >\n        2 / 3 * count by(ic, ic_subnet) (up{job=\"replica\",ic=\"$ic\",ic_subnet!=\"$ic_subnet\"})\n  )\n<\n  $registry_version",
     "legendFormat": "{{ic_subnet}}"
    }
   ]
  }
 ]
}