#![forbid(unsafe_code)]
#![deny(clippy::unwrap_used)]
//! # ic-webmcp-asset-middleware
//!
//! Helpers for serving [WebMCP](https://webmcp.link/) manifests from IC canisters
//! with the required CORS and content-type headers for AI agent discovery.
//!
//! ## What browsers need
//!
//! When Chrome's WebMCP implementation fetches `/.well-known/webmcp.json`,
//! it expects:
//! - `Content-Type: application/json`
//! - `Access-Control-Allow-Origin: *`
//! - `Access-Control-Allow-Methods: GET, OPTIONS`
//! - `Access-Control-Allow-Headers: Content-Type`
//!
//! This crate produces the correct header set and can be used in two ways:
//!
//! 1. **Direct HTTP handler** — embed [`handle_webmcp_request`] in a canister's
//!    `http_request` endpoint.
//! 2. **Asset canister config** — call [`ic_assets_config`] to generate a
//!    `.ic-assets.json5` file that instructs the asset canister to attach CORS
//!    headers to the manifest path automatically.
//!
//! ## Usage in a custom canister
//!
//! ```
//! use ic_webmcp_asset_middleware::handle_webmcp_request;
//!
//! // Typically you would use include_str! to embed files generated by ic-webmcp-codegen:
//! //   const MANIFEST_JSON: &str = include_str!("../webmcp.json");
//! //   const WEBMCP_JS: &str = include_str!("../webmcp.js");
//! let manifest = r#"{"schema_version":"1.0","canister":{"name":"Demo","description":""},"tools":[]}"#;
//! let js = "await import('https://esm.sh/@dfinity/webmcp').then(m => m.initWebMCP());";
//!
//! // In your http_request handler:
//! let resp = handle_webmcp_request("GET", "/.well-known/webmcp.json", manifest, Some(js));
//! assert!(resp.is_some());
//! ```
//!
//! ## Usage with the asset canister
//!
//! ```no_run
//! use ic_webmcp_asset_middleware::ic_assets_config;
//! use std::fs;
//!
//! // Generate .ic-assets.json5 and place it in your assets/ directory:
//! fs::write("assets/.ic-assets.json5", ic_assets_config()).unwrap();
//! ```

/// The canonical path where browsers discover WebMCP manifests.
pub const WEBMCP_MANIFEST_PATH: &str = "/.well-known/webmcp.json";

/// The registration script path.
pub const WEBMCP_JS_PATH: &str = "/webmcp.js";

/// HTTP headers required for WebMCP manifest discovery.
pub const WEBMCP_CORS_HEADERS: &[(&str, &str)] = &[
    ("Content-Type", "application/json"),
    ("Access-Control-Allow-Origin", "*"),
    ("Access-Control-Allow-Methods", "GET, OPTIONS"),
    ("Access-Control-Allow-Headers", "Content-Type"),
    ("Cache-Control", "public, max-age=300"),
];

/// HTTP headers for the webmcp.js script.
pub const WEBMCP_JS_HEADERS: &[(&str, &str)] = &[
    ("Content-Type", "application/javascript; charset=utf-8"),
    ("Access-Control-Allow-Origin", "*"),
    ("Cache-Control", "public, max-age=300"),
];

// ── IC HTTP interface types ──────────────────────────────────────────

/// A minimal HTTP response compatible with the IC asset canister HTTP interface.
#[derive(Debug, Clone)]
pub struct HttpResponse {
    pub status_code: u16,
    pub headers: Vec<(String, String)>,
    pub body: Vec<u8>,
}

impl HttpResponse {
    /// Build a 200 OK JSON response with full WebMCP CORS headers.
    pub fn webmcp_json(body: &str) -> Self {
        HttpResponse {
            status_code: 200,
            headers: WEBMCP_CORS_HEADERS
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
            body: body.as_bytes().to_vec(),
        }
    }

    /// Build a 200 OK JavaScript response with CORS headers.
    pub fn webmcp_js(body: &str) -> Self {
        HttpResponse {
            status_code: 200,
            headers: WEBMCP_JS_HEADERS
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
            body: body.as_bytes().to_vec(),
        }
    }

    /// Build a 200 OK CORS preflight response (for OPTIONS requests).
    pub fn options_preflight() -> Self {
        HttpResponse {
            status_code: 204,
            headers: WEBMCP_CORS_HEADERS
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
            body: Vec::new(),
        }
    }

    /// Build a 404 Not Found response.
    pub fn not_found() -> Self {
        HttpResponse {
            status_code: 404,
            headers: vec![("Content-Type".to_string(), "text/plain".to_string())],
            body: b"Not Found".to_vec(),
        }
    }
}

// ── HTTP request handler ─────────────────────────────────────────────

/// Handle an incoming HTTP request for WebMCP endpoints.
///
/// Returns `None` if the path is not a WebMCP path (caller should fall
/// through to normal asset serving).
///
/// # Example
///
/// ```ignore
/// #[ic_cdk::query]
/// fn http_request(req: HttpRequest) -> HttpResponse {
///     if let Some(response) = ic_webmcp_asset_middleware::handle_webmcp_request(
///         &req.method,
///         &req.url,
///         MANIFEST_JSON,
///         Some(WEBMCP_JS),
///     ) {
///         return response;
///     }
///     // Fall through to normal asset serving
///     serve_asset(&req)
/// }
/// ```
pub fn handle_webmcp_request(
    method: &str,
    path: &str,
    manifest_json: &str,
    webmcp_js: Option<&str>,
) -> Option<HttpResponse> {
    // Strip query string for path matching
    let path = path.split('?').next().unwrap_or(path);

    match (method.to_ascii_uppercase().as_str(), path) {
        ("OPTIONS", p) if p == WEBMCP_MANIFEST_PATH || p == WEBMCP_JS_PATH => {
            Some(HttpResponse::options_preflight())
        }
        ("GET", p) if p == WEBMCP_MANIFEST_PATH => Some(HttpResponse::webmcp_json(manifest_json)),
        ("GET", p) if p == WEBMCP_JS_PATH => match webmcp_js {
            Some(js) => Some(HttpResponse::webmcp_js(js)),
            None => Some(HttpResponse::not_found()),
        },
        _ => None,
    }
}

// ── .ic-assets.json5 generator ───────────────────────────────────────

/// Generate `.ic-assets.json5` configuration for the IC asset canister.
///
/// The asset canister reads this file to attach HTTP headers to specific
/// paths. This function produces the snippet needed to add CORS headers
/// to the WebMCP manifest and JS paths.
///
/// The generated config should be placed in the `assets/` directory as
/// `.ic-assets.json5`.
pub fn ic_assets_config() -> String {
    let cors_headers: Vec<String> = WEBMCP_CORS_HEADERS
        .iter()
        .map(|(k, v)| format!("      {{ \"name\": \"{}\", \"value\": \"{}\" }}", k, v))
        .collect();

    let js_headers: Vec<String> = WEBMCP_JS_HEADERS
        .iter()
        .map(|(k, v)| format!("      {{ \"name\": \"{}\", \"value\": \"{}\" }}", k, v))
        .collect();

    format!(
        r#"// .ic-assets.json5 — WebMCP CORS configuration
// Auto-generated by ic-webmcp-asset-middleware
// Place this in your assets/ directory alongside your other assets.
[
  {{
    "match": "/.well-known/webmcp.json",
    "headers": [
{}
    ],
    "allow_raw_access": true
  }},
  {{
    "match": "/webmcp.js",
    "headers": [
{}
    ],
    "allow_raw_access": true
  }}
]
"#,
        cors_headers.join(",\n"),
        js_headers.join(",\n"),
    )
}

// ── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_handle_manifest_get() {
        let resp = handle_webmcp_request(
            "GET",
            "/.well-known/webmcp.json",
            r#"{"schema_version":"1.0"}"#,
            None,
        );
        let resp = resp.expect("should handle manifest GET");
        assert_eq!(resp.status_code, 200);
        assert_eq!(resp.body, br#"{"schema_version":"1.0"}"#);
        assert!(
            resp.headers
                .iter()
                .any(|(k, v)| k == "Access-Control-Allow-Origin" && v == "*")
        );
        assert!(
            resp.headers
                .iter()
                .any(|(k, v)| k == "Content-Type" && v == "application/json")
        );
    }

    #[test]
    fn test_handle_js_get() {
        let js = "console.log('webmcp');";
        let resp = handle_webmcp_request("GET", "/webmcp.js", "{}", Some(js));
        let resp = resp.expect("should handle JS GET");
        assert_eq!(resp.status_code, 200);
        assert_eq!(std::str::from_utf8(&resp.body).unwrap(), js);
        assert!(
            resp.headers
                .iter()
                .any(|(k, _)| k == "Access-Control-Allow-Origin")
        );
    }

    #[test]
    fn test_handle_js_not_found_when_none() {
        let resp = handle_webmcp_request("GET", "/webmcp.js", "{}", None);
        let resp = resp.expect("should return 404");
        assert_eq!(resp.status_code, 404);
    }

    #[test]
    fn test_handle_options_preflight() {
        let resp = handle_webmcp_request("OPTIONS", "/.well-known/webmcp.json", "{}", None);
        let resp = resp.expect("should handle OPTIONS");
        assert_eq!(resp.status_code, 204);
    }

    #[test]
    fn test_non_webmcp_path_returns_none() {
        let resp = handle_webmcp_request("GET", "/index.html", "{}", None);
        assert!(resp.is_none());
    }

    #[test]
    fn test_path_with_query_string() {
        let resp = handle_webmcp_request("GET", "/.well-known/webmcp.json?v=1", r#"{}"#, None);
        assert!(resp.is_some());
        assert_eq!(resp.unwrap().status_code, 200);
    }

    #[test]
    fn test_case_insensitive_method() {
        let resp = handle_webmcp_request("get", "/.well-known/webmcp.json", r#"{}"#, None);
        assert!(resp.is_some());
        assert_eq!(resp.unwrap().status_code, 200);
    }

    #[test]
    fn test_ic_assets_config_contains_required_paths() {
        let config = ic_assets_config();
        assert!(config.contains("/.well-known/webmcp.json"));
        assert!(config.contains("/webmcp.js"));
        assert!(config.contains("Access-Control-Allow-Origin"));
        assert!(config.contains("allow_raw_access"));
    }
}
