= Public HTTPS Endpoint
:toc:

== Introduction

The public endpoint is responsible for processing https requests as specified in the
https://internetcomputer.org/docs/current/references/ic-interface-spec#http-interface[IC specification]. Processing semantics include:

* accepting TCP connections
* TLS handshake for connections using HTTPS
* forwarding, potentially after a transform, each request to the corresponding upstream component
* request validation according to the https://internetcomputer.org/docs/current/references/ic-interface-spec#http-interface[interface specification of the IC]
* async accepting and serving of connections 
* DoS mitigation, as described in the link:rs/http_endpoints/README.adoc[parent README.adoc]

=== Startup

The HTTPS endpoint starts serving requests as soon as `+start_server+` is called. This is driven by operational needs,
we want to serve `+/status+`, `+/_/dashboard+`, `+/_/pprof+`,`+/catch_up_package+` endpoints as soon as possible.

In order to serve `+query+`, `+read_state+` or `+call+` requests, the replica needs to meet a few preconditions. The preconditions are
encoded in the `+ic_types::messages::ReplicaHealthStatus+` enum which is part of the `+/status+` response. 
If you try to send, for example, a query request, before the replica enters `+ReplicaHealthStatus::Healthy+`, then *503 Service Unavailable*
is returned as part of the response.

=== Code structure

For each HTTP(s) endpoint there is a module that processes the corresponding requests (`+query.rs+`,
`+call.rs+`, `+query.rs+`, `+read_state.rs+`, etc.). 

=== Http response status codes

==== Call

According to the https://internetcomputer.org/docs/interface-spec/index.html[IC spec], first steps of the high-level workflow of calling a canister are:

. A user submits a call via the HTTPS Interface. No useful information is returned in the immediate response (as such information cannot be trustworthy anyways).
. For a certain amount of time, the IC behaves as if it does not know about the call.
. The IC asks the targeted canister if it is willing to accept this message and be charged for the expense of processing it. This uses the Ingress message inspection API for normal calls. 
. At some point, the IC may accept the call for processing and set its status to received. This indicates that the IC as a whole has received the call and plans on processing it (although it may still not get processed if the IC is under high load).

In the existing implementation of the IC protocol, if an error occurs within the HTTPS endpoint, which prevents a call request from being executed by the IC, then a 4xx or 5xx error code is returned.
When assigning an error code try to answer the following question: "is this something actionable by the caller, the canister owner, the IC operator?". 4xx is for caller and 5xx is for canister owner or IC operator.

Alternatives for http status codes when inspecting a message (canister code) fails:

. *Return only 2xx*. This would require the user to keep polling past the ingress expiry before they could retry. This goes against returning an error when we know a request won't be executed by the IC. For example, if an user sends invalid request, they will have to poll for 5+ minutes before confirming the request is missing from the IC. 
. *Return only 4xx*. Per the HTTP spec, we simply cannot return a 4xx status code if the client submitted a valid request at the right time (e.g. not trying to stop an already stopped canister).
. *Return only 502 and/or 504*. Per the HTTP spec those errors are more appropriate for proxies that act on behalf of the user. This option means splitting the 5xx status codes between replica and IC protocol. Unfortunately,
there is no clean way of splitting 5xx status codes and doing so would hide information (e.g. if you put all IC protocol errors behind a 502 and/or 504). Splitting the 5xx status codes is not necessary because, as it turns out, there really aren't all that many replica errors that may be caused by bugs or deployment issues (it's mostly network errors and such).

==== Query

==== Read state
