[package]
name = "metrics-proxy"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "metrics-proxy"
path = "src/main.rs"

[dependencies]
axum = { workspace = true, features = ["macros"] }
axum-otel-metrics = { workspace = true }
clap = { workspace = true }
duration-string = { workspace = true }
exitcode = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-prometheus = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["metrics"] }
pin-project-lite = { workspace = true }
prometheus = { workspace = true }
prometheus-parse = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
simple_logger = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["timeout"] }
url = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
