[package]
name = "ic-ckbtc-agent"
description = "Agent for the ckBTC minter."
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
candid = { workspace = true }
ic-agent = { workspace = true }
ic-ckbtc-minter = { path = "../minter" }
ic-http-types = { path = "../../../../packages/ic-http-types" }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
