//! IDs of neurons generated by
//! `ic_nns_governance::GovernanceCanisterInitPayloadBuilder::
//! with_test_neurons`.
// To update or add more, add print statements to `with_test_neurons` to print
// the generated neuron IDs and copy the printed IDs here.

/// ID ot Test Neuron 1
pub const TEST_NEURON_1_ID: u64 = 449479075714955186;
/// ID ot Test Neuron 2
pub const TEST_NEURON_2_ID: u64 = 4368585614685248742;
/// ID ot Test Neuron 3
pub const TEST_NEURON_3_ID: u64 = 4884056990215423907;

/// The sum of the total ICP staked in test neurons.
pub const TEST_NEURON_TOTAL_STAKE_DOMS: u64 = 1_110_000_000;
